// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: fOS_1

#ifndef _FOS_1_UI_H
#define _FOS_1_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "ui_ScreenHome.h"
#include "ui_ScreenSettings.h"
#include "ui_ScreenFileManager.h"
#include "ui_ScreenAppLauncher.h"
#include "ui_ScreenText.h"
#include "ui_ScreenRadio.h"
#include "ui_ScreenWeather.h"
#include "ui_ScreenClock.h"
#include "ui_ScreenCalculator.h"
#include "ui_AppContent.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_350490791);   // assets/settings-2.png
LV_IMG_DECLARE( ui_img_folder_png);   // assets/folder.png
LV_IMG_DECLARE( ui_img_application_png);   // assets/application.png
LV_IMG_DECLARE( ui_img_1781796769);   // assets/text-size-2.png
LV_IMG_DECLARE( ui_img_1607212695);   // assets/radio-11.png
LV_IMG_DECLARE( ui_img_1045517857);   // assets/cloudy-day-2.png
LV_IMG_DECLARE( ui_img_294430296);   // assets/clock-2.png
LV_IMG_DECLARE( ui_img_1548352994);   // assets/calculator-2.png
LV_IMG_DECLARE( ui_img_1837598647);   // assets/Wi-Fi.png
LV_IMG_DECLARE( ui_img_fos_256x256_png);   // assets/fOS_256x256.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
