// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: fOS_1

#ifndef UI_APPCONTENT_H
#define UI_APPCONTENT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_AppContent
extern void ui_AppContent_screen_init(void);
extern void ui_AppContent_screen_destroy(void);
extern lv_obj_t *ui_AppContent;
extern void ui_event_HomeButton9( lv_event_t * e);
extern lv_obj_t *ui_HomeButton9;
extern lv_obj_t *ui_LabelMenu10;
extern lv_obj_t *ui_AppName;
extern lv_obj_t *ui_AppContentArea;
// CUSTOM VARIABLES
extern lv_obj_t *uic_AppContent;
extern lv_obj_t *uic_AppName;
extern lv_obj_t *uic_AppContentArea;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

