// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: fOS_1

#include "ui.h"

lv_obj_t *uic_AppContentArea;
lv_obj_t *uic_AppName;
lv_obj_t *uic_AppContent;
lv_obj_t *ui_AppContent = NULL;lv_obj_t *ui_HomeButton9 = NULL;lv_obj_t *ui_LabelMenu10 = NULL;lv_obj_t *ui_AppName = NULL;lv_obj_t *ui_AppContentArea = NULL;
// event funtions
void ui_event_HomeButton9( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenAppLauncher, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenAppLauncher_screen_init);
}
}

// build funtions

void ui_AppContent_screen_init(void)
{
ui_AppContent = lv_obj_create(NULL);
lv_obj_clear_flag( ui_AppContent, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_HomeButton9 = lv_btn_create(ui_AppContent);
lv_obj_set_width( ui_HomeButton9, 100);
lv_obj_set_height( ui_HomeButton9, 50);
lv_obj_set_x( ui_HomeButton9, -340 );
lv_obj_set_y( ui_HomeButton9, -210 );
lv_obj_set_align( ui_HomeButton9, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_HomeButton9, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_HomeButton9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_HomeButton9, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_HomeButton9, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HomeButton9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelMenu10 = lv_label_create(ui_HomeButton9);
lv_obj_set_width( ui_LabelMenu10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelMenu10, LV_SIZE_CONTENT);   /// 0
lv_obj_set_align( ui_LabelMenu10, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelMenu10,"Menu");
lv_obj_set_style_text_color(ui_LabelMenu10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelMenu10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_LabelMenu10, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelMenu10, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AppName = lv_label_create(ui_AppContent);
lv_obj_set_width( ui_AppName, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AppName, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_AppName, 0 );
lv_obj_set_y( ui_AppName, -210 );
lv_obj_set_align( ui_AppName, LV_ALIGN_CENTER );
lv_label_set_text(ui_AppName,"No app found!");
lv_obj_set_style_text_font(ui_AppName, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AppContentArea = lv_obj_create(ui_AppContent);
lv_obj_remove_style_all(ui_AppContentArea);
lv_obj_set_width( ui_AppContentArea, 780);
lv_obj_set_height( ui_AppContentArea, 400);
lv_obj_set_x( ui_AppContentArea, 0 );
lv_obj_set_y( ui_AppContentArea, 29 );
lv_obj_set_align( ui_AppContentArea, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_AppContentArea, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_HomeButton9, ui_event_HomeButton9, LV_EVENT_ALL, NULL);
uic_AppContent = ui_AppContent;
uic_AppName = ui_AppName;
uic_AppContentArea = ui_AppContentArea;

}

void ui_AppContent_screen_destroy(void)
{
   if (ui_AppContent) lv_obj_del(ui_AppContent);

// NULL screen variables
uic_AppContent= NULL;
ui_AppContent= NULL;
ui_HomeButton9= NULL;
ui_LabelMenu10= NULL;
uic_AppName= NULL;
ui_AppName= NULL;
uic_AppContentArea= NULL;
ui_AppContentArea= NULL;

}
