// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: fOS_1

#include "ui.h"

// COMPONENT Switch

lv_obj_t *ui_Switch_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_Switch;
cui_Switch = lv_btn_create(comp_parent);
lv_obj_set_width( cui_Switch, 100);
lv_obj_set_height( cui_Switch, 50);
lv_obj_set_align( cui_Switch, LV_ALIGN_CENTER );
lv_obj_add_flag( cui_Switch, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( cui_Switch, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_SWITCH_NUM);
children[UI_COMP_SWITCH_SWITCH] = cui_Switch;
lv_obj_add_event_cb(cui_Switch, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_Switch, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_Switch_create_hook(cui_Switch);
return cui_Switch; 
}

