// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: fOS_1

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void updateSDUI(lv_event_t * e);
void StartAppLauncher(lv_event_t * e);
void fillFileRoller_TextViewer(lv_event_t * e);
void fillFileRoller_Radio(lv_event_t * e);
void StartWeatherApp(lv_event_t * e);
void updateSystemInfo(lv_event_t * e);
void ReloadWiFiConnection(lv_event_t * e);
void SaveWifiConnection(lv_event_t * e);
void SaveTimeZone(lv_event_t * e);
void BackToHomeFromFileManager(lv_event_t * e);
void DeleteFileSelected(lv_event_t * e);
void BackToHomeFromText(lv_event_t * e);
void OpenNewFile(lv_event_t * e);
void save_text_file(lv_event_t * e);
void load_selected_file(lv_event_t * e);
void PlayRadio(lv_event_t * e);
void StopwatchPlay(lv_event_t * e);
void StopwatchReset(lv_event_t * e);
void keypad_event_handler(lv_event_t * e);
void operator_event_handler(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
