// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: fOS_1

#include "ui.h"

void updateSDUI(lv_event_t * e)
{
	updateSDUIData();
}

void updateSystemInfo(lv_event_t * e)
{
	updateSystemInfoData();
}

void DeleteFileSelected(lv_event_t * e)
{
  if (lv_event_get_code(e) == LV_EVENT_CLICKED) {
        deleteSelectedFile();
    }
}

void save_text_file(lv_event_t * e)
{
	// Your code here
}

void load_selected_file(lv_event_t * e)
{
	// Your code here
}
