// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: fOS_1

#ifndef UI_SCREENCLOCK_H
#define UI_SCREENCLOCK_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenClock
extern void ui_ScreenClock_screen_init(void);
extern void ui_ScreenClock_screen_destroy(void);
extern lv_obj_t *ui_ScreenClock;
extern void ui_event_HomeButton6( lv_event_t * e);
extern lv_obj_t *ui_HomeButton6;
extern lv_obj_t *ui_LabelMenu7;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

