// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: fOS_1

#ifndef UI_SCREENRADIO_H
#define UI_SCREENRADIO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenRadio
extern void ui_ScreenRadio_screen_init(void);
extern void ui_ScreenRadio_screen_destroy(void);
extern lv_obj_t *ui_ScreenRadio;
extern void ui_event_HomeButton4( lv_event_t * e);
extern lv_obj_t *ui_HomeButton4;
extern lv_obj_t *ui_LabelMenu5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

