// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: fOS_1

#include "ui.h"

lv_obj_t *ui_ScreenRadio = NULL;lv_obj_t *ui_HomeButton4 = NULL;lv_obj_t *ui_LabelMenu5 = NULL;
// event funtions
void ui_event_HomeButton4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenHome, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_ScreenHome_screen_init);
}
}

// build funtions

void ui_ScreenRadio_screen_init(void)
{
ui_ScreenRadio = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenRadio, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_HomeButton4 = lv_btn_create(ui_ScreenRadio);
lv_obj_set_width( ui_HomeButton4, 100);
lv_obj_set_height( ui_HomeButton4, 50);
lv_obj_set_x( ui_HomeButton4, -340 );
lv_obj_set_y( ui_HomeButton4, -210 );
lv_obj_set_align( ui_HomeButton4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_HomeButton4, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_HomeButton4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_HomeButton4, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_HomeButton4, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HomeButton4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelMenu5 = lv_label_create(ui_ScreenRadio);
lv_obj_set_width( ui_LabelMenu5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelMenu5, LV_SIZE_CONTENT);   /// 0
lv_obj_set_x( ui_LabelMenu5, -340 );
lv_obj_set_y( ui_LabelMenu5, -210 );
lv_obj_set_align( ui_LabelMenu5, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelMenu5,"Menu");
lv_obj_set_style_text_color(ui_LabelMenu5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelMenu5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_LabelMenu5, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelMenu5, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_HomeButton4, ui_event_HomeButton4, LV_EVENT_ALL, NULL);

}

void ui_ScreenRadio_screen_destroy(void)
{
   if (ui_ScreenRadio) lv_obj_del(ui_ScreenRadio);

// NULL screen variables
ui_ScreenRadio= NULL;
ui_HomeButton4= NULL;
ui_LabelMenu5= NULL;

}
