// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: fOS_1

#ifndef UI_SCREENSETTINGS_H
#define UI_SCREENSETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenSettings
extern void ui_ScreenSettings_screen_init(void);
extern void ui_ScreenSettings_screen_destroy(void);
extern lv_obj_t *ui_ScreenSettings;
extern void ui_event_HomeButton( lv_event_t * e);
extern lv_obj_t *ui_HomeButton;
extern lv_obj_t *ui_LabelMenu1;
extern void ui_event_ButtonSettingsSystemInfo( lv_event_t * e);
extern lv_obj_t *ui_ButtonSettingsSystemInfo;
extern lv_obj_t *ui_LabelSettingsSystemInfo;
// CUSTOM VARIABLES
extern lv_obj_t *uic_ScreenSettings;
extern lv_obj_t *uic_ButtonSettingsSystemInfo;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

