// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: fOS_1

#ifndef UI_SCREENCLOCK_H
#define UI_SCREENCLOCK_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenClock
extern void ui_ScreenClock_screen_init(void);
extern void ui_ScreenClock_screen_destroy(void);
extern lv_obj_t *ui_ScreenClock;
extern lv_obj_t *ui_TabView1;
extern lv_obj_t *ui_Current_Time;
extern lv_obj_t *ui_RealTimeClock;
extern lv_obj_t *ui_Calendar;
extern lv_obj_t *ui_Stopwatch;
extern void ui_event_ButtonStopwatchPlay( lv_event_t * e);
extern lv_obj_t *ui_ButtonStopwatchPlay;
extern lv_obj_t *ui_LabelStopwatchPlay;
extern void ui_event_ButtonStopwatchReset( lv_event_t * e);
extern lv_obj_t *ui_ButtonStopwatchReset;
extern lv_obj_t *ui_LabelStopwatchReset;
extern lv_obj_t *ui_LabelStopwatchDisplay;
extern void ui_event_HomeButton6( lv_event_t * e);
extern lv_obj_t *ui_HomeButton6;
extern lv_obj_t *ui_LabelMenu7;
// CUSTOM VARIABLES
extern lv_obj_t *uic_TabView1;
extern lv_obj_t *uic_RealTimeClock;
extern lv_obj_t *uic_Calendar;
extern lv_obj_t *uic_ButtonStopwatchPlay;
extern lv_obj_t *uic_LabelStopwatchPlay;
extern lv_obj_t *uic_ButtonStopwatchReset;
extern lv_obj_t *uic_LabelStopwatchDisplay;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

