// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: fOS_1

#ifndef UI_SCREENFILEMANAGER_H
#define UI_SCREENFILEMANAGER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenFileManager
extern void ui_ScreenFileManager_screen_init(void);
extern void ui_ScreenFileManager_screen_destroy(void);
extern lv_obj_t *ui_ScreenFileManager;
extern void ui_event_HomeButton1( lv_event_t * e);
extern lv_obj_t *ui_HomeButton1;
extern lv_obj_t *ui_LabelMenu2;
extern void ui_event_ButtonDeleteFile( lv_event_t * e);
extern lv_obj_t *ui_ButtonDeleteFile;
extern void ui_event_LabelDeleteFile( lv_event_t * e);
extern lv_obj_t *ui_LabelDeleteFile;
extern lv_obj_t *ui_FileRollerFileManager;
extern lv_obj_t *ui_BarSD;
extern lv_obj_t *ui_LabelSDInfo;
// CUSTOM VARIABLES
extern lv_obj_t *uic_ButtonDeleteFile;
extern lv_obj_t *uic_LabelDeleteFile;
extern lv_obj_t *uic_FileRollerFileManager;
extern lv_obj_t *uic_BarSD;
extern lv_obj_t *uic_LabelSDInfo;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

