// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: fOS_1

#ifndef UI_SCREENCALCULATOR_H
#define UI_SCREENCALCULATOR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenCalculator
extern void ui_ScreenCalculator_screen_init(void);
extern void ui_ScreenCalculator_screen_destroy(void);
extern lv_obj_t *ui_ScreenCalculator;
extern void ui_event_HomeButton7( lv_event_t * e);
extern lv_obj_t *ui_HomeButton7;
extern lv_obj_t *ui_LabelMenu8;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

