// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: fOS_1

#ifndef UI_SCREENRADIO_H
#define UI_SCREENRADIO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenRadio
extern void ui_ScreenRadio_screen_init(void);
extern void ui_ScreenRadio_screen_destroy(void);
extern lv_obj_t *ui_ScreenRadio;
extern void ui_event_HomeButton4( lv_event_t * e);
extern lv_obj_t *ui_HomeButton4;
extern lv_obj_t *ui_LabelMenu5;
extern void ui_event_ButtonPlayRadio( lv_event_t * e);
extern lv_obj_t *ui_ButtonPlayRadio;
extern lv_obj_t *ui_LabelPlayRadio;
extern lv_obj_t *ui_TabViewMusicSelector;
extern lv_obj_t *ui_FilePlayerSelector;
extern lv_obj_t *ui_RollerOptionRadio;
extern lv_obj_t *ui_WebRadioSelector;
extern lv_obj_t *ui_RollerOptionWebRadio;
// CUSTOM VARIABLES
extern lv_obj_t *uic_ButtonPlayRadio;
extern lv_obj_t *uic_TabViewMusicSelector;
extern lv_obj_t *uic_FilePlayerSelector;
extern lv_obj_t *uic_RollerOptionRadio;
extern lv_obj_t *uic_WebRadioSelector;
extern lv_obj_t *uic_RollerOptionWebRadio;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

