// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: fOS_1

#ifndef UI_SCREENWEATHER_H
#define UI_SCREENWEATHER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenWeather
extern void ui_ScreenWeather_screen_init(void);
extern void ui_ScreenWeather_screen_destroy(void);
extern lv_obj_t *ui_ScreenWeather;
extern void ui_event_HomeButton5( lv_event_t * e);
extern lv_obj_t *ui_HomeButton5;
extern lv_obj_t *ui_LabelMenu6;
extern lv_obj_t *ui_RollerWeatherData;
extern lv_obj_t *ui_LabelWeatherTemperature;
extern lv_obj_t *ui_LabelWeatherInformation;
// CUSTOM VARIABLES
extern lv_obj_t *uic_RollerWeatherData;
extern lv_obj_t *uic_LabelWeatherTemperature;
extern lv_obj_t *uic_LabelWeatherInformation;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

