// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: fOS_1

#include "ui.h"

lv_obj_t *uic_LabelSDInfo;
lv_obj_t *uic_BarSD;
lv_obj_t *uic_FileRollerFileManager;
lv_obj_t *uic_LabelDeleteFile;
lv_obj_t *uic_ButtonDeleteFile;
lv_obj_t *ui_ScreenFileManager = NULL;lv_obj_t *ui_HomeButton1 = NULL;lv_obj_t *ui_LabelMenu2 = NULL;lv_obj_t *ui_ButtonDeleteFile = NULL;lv_obj_t *ui_LabelDeleteFile = NULL;lv_obj_t *ui_FileRollerFileManager = NULL;lv_obj_t *ui_BarSD = NULL;lv_obj_t *ui_LabelSDInfo = NULL;
// event funtions
void ui_event_HomeButton1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenHome, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenHome_screen_init);
}
if ( event_code == LV_EVENT_CLICKED) {
      BackToHomeFromFileManager( e );
}
}

void ui_event_ButtonDeleteFile( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      DeleteFileSelected( e );
}
}

void ui_event_LabelDeleteFile( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      DeleteFileSelected( e );
}
}

// build funtions

void ui_ScreenFileManager_screen_init(void)
{
ui_ScreenFileManager = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenFileManager, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_text_font(ui_ScreenFileManager, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HomeButton1 = lv_btn_create(ui_ScreenFileManager);
lv_obj_set_width( ui_HomeButton1, 100);
lv_obj_set_height( ui_HomeButton1, 50);
lv_obj_set_x( ui_HomeButton1, -340 );
lv_obj_set_y( ui_HomeButton1, -210 );
lv_obj_set_align( ui_HomeButton1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_HomeButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_HomeButton1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_HomeButton1, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_HomeButton1, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HomeButton1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelMenu2 = lv_label_create(ui_HomeButton1);
lv_obj_set_width( ui_LabelMenu2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelMenu2, LV_SIZE_CONTENT);   /// 0
lv_obj_set_align( ui_LabelMenu2, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelMenu2,"Menu");
lv_obj_set_style_text_color(ui_LabelMenu2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelMenu2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_LabelMenu2, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelMenu2, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonDeleteFile = lv_btn_create(ui_ScreenFileManager);
lv_obj_set_width( ui_ButtonDeleteFile, 203);
lv_obj_set_height( ui_ButtonDeleteFile, 50);
lv_obj_set_x( ui_ButtonDeleteFile, 287 );
lv_obj_set_y( ui_ButtonDeleteFile, -210 );
lv_obj_set_align( ui_ButtonDeleteFile, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonDeleteFile, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonDeleteFile, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ButtonDeleteFile, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ButtonDeleteFile, lv_color_hex(0xE8210B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonDeleteFile, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelDeleteFile = lv_label_create(ui_ButtonDeleteFile);
lv_obj_set_width( ui_LabelDeleteFile, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelDeleteFile, LV_SIZE_CONTENT);   /// 0
lv_obj_set_align( ui_LabelDeleteFile, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelDeleteFile,"Delete file");
lv_obj_set_style_text_color(ui_LabelDeleteFile, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelDeleteFile, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_LabelDeleteFile, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelDeleteFile, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FileRollerFileManager = lv_roller_create(ui_ScreenFileManager);
lv_roller_set_options( ui_FileRollerFileManager, "No file found", LV_ROLLER_MODE_NORMAL );
lv_obj_set_width( ui_FileRollerFileManager, 780);
lv_obj_set_height( ui_FileRollerFileManager, 260);
lv_obj_set_x( ui_FileRollerFileManager, 0 );
lv_obj_set_y( ui_FileRollerFileManager, -45 );
lv_obj_set_align( ui_FileRollerFileManager, LV_ALIGN_CENTER );
lv_obj_set_style_text_align(ui_FileRollerFileManager, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_FileRollerFileManager, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BarSD = lv_bar_create(ui_ScreenFileManager);
lv_obj_set_width( ui_BarSD, 780);
lv_obj_set_height( ui_BarSD, 34);
lv_obj_set_x( ui_BarSD, 0 );
lv_obj_set_y( ui_BarSD, 205 );
lv_obj_set_align( ui_BarSD, LV_ALIGN_CENTER );

ui_LabelSDInfo = lv_label_create(ui_ScreenFileManager);
lv_obj_set_width( ui_LabelSDInfo, 775);
lv_obj_set_height( ui_LabelSDInfo, 75);
lv_obj_set_x( ui_LabelSDInfo, 1 );
lv_obj_set_y( ui_LabelSDInfo, 135 );
lv_obj_set_align( ui_LabelSDInfo, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelSDInfo,"No SD card detected.");
lv_obj_set_style_text_font(ui_LabelSDInfo, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_HomeButton1, ui_event_HomeButton1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_LabelDeleteFile, ui_event_LabelDeleteFile, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonDeleteFile, ui_event_ButtonDeleteFile, LV_EVENT_ALL, NULL);
uic_ButtonDeleteFile = ui_ButtonDeleteFile;
uic_LabelDeleteFile = ui_LabelDeleteFile;
uic_FileRollerFileManager = ui_FileRollerFileManager;
uic_BarSD = ui_BarSD;
uic_LabelSDInfo = ui_LabelSDInfo;

}

void ui_ScreenFileManager_screen_destroy(void)
{
   if (ui_ScreenFileManager) lv_obj_del(ui_ScreenFileManager);

// NULL screen variables
ui_ScreenFileManager= NULL;
ui_HomeButton1= NULL;
ui_LabelMenu2= NULL;
uic_ButtonDeleteFile= NULL;
ui_ButtonDeleteFile= NULL;
uic_LabelDeleteFile= NULL;
ui_LabelDeleteFile= NULL;
uic_FileRollerFileManager= NULL;
ui_FileRollerFileManager= NULL;
uic_BarSD= NULL;
ui_BarSD= NULL;
uic_LabelSDInfo= NULL;
ui_LabelSDInfo= NULL;

}
