// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: fOS_1

#include "ui.h"

lv_obj_t *uic_SliderBrightness;
lv_obj_t *uic_ColorwheelSettings;
lv_obj_t *uic_ButtonSaveAppearance;
lv_obj_t *uic_AppearanceContainer;
lv_obj_t *uic_TimeZoneManager;
lv_obj_t *uic_ButtonSaveTimeZone;
lv_obj_t *uic_TimeZoneContainer;
lv_obj_t *uic_KeyboardWifi;
lv_obj_t *uic_TextAreaWifiPassword;
lv_obj_t *uic_TextAreaWifiSSID;
lv_obj_t *uic_ButtonSaveWifi;
lv_obj_t *uic_WifiScreenContainer;
lv_obj_t *uic_systemInfoLabel;
lv_obj_t *uic_ButtonBack;
lv_obj_t *uic_InfoScreenContainer;
lv_obj_t *uic_ButtonSettingsAppearance;
lv_obj_t *uic_ButtonSettingsTimeZone;
lv_obj_t *uic_ButtonSettingsSystemInfo;
lv_obj_t *uic_ScreenSettings;
lv_obj_t *ui_ScreenSettings = NULL;lv_obj_t *ui_HomeButton = NULL;lv_obj_t *ui_LabelMenu1 = NULL;lv_obj_t *ui_ButtonSettingsSystemInfo = NULL;lv_obj_t *ui_LabelSettingsSystemInfo = NULL;lv_obj_t *ui_ButtonSettingsWiFi = NULL;lv_obj_t *ui_LabelSettingsWiFi = NULL;lv_obj_t *ui_ButtonSettingsWiFi1 = NULL;lv_obj_t *ui_LabelSettingsWiFi1 = NULL;lv_obj_t *ui_ButtonSettingsTimeZone = NULL;lv_obj_t *ui_LabelSettingsTimeZone = NULL;lv_obj_t *ui_ButtonSettingsAppearance = NULL;lv_obj_t *ui_LabelSettingsTimeZone1 = NULL;lv_obj_t *ui_InfoScreenContainer = NULL;lv_obj_t *ui_ButtonBack = NULL;lv_obj_t *ui_LabelBack = NULL;lv_obj_t *ui_LabelHardwareInformation = NULL;lv_obj_t *ui_systemInfoLabel = NULL;lv_obj_t *ui_LabelSoftwareInformation = NULL;lv_obj_t *ui_LabelSoftwareInformationData = NULL;lv_obj_t *ui_WifiScreenContainer = NULL;lv_obj_t *ui_ButtonBack1 = NULL;lv_obj_t *ui_LabelBack1 = NULL;lv_obj_t *ui_ButtonSaveWifi = NULL;lv_obj_t *ui_LabelBack2 = NULL;lv_obj_t *ui_LabelWifiSSID = NULL;lv_obj_t *ui_TextAreaWifiSSID = NULL;lv_obj_t *ui_LabelWifiPassword = NULL;lv_obj_t *ui_TextAreaWifiPassword = NULL;lv_obj_t *ui_KeyboardWifi = NULL;lv_obj_t *ui_TimeZoneContainer = NULL;lv_obj_t *ui_ButtonBack2 = NULL;lv_obj_t *ui_LabelBack3 = NULL;lv_obj_t *ui_ButtonSaveTimeZone = NULL;lv_obj_t *ui_LabelBack4 = NULL;lv_obj_t *ui_TimeZoneManager = NULL;lv_obj_t *ui_AppearanceContainer = NULL;lv_obj_t *ui_ButtonBack3 = NULL;lv_obj_t *ui_LabelBack5 = NULL;lv_obj_t *ui_ButtonSaveAppearance = NULL;lv_obj_t *ui_LabelBack6 = NULL;lv_obj_t *ui_ColorwheelSettings = NULL;lv_obj_t *ui_LabelColorwheel = NULL;lv_obj_t *ui_SliderBrightness = NULL;lv_obj_t *ui_LabelBrightness = NULL;
// event funtions
void ui_event_HomeButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenHome, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenHome_screen_init);
}
}

void ui_event_ButtonSettingsSystemInfo( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_InfoScreenContainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
if ( event_code == LV_EVENT_CLICKED) {
      updateSystemInfo( e );
}
}

void ui_event_ButtonSettingsWiFi( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_WifiScreenContainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

void ui_event_ButtonSettingsWiFi1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      ReloadWiFiConnection( e );
}
}

void ui_event_ButtonSettingsTimeZone( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_TimeZoneContainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

void ui_event_ButtonSettingsAppearance( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_AppearanceContainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

void ui_event_ButtonBack( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_InfoScreenContainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_ButtonBack1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_WifiScreenContainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_ButtonSaveWifi( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      SaveWifiConnection( e );
}
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_WifiScreenContainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_TextAreaWifiSSID( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_keyboard_set_target(ui_KeyboardWifi,  ui_TextAreaWifiSSID);
}
}

void ui_event_TextAreaWifiPassword( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_keyboard_set_target(ui_KeyboardWifi,  ui_TextAreaWifiPassword);
}
}

void ui_event_ButtonBack2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_TimeZoneContainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_ButtonSaveTimeZone( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      SaveTimeZone( e );
}
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_TimeZoneContainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_ButtonBack3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_AppearanceContainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_ButtonSaveAppearance( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      SaveAppearanceChanges( e );
}
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_AppearanceContainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

// build funtions

void ui_ScreenSettings_screen_init(void)
{
ui_ScreenSettings = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenSettings, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_HomeButton = lv_btn_create(ui_ScreenSettings);
lv_obj_set_width( ui_HomeButton, 100);
lv_obj_set_height( ui_HomeButton, 50);
lv_obj_set_x( ui_HomeButton, -340 );
lv_obj_set_y( ui_HomeButton, -210 );
lv_obj_set_align( ui_HomeButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_HomeButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_HomeButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_HomeButton, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_HomeButton, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HomeButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelMenu1 = lv_label_create(ui_ScreenSettings);
lv_obj_set_width( ui_LabelMenu1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelMenu1, LV_SIZE_CONTENT);   /// 0
lv_obj_set_x( ui_LabelMenu1, -340 );
lv_obj_set_y( ui_LabelMenu1, -210 );
lv_obj_set_align( ui_LabelMenu1, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelMenu1,"Menu");
lv_obj_set_style_text_color(ui_LabelMenu1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelMenu1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_LabelMenu1, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelMenu1, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonSettingsSystemInfo = lv_btn_create(ui_ScreenSettings);
lv_obj_set_width( ui_ButtonSettingsSystemInfo, 190);
lv_obj_set_height( ui_ButtonSettingsSystemInfo, 50);
lv_obj_set_x( ui_ButtonSettingsSystemInfo, -295 );
lv_obj_set_y( ui_ButtonSettingsSystemInfo, -150 );
lv_obj_set_align( ui_ButtonSettingsSystemInfo, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonSettingsSystemInfo, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonSettingsSystemInfo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ButtonSettingsSystemInfo, 7, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelSettingsSystemInfo = lv_label_create(ui_ButtonSettingsSystemInfo);
lv_obj_set_width( ui_LabelSettingsSystemInfo, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelSettingsSystemInfo, LV_SIZE_CONTENT);   /// 0
lv_obj_set_align( ui_LabelSettingsSystemInfo, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelSettingsSystemInfo,"Information");
lv_obj_set_style_text_color(ui_LabelSettingsSystemInfo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelSettingsSystemInfo, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_LabelSettingsSystemInfo, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelSettingsSystemInfo, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonSettingsWiFi = lv_btn_create(ui_ScreenSettings);
lv_obj_set_width( ui_ButtonSettingsWiFi, 190);
lv_obj_set_height( ui_ButtonSettingsWiFi, 50);
lv_obj_set_x( ui_ButtonSettingsWiFi, -295 );
lv_obj_set_y( ui_ButtonSettingsWiFi, -89 );
lv_obj_set_align( ui_ButtonSettingsWiFi, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonSettingsWiFi, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonSettingsWiFi, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ButtonSettingsWiFi, 7, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelSettingsWiFi = lv_label_create(ui_ButtonSettingsWiFi);
lv_obj_set_width( ui_LabelSettingsWiFi, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelSettingsWiFi, LV_SIZE_CONTENT);   /// 0
lv_obj_set_align( ui_LabelSettingsWiFi, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelSettingsWiFi,"WI-FI Setting");
lv_obj_set_style_text_color(ui_LabelSettingsWiFi, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelSettingsWiFi, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_LabelSettingsWiFi, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelSettingsWiFi, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonSettingsWiFi1 = lv_btn_create(ui_ScreenSettings);
lv_obj_set_width( ui_ButtonSettingsWiFi1, 190);
lv_obj_set_height( ui_ButtonSettingsWiFi1, 50);
lv_obj_set_x( ui_ButtonSettingsWiFi1, -92 );
lv_obj_set_y( ui_ButtonSettingsWiFi1, -89 );
lv_obj_set_align( ui_ButtonSettingsWiFi1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonSettingsWiFi1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonSettingsWiFi1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ButtonSettingsWiFi1, 7, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelSettingsWiFi1 = lv_label_create(ui_ButtonSettingsWiFi1);
lv_obj_set_width( ui_LabelSettingsWiFi1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelSettingsWiFi1, LV_SIZE_CONTENT);   /// 0
lv_obj_set_align( ui_LabelSettingsWiFi1, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelSettingsWiFi1,"Reload Wi-Fi");
lv_obj_set_style_text_color(ui_LabelSettingsWiFi1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelSettingsWiFi1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_LabelSettingsWiFi1, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelSettingsWiFi1, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonSettingsTimeZone = lv_btn_create(ui_ScreenSettings);
lv_obj_set_width( ui_ButtonSettingsTimeZone, 190);
lv_obj_set_height( ui_ButtonSettingsTimeZone, 50);
lv_obj_set_x( ui_ButtonSettingsTimeZone, -295 );
lv_obj_set_y( ui_ButtonSettingsTimeZone, -28 );
lv_obj_set_align( ui_ButtonSettingsTimeZone, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonSettingsTimeZone, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonSettingsTimeZone, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ButtonSettingsTimeZone, 7, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelSettingsTimeZone = lv_label_create(ui_ButtonSettingsTimeZone);
lv_obj_set_width( ui_LabelSettingsTimeZone, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelSettingsTimeZone, LV_SIZE_CONTENT);   /// 0
lv_obj_set_align( ui_LabelSettingsTimeZone, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelSettingsTimeZone,"Time Zone");
lv_obj_set_style_text_color(ui_LabelSettingsTimeZone, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelSettingsTimeZone, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_LabelSettingsTimeZone, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelSettingsTimeZone, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonSettingsAppearance = lv_btn_create(ui_ScreenSettings);
lv_obj_set_width( ui_ButtonSettingsAppearance, 190);
lv_obj_set_height( ui_ButtonSettingsAppearance, 50);
lv_obj_set_x( ui_ButtonSettingsAppearance, -295 );
lv_obj_set_y( ui_ButtonSettingsAppearance, 32 );
lv_obj_set_align( ui_ButtonSettingsAppearance, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonSettingsAppearance, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonSettingsAppearance, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ButtonSettingsAppearance, 7, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelSettingsTimeZone1 = lv_label_create(ui_ButtonSettingsAppearance);
lv_obj_set_width( ui_LabelSettingsTimeZone1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelSettingsTimeZone1, LV_SIZE_CONTENT);   /// 0
lv_obj_set_align( ui_LabelSettingsTimeZone1, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelSettingsTimeZone1,"Appearance");
lv_obj_set_style_text_color(ui_LabelSettingsTimeZone1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelSettingsTimeZone1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_LabelSettingsTimeZone1, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelSettingsTimeZone1, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_InfoScreenContainer = lv_obj_create(ui_ScreenSettings);
lv_obj_remove_style_all(ui_InfoScreenContainer);
lv_obj_set_width( ui_InfoScreenContainer, 800);
lv_obj_set_height( ui_InfoScreenContainer, 480);
lv_obj_set_align( ui_InfoScreenContainer, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_InfoScreenContainer, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_InfoScreenContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_InfoScreenContainer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_InfoScreenContainer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonBack = lv_btn_create(ui_InfoScreenContainer);
lv_obj_set_width( ui_ButtonBack, 143);
lv_obj_set_height( ui_ButtonBack, 50);
lv_obj_set_x( ui_ButtonBack, -320 );
lv_obj_set_y( ui_ButtonBack, -210 );
lv_obj_set_align( ui_ButtonBack, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonBack, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ButtonBack, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ButtonBack, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonBack, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelBack = lv_label_create(ui_ButtonBack);
lv_obj_set_width( ui_LabelBack, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelBack, LV_SIZE_CONTENT);   /// 0
lv_obj_set_align( ui_LabelBack, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelBack,"< Settings");
lv_obj_set_style_text_color(ui_LabelBack, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelBack, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_LabelBack, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelBack, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelHardwareInformation = lv_label_create(ui_InfoScreenContainer);
lv_obj_set_width( ui_LabelHardwareInformation, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelHardwareInformation, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelHardwareInformation, -249 );
lv_obj_set_y( ui_LabelHardwareInformation, -165 );
lv_obj_set_align( ui_LabelHardwareInformation, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelHardwareInformation,"Hardware information:");
lv_obj_set_style_text_font(ui_LabelHardwareInformation, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_systemInfoLabel = lv_label_create(ui_InfoScreenContainer);
lv_obj_set_width( ui_systemInfoLabel, 462);
lv_obj_set_height( ui_systemInfoLabel, 368);
lv_obj_set_x( ui_systemInfoLabel, -154 );
lv_obj_set_y( ui_systemInfoLabel, 42 );
lv_obj_set_align( ui_systemInfoLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_systemInfoLabel,"");
lv_obj_set_style_text_font(ui_systemInfoLabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelSoftwareInformation = lv_label_create(ui_InfoScreenContainer);
lv_obj_set_width( ui_LabelSoftwareInformation, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelSoftwareInformation, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelSoftwareInformation, 226 );
lv_obj_set_y( ui_LabelSoftwareInformation, -165 );
lv_obj_set_align( ui_LabelSoftwareInformation, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelSoftwareInformation,"Software information:");
lv_obj_set_style_text_font(ui_LabelSoftwareInformation, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelSoftwareInformationData = lv_label_create(ui_InfoScreenContainer);
lv_obj_set_width( ui_LabelSoftwareInformationData, 281);
lv_obj_set_height( ui_LabelSoftwareInformationData, 368);
lv_obj_set_x( ui_LabelSoftwareInformationData, 235 );
lv_obj_set_y( ui_LabelSoftwareInformationData, 42 );
lv_obj_set_align( ui_LabelSoftwareInformationData, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelSoftwareInformationData,"fOS version:\n1.1\nDeveloper: \nFelix Leopold Meinhardt");
lv_obj_set_style_text_font(ui_LabelSoftwareInformationData, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_WifiScreenContainer = lv_obj_create(ui_ScreenSettings);
lv_obj_remove_style_all(ui_WifiScreenContainer);
lv_obj_set_width( ui_WifiScreenContainer, 800);
lv_obj_set_height( ui_WifiScreenContainer, 480);
lv_obj_set_align( ui_WifiScreenContainer, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_WifiScreenContainer, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_WifiScreenContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_WifiScreenContainer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_WifiScreenContainer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonBack1 = lv_btn_create(ui_WifiScreenContainer);
lv_obj_set_width( ui_ButtonBack1, 143);
lv_obj_set_height( ui_ButtonBack1, 50);
lv_obj_set_x( ui_ButtonBack1, -320 );
lv_obj_set_y( ui_ButtonBack1, -210 );
lv_obj_set_align( ui_ButtonBack1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonBack1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonBack1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ButtonBack1, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ButtonBack1, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonBack1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelBack1 = lv_label_create(ui_ButtonBack1);
lv_obj_set_width( ui_LabelBack1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelBack1, LV_SIZE_CONTENT);   /// 0
lv_obj_set_align( ui_LabelBack1, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelBack1,"< Settings");
lv_obj_set_style_text_color(ui_LabelBack1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelBack1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_LabelBack1, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelBack1, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonSaveWifi = lv_btn_create(ui_WifiScreenContainer);
lv_obj_set_width( ui_ButtonSaveWifi, 143);
lv_obj_set_height( ui_ButtonSaveWifi, 50);
lv_obj_set_x( ui_ButtonSaveWifi, 317 );
lv_obj_set_y( ui_ButtonSaveWifi, -210 );
lv_obj_set_align( ui_ButtonSaveWifi, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonSaveWifi, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonSaveWifi, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ButtonSaveWifi, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ButtonSaveWifi, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonSaveWifi, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelBack2 = lv_label_create(ui_ButtonSaveWifi);
lv_obj_set_width( ui_LabelBack2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelBack2, LV_SIZE_CONTENT);   /// 0
lv_obj_set_align( ui_LabelBack2, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelBack2,"Save Wifi");
lv_obj_set_style_text_color(ui_LabelBack2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelBack2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_LabelBack2, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelBack2, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelWifiSSID = lv_label_create(ui_WifiScreenContainer);
lv_obj_set_width( ui_LabelWifiSSID, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelWifiSSID, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelWifiSSID, -358 );
lv_obj_set_y( ui_LabelWifiSSID, -155 );
lv_obj_set_align( ui_LabelWifiSSID, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelWifiSSID,"SSID");
lv_obj_set_style_text_font(ui_LabelWifiSSID, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextAreaWifiSSID = lv_textarea_create(ui_WifiScreenContainer);
lv_obj_set_width( ui_TextAreaWifiSSID, 774);
lv_obj_set_height( ui_TextAreaWifiSSID, LV_SIZE_CONTENT);   /// 49
lv_obj_set_x( ui_TextAreaWifiSSID, 0 );
lv_obj_set_y( ui_TextAreaWifiSSID, -105 );
lv_obj_set_align( ui_TextAreaWifiSSID, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_TextAreaWifiSSID,"Here you can enter your Wi-Fi name . . .");
lv_textarea_set_one_line(ui_TextAreaWifiSSID,true);
lv_obj_set_style_text_font(ui_TextAreaWifiSSID, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(ui_TextAreaWifiSSID, &lv_font_montserrat_20, LV_PART_SELECTED| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(ui_TextAreaWifiSSID, &lv_font_montserrat_20, LV_PART_CURSOR| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(ui_TextAreaWifiSSID, &lv_font_montserrat_20, LV_PART_TEXTAREA_PLACEHOLDER| LV_STATE_DEFAULT);

ui_LabelWifiPassword = lv_label_create(ui_WifiScreenContainer);
lv_obj_set_width( ui_LabelWifiPassword, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelWifiPassword, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelWifiPassword, -326 );
lv_obj_set_y( ui_LabelWifiPassword, -54 );
lv_obj_set_align( ui_LabelWifiPassword, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelWifiPassword,"Password");
lv_obj_set_style_text_font(ui_LabelWifiPassword, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextAreaWifiPassword = lv_textarea_create(ui_WifiScreenContainer);
lv_obj_set_width( ui_TextAreaWifiPassword, 774);
lv_obj_set_height( ui_TextAreaWifiPassword, LV_SIZE_CONTENT);   /// 49
lv_obj_set_x( ui_TextAreaWifiPassword, 0 );
lv_obj_set_y( ui_TextAreaWifiPassword, -5 );
lv_obj_set_align( ui_TextAreaWifiPassword, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_TextAreaWifiPassword,"Here you can enter your Wi-Fi password . . .");
lv_textarea_set_one_line(ui_TextAreaWifiPassword,true);
lv_textarea_set_password_mode(ui_TextAreaWifiPassword, true);
lv_obj_set_style_text_font(ui_TextAreaWifiPassword, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(ui_TextAreaWifiPassword, &lv_font_montserrat_20, LV_PART_SELECTED| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(ui_TextAreaWifiPassword, &lv_font_montserrat_20, LV_PART_CURSOR| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(ui_TextAreaWifiPassword, &lv_font_montserrat_20, LV_PART_TEXTAREA_PLACEHOLDER| LV_STATE_DEFAULT);

ui_KeyboardWifi = lv_keyboard_create(ui_WifiScreenContainer);
lv_obj_set_width( ui_KeyboardWifi, 793);
lv_obj_set_height( ui_KeyboardWifi, 197);
lv_obj_set_x( ui_KeyboardWifi, 0 );
lv_obj_set_y( ui_KeyboardWifi, 135 );
lv_obj_set_align( ui_KeyboardWifi, LV_ALIGN_CENTER );

lv_obj_set_style_text_font(ui_KeyboardWifi, &lv_font_montserrat_20, LV_PART_ITEMS| LV_STATE_DEFAULT);

ui_TimeZoneContainer = lv_obj_create(ui_ScreenSettings);
lv_obj_remove_style_all(ui_TimeZoneContainer);
lv_obj_set_width( ui_TimeZoneContainer, 800);
lv_obj_set_height( ui_TimeZoneContainer, 480);
lv_obj_set_align( ui_TimeZoneContainer, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_TimeZoneContainer, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_TimeZoneContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_TimeZoneContainer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TimeZoneContainer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonBack2 = lv_btn_create(ui_TimeZoneContainer);
lv_obj_set_width( ui_ButtonBack2, 143);
lv_obj_set_height( ui_ButtonBack2, 50);
lv_obj_set_x( ui_ButtonBack2, -320 );
lv_obj_set_y( ui_ButtonBack2, -210 );
lv_obj_set_align( ui_ButtonBack2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonBack2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonBack2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ButtonBack2, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ButtonBack2, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonBack2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelBack3 = lv_label_create(ui_ButtonBack2);
lv_obj_set_width( ui_LabelBack3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelBack3, LV_SIZE_CONTENT);   /// 0
lv_obj_set_align( ui_LabelBack3, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelBack3,"< Settings");
lv_obj_set_style_text_color(ui_LabelBack3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelBack3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_LabelBack3, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelBack3, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonSaveTimeZone = lv_btn_create(ui_TimeZoneContainer);
lv_obj_set_width( ui_ButtonSaveTimeZone, 207);
lv_obj_set_height( ui_ButtonSaveTimeZone, 50);
lv_obj_set_x( ui_ButtonSaveTimeZone, 286 );
lv_obj_set_y( ui_ButtonSaveTimeZone, -210 );
lv_obj_set_align( ui_ButtonSaveTimeZone, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonSaveTimeZone, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonSaveTimeZone, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ButtonSaveTimeZone, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ButtonSaveTimeZone, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonSaveTimeZone, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelBack4 = lv_label_create(ui_ButtonSaveTimeZone);
lv_obj_set_width( ui_LabelBack4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelBack4, LV_SIZE_CONTENT);   /// 0
lv_obj_set_align( ui_LabelBack4, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelBack4,"Save Time Zone");
lv_obj_set_style_text_color(ui_LabelBack4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelBack4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_LabelBack4, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelBack4, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TimeZoneManager = lv_roller_create(ui_TimeZoneContainer);
lv_roller_set_options( ui_TimeZoneManager, "Oops, something went wrong.", LV_ROLLER_MODE_NORMAL );
lv_obj_set_width( ui_TimeZoneManager, 780);
lv_obj_set_height( ui_TimeZoneManager, 398);
lv_obj_set_x( ui_TimeZoneManager, 0 );
lv_obj_set_y( ui_TimeZoneManager, 26 );
lv_obj_set_align( ui_TimeZoneManager, LV_ALIGN_CENTER );
lv_obj_set_style_text_align(ui_TimeZoneManager, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TimeZoneManager, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AppearanceContainer = lv_obj_create(ui_ScreenSettings);
lv_obj_remove_style_all(ui_AppearanceContainer);
lv_obj_set_width( ui_AppearanceContainer, 800);
lv_obj_set_height( ui_AppearanceContainer, 480);
lv_obj_set_align( ui_AppearanceContainer, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_AppearanceContainer, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_AppearanceContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_AppearanceContainer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_AppearanceContainer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonBack3 = lv_btn_create(ui_AppearanceContainer);
lv_obj_set_width( ui_ButtonBack3, 143);
lv_obj_set_height( ui_ButtonBack3, 50);
lv_obj_set_x( ui_ButtonBack3, -320 );
lv_obj_set_y( ui_ButtonBack3, -210 );
lv_obj_set_align( ui_ButtonBack3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonBack3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonBack3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ButtonBack3, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ButtonBack3, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonBack3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelBack5 = lv_label_create(ui_ButtonBack3);
lv_obj_set_width( ui_LabelBack5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelBack5, LV_SIZE_CONTENT);   /// 0
lv_obj_set_align( ui_LabelBack5, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelBack5,"< Settings");
lv_obj_set_style_text_color(ui_LabelBack5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelBack5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_LabelBack5, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelBack5, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonSaveAppearance = lv_btn_create(ui_AppearanceContainer);
lv_obj_set_width( ui_ButtonSaveAppearance, 207);
lv_obj_set_height( ui_ButtonSaveAppearance, 50);
lv_obj_set_x( ui_ButtonSaveAppearance, 286 );
lv_obj_set_y( ui_ButtonSaveAppearance, -210 );
lv_obj_set_align( ui_ButtonSaveAppearance, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonSaveAppearance, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonSaveAppearance, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ButtonSaveAppearance, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ButtonSaveAppearance, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonSaveAppearance, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelBack6 = lv_label_create(ui_ButtonSaveAppearance);
lv_obj_set_width( ui_LabelBack6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelBack6, LV_SIZE_CONTENT);   /// 0
lv_obj_set_align( ui_LabelBack6, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelBack6,"Save changes");
lv_obj_set_style_text_color(ui_LabelBack6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelBack6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_LabelBack6, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelBack6, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ColorwheelSettings = lv_colorwheel_create(ui_AppearanceContainer,true);
lv_obj_set_width( ui_ColorwheelSettings, 200);
lv_obj_set_height( ui_ColorwheelSettings, 200);
lv_obj_set_x( ui_ColorwheelSettings, -208 );
lv_obj_set_y( ui_ColorwheelSettings, 25 );
lv_obj_set_align( ui_ColorwheelSettings, LV_ALIGN_CENTER );

ui_LabelColorwheel = lv_label_create(ui_AppearanceContainer);
lv_obj_set_width( ui_LabelColorwheel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelColorwheel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelColorwheel, -208 );
lv_obj_set_y( ui_LabelColorwheel, -114 );
lv_obj_set_align( ui_LabelColorwheel, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelColorwheel,"Color");
lv_obj_set_style_text_font(ui_LabelColorwheel, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SliderBrightness = lv_slider_create(ui_AppearanceContainer);
lv_slider_set_value( ui_SliderBrightness, 100, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_SliderBrightness)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_SliderBrightness, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_SliderBrightness, 344);
lv_obj_set_height( ui_SliderBrightness, 15);
lv_obj_set_x( ui_SliderBrightness, 146 );
lv_obj_set_y( ui_SliderBrightness, 25 );
lv_obj_set_align( ui_SliderBrightness, LV_ALIGN_CENTER );

ui_LabelBrightness = lv_label_create(ui_AppearanceContainer);
lv_obj_set_width( ui_LabelBrightness, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelBrightness, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelBrightness, 146 );
lv_obj_set_y( ui_LabelBrightness, -114 );
lv_obj_set_align( ui_LabelBrightness, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelBrightness,"Brightness");
lv_obj_set_style_text_font(ui_LabelBrightness, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_HomeButton, ui_event_HomeButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonSettingsSystemInfo, ui_event_ButtonSettingsSystemInfo, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonSettingsWiFi, ui_event_ButtonSettingsWiFi, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonSettingsWiFi1, ui_event_ButtonSettingsWiFi1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonSettingsTimeZone, ui_event_ButtonSettingsTimeZone, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonSettingsAppearance, ui_event_ButtonSettingsAppearance, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonBack, ui_event_ButtonBack, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonBack1, ui_event_ButtonBack1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonSaveWifi, ui_event_ButtonSaveWifi, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TextAreaWifiSSID, ui_event_TextAreaWifiSSID, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TextAreaWifiPassword, ui_event_TextAreaWifiPassword, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonBack2, ui_event_ButtonBack2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonSaveTimeZone, ui_event_ButtonSaveTimeZone, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonBack3, ui_event_ButtonBack3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonSaveAppearance, ui_event_ButtonSaveAppearance, LV_EVENT_ALL, NULL);
uic_ScreenSettings = ui_ScreenSettings;
uic_ButtonSettingsSystemInfo = ui_ButtonSettingsSystemInfo;
uic_ButtonSettingsTimeZone = ui_ButtonSettingsTimeZone;
uic_ButtonSettingsAppearance = ui_ButtonSettingsAppearance;
uic_InfoScreenContainer = ui_InfoScreenContainer;
uic_ButtonBack = ui_ButtonBack;
uic_systemInfoLabel = ui_systemInfoLabel;
uic_WifiScreenContainer = ui_WifiScreenContainer;
uic_ButtonSaveWifi = ui_ButtonSaveWifi;
uic_TextAreaWifiSSID = ui_TextAreaWifiSSID;
uic_TextAreaWifiPassword = ui_TextAreaWifiPassword;
uic_KeyboardWifi = ui_KeyboardWifi;
uic_TimeZoneContainer = ui_TimeZoneContainer;
uic_ButtonSaveTimeZone = ui_ButtonSaveTimeZone;
uic_TimeZoneManager = ui_TimeZoneManager;
uic_AppearanceContainer = ui_AppearanceContainer;
uic_ButtonSaveAppearance = ui_ButtonSaveAppearance;
uic_ColorwheelSettings = ui_ColorwheelSettings;
uic_SliderBrightness = ui_SliderBrightness;

}

void ui_ScreenSettings_screen_destroy(void)
{
   if (ui_ScreenSettings) lv_obj_del(ui_ScreenSettings);

// NULL screen variables
uic_ScreenSettings= NULL;
ui_ScreenSettings= NULL;
ui_HomeButton= NULL;
ui_LabelMenu1= NULL;
uic_ButtonSettingsSystemInfo= NULL;
ui_ButtonSettingsSystemInfo= NULL;
ui_LabelSettingsSystemInfo= NULL;
ui_ButtonSettingsWiFi= NULL;
ui_LabelSettingsWiFi= NULL;
ui_ButtonSettingsWiFi1= NULL;
ui_LabelSettingsWiFi1= NULL;
uic_ButtonSettingsTimeZone= NULL;
ui_ButtonSettingsTimeZone= NULL;
ui_LabelSettingsTimeZone= NULL;
uic_ButtonSettingsAppearance= NULL;
ui_ButtonSettingsAppearance= NULL;
ui_LabelSettingsTimeZone1= NULL;
uic_InfoScreenContainer= NULL;
ui_InfoScreenContainer= NULL;
uic_ButtonBack= NULL;
ui_ButtonBack= NULL;
ui_LabelBack= NULL;
ui_LabelHardwareInformation= NULL;
uic_systemInfoLabel= NULL;
ui_systemInfoLabel= NULL;
ui_LabelSoftwareInformation= NULL;
ui_LabelSoftwareInformationData= NULL;
uic_WifiScreenContainer= NULL;
ui_WifiScreenContainer= NULL;
ui_ButtonBack1= NULL;
ui_LabelBack1= NULL;
uic_ButtonSaveWifi= NULL;
ui_ButtonSaveWifi= NULL;
ui_LabelBack2= NULL;
ui_LabelWifiSSID= NULL;
uic_TextAreaWifiSSID= NULL;
ui_TextAreaWifiSSID= NULL;
ui_LabelWifiPassword= NULL;
uic_TextAreaWifiPassword= NULL;
ui_TextAreaWifiPassword= NULL;
uic_KeyboardWifi= NULL;
ui_KeyboardWifi= NULL;
uic_TimeZoneContainer= NULL;
ui_TimeZoneContainer= NULL;
ui_ButtonBack2= NULL;
ui_LabelBack3= NULL;
uic_ButtonSaveTimeZone= NULL;
ui_ButtonSaveTimeZone= NULL;
ui_LabelBack4= NULL;
uic_TimeZoneManager= NULL;
ui_TimeZoneManager= NULL;
uic_AppearanceContainer= NULL;
ui_AppearanceContainer= NULL;
ui_ButtonBack3= NULL;
ui_LabelBack5= NULL;
uic_ButtonSaveAppearance= NULL;
ui_ButtonSaveAppearance= NULL;
ui_LabelBack6= NULL;
uic_ColorwheelSettings= NULL;
ui_ColorwheelSettings= NULL;
ui_LabelColorwheel= NULL;
uic_SliderBrightness= NULL;
ui_SliderBrightness= NULL;
ui_LabelBrightness= NULL;

}
