// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: lvgl_test

#include "ui.h"

void AppStoreDownloadApp(lv_event_t * e);
void AppStoreDeleteApp(lv_event_t * e);
void AssignAppsConfirm(lv_event_t * e);

lv_obj_t *uic_SelectAppSlotRoller;
lv_obj_t *uic_AppForAssigningRoller;
lv_obj_t *uic_AppDownloadRoller;
lv_obj_t *ui_AppStore = NULL;lv_obj_t *ui_TabView4 = NULL;lv_obj_t *ui_TabPageDownload = NULL;lv_obj_t *ui_AppDownloadRoller = NULL;lv_obj_t *ui_AppStoreDownload = NULL;lv_obj_t *ui_WeatherSearchConfirmLabel3 = NULL;lv_obj_t *ui_AppStoreDelete = NULL;lv_obj_t *ui_WeatherSearchConfirmLabel1 = NULL;lv_obj_t *ui_TabPageAssignApps = NULL;lv_obj_t *ui_AppForAssigningRoller = NULL;lv_obj_t *ui_SelectAppSlotRoller = NULL;lv_obj_t *ui_AssignAppsConfirm = NULL;lv_obj_t *ui_WeatherSearchConfirmLabel2 = NULL;
// event funtions
void ui_event_AppStoreDownload( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      AppStoreDownloadApp( e );
}
}

void ui_event_AppStoreDelete( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      AppStoreDeleteApp( e );
}
}

void ui_event_AssignAppsConfirm( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      AssignAppsConfirm( e );
}
}

// build funtions

void ui_AppStore_screen_init(void)
{
ui_AppStore = lv_obj_create(NULL);
lv_obj_clear_flag( ui_AppStore, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TabView4 = lv_tabview_create(ui_AppStore, LV_DIR_TOP, 50);
lv_obj_set_width( ui_TabView4, 800);
lv_obj_set_height( ui_TabView4, 480);
lv_obj_set_align( ui_TabView4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_TabView4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_set_style_text_font(lv_tabview_get_tab_btns(ui_TabView4), &lv_font_montserrat_24,  LV_PART_ITEMS| LV_STATE_DEFAULT);

ui_TabPageDownload = lv_tabview_add_tab(ui_TabView4, "Download");

ui_AppDownloadRoller = lv_roller_create(ui_TabPageDownload);
lv_roller_set_options( ui_AppDownloadRoller, "Weather App | installed V1.0.0 - compatible V1.1.0 | 19KB\nCalculator | V1.0.0 | 10KB", LV_ROLLER_MODE_NORMAL );
lv_obj_set_width( ui_AppDownloadRoller, 760);
lv_obj_set_height( ui_AppDownloadRoller, 338);
lv_obj_set_x( ui_AppDownloadRoller, 0 );
lv_obj_set_y( ui_AppDownloadRoller, 26 );
lv_obj_set_align( ui_AppDownloadRoller, LV_ALIGN_CENTER );
lv_obj_set_style_text_font(ui_AppDownloadRoller, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(ui_AppDownloadRoller, &lv_font_montserrat_20, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_AppStoreDownload = lv_btn_create(ui_TabPageDownload);
lv_obj_set_width( ui_AppStoreDownload, 152);
lv_obj_set_height( ui_AppStoreDownload, 50);
lv_obj_set_x( ui_AppStoreDownload, 304 );
lv_obj_set_y( ui_AppStoreDownload, -180 );
lv_obj_set_align( ui_AppStoreDownload, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_AppStoreDownload, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_AppStoreDownload, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_AppStoreDownload, 7, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_WeatherSearchConfirmLabel3 = lv_label_create(ui_AppStoreDownload);
lv_obj_set_width( ui_WeatherSearchConfirmLabel3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_WeatherSearchConfirmLabel3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_WeatherSearchConfirmLabel3, LV_ALIGN_CENTER );
lv_label_set_text(ui_WeatherSearchConfirmLabel3,"Download");
lv_obj_set_style_text_color(ui_WeatherSearchConfirmLabel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_WeatherSearchConfirmLabel3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_WeatherSearchConfirmLabel3, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AppStoreDelete = lv_btn_create(ui_TabPageDownload);
lv_obj_set_width( ui_AppStoreDelete, 152);
lv_obj_set_height( ui_AppStoreDelete, 50);
lv_obj_set_x( ui_AppStoreDelete, 143 );
lv_obj_set_y( ui_AppStoreDelete, -180 );
lv_obj_set_align( ui_AppStoreDelete, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_AppStoreDelete, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_AppStoreDelete, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_AppStoreDelete, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_AppStoreDelete, lv_color_hex(0xE8210B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_AppStoreDelete, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_WeatherSearchConfirmLabel1 = lv_label_create(ui_AppStoreDelete);
lv_obj_set_width( ui_WeatherSearchConfirmLabel1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_WeatherSearchConfirmLabel1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_WeatherSearchConfirmLabel1, LV_ALIGN_CENTER );
lv_label_set_text(ui_WeatherSearchConfirmLabel1,"Delete");
lv_obj_set_style_text_color(ui_WeatherSearchConfirmLabel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_WeatherSearchConfirmLabel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_WeatherSearchConfirmLabel1, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TabPageAssignApps = lv_tabview_add_tab(ui_TabView4, "Assign Apps");

ui_AppForAssigningRoller = lv_dropdown_create(ui_TabPageAssignApps);
lv_dropdown_set_options( ui_AppForAssigningRoller, "Select an app\nNothing" );
lv_obj_set_width( ui_AppForAssigningRoller, 760);
lv_obj_set_height( ui_AppForAssigningRoller, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_AppForAssigningRoller, 0 );
lv_obj_set_y( ui_AppForAssigningRoller, -160 );
lv_obj_set_align( ui_AppForAssigningRoller, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_AppForAssigningRoller, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_text_font(ui_AppForAssigningRoller, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(ui_AppForAssigningRoller, &lv_font_montserrat_20, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(lv_dropdown_get_list(ui_AppForAssigningRoller), &lv_font_montserrat_20,  LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(lv_dropdown_get_list(ui_AppForAssigningRoller), &lv_font_montserrat_20,  LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_SelectAppSlotRoller = lv_dropdown_create(ui_TabPageAssignApps);
lv_dropdown_set_options( ui_SelectAppSlotRoller, "Select a slot" );
lv_obj_set_width( ui_SelectAppSlotRoller, 760);
lv_obj_set_height( ui_SelectAppSlotRoller, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SelectAppSlotRoller, 0 );
lv_obj_set_y( ui_SelectAppSlotRoller, -96 );
lv_obj_set_align( ui_SelectAppSlotRoller, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SelectAppSlotRoller, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_text_font(ui_SelectAppSlotRoller, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(ui_SelectAppSlotRoller, &lv_font_montserrat_20, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(lv_dropdown_get_list(ui_SelectAppSlotRoller), &lv_font_montserrat_20,  LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(lv_dropdown_get_list(ui_SelectAppSlotRoller), &lv_font_montserrat_20,  LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_AssignAppsConfirm = lv_btn_create(ui_TabPageAssignApps);
lv_obj_set_width( ui_AssignAppsConfirm, 119);
lv_obj_set_height( ui_AssignAppsConfirm, 50);
lv_obj_set_x( ui_AssignAppsConfirm, -320 );
lv_obj_set_y( ui_AssignAppsConfirm, -33 );
lv_obj_set_align( ui_AssignAppsConfirm, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_AssignAppsConfirm, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_AssignAppsConfirm, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_AssignAppsConfirm, 7, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_WeatherSearchConfirmLabel2 = lv_label_create(ui_AssignAppsConfirm);
lv_obj_set_width( ui_WeatherSearchConfirmLabel2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_WeatherSearchConfirmLabel2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_WeatherSearchConfirmLabel2, LV_ALIGN_CENTER );
lv_label_set_text(ui_WeatherSearchConfirmLabel2,"Confirm");
lv_obj_set_style_text_color(ui_WeatherSearchConfirmLabel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_WeatherSearchConfirmLabel2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_WeatherSearchConfirmLabel2, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_AppStoreDownload, ui_event_AppStoreDownload, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_AppStoreDelete, ui_event_AppStoreDelete, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_AssignAppsConfirm, ui_event_AssignAppsConfirm, LV_EVENT_ALL, NULL);
uic_AppDownloadRoller = ui_AppDownloadRoller;
uic_AppForAssigningRoller = ui_AppForAssigningRoller;
uic_SelectAppSlotRoller = ui_SelectAppSlotRoller;

}

void ui_AppStore_screen_destroy(void)
{
   if (ui_AppStore) lv_obj_del(ui_AppStore);

// NULL screen variables
ui_AppStore= NULL;
ui_TabView4= NULL;
ui_TabPageDownload= NULL;
uic_AppDownloadRoller= NULL;
ui_AppDownloadRoller= NULL;
ui_AppStoreDownload= NULL;
ui_WeatherSearchConfirmLabel3= NULL;
ui_AppStoreDelete= NULL;
ui_WeatherSearchConfirmLabel1= NULL;
ui_TabPageAssignApps= NULL;
uic_AppForAssigningRoller= NULL;
ui_AppForAssigningRoller= NULL;
uic_SelectAppSlotRoller= NULL;
ui_SelectAppSlotRoller= NULL;
ui_AssignAppsConfirm= NULL;
ui_WeatherSearchConfirmLabel2= NULL;

}
