// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: lvgl_test

#ifndef UI_APPSTORE_H
#define UI_APPSTORE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_AppStore
extern void ui_AppStore_screen_init(void);
extern void ui_AppStore_screen_destroy(void);
extern lv_obj_t *ui_AppStore;
extern lv_obj_t *ui_TabView4;
extern lv_obj_t *ui_TabPageDownload;
extern lv_obj_t *ui_AppDownloadRoller;
extern void ui_event_AppStoreDownload( lv_event_t * e);
extern lv_obj_t *ui_AppStoreDownload;
extern lv_obj_t *ui_WeatherSearchConfirmLabel3;
extern void ui_event_AppStoreDelete( lv_event_t * e);
extern lv_obj_t *ui_AppStoreDelete;
extern lv_obj_t *ui_WeatherSearchConfirmLabel1;
extern lv_obj_t *ui_TabPageAssignApps;
extern lv_obj_t *ui_AppForAssigningRoller;
extern lv_obj_t *ui_SelectAppSlotRoller;
extern void ui_event_AssignAppsConfirm( lv_event_t * e);
extern lv_obj_t *ui_AssignAppsConfirm;
extern lv_obj_t *ui_WeatherSearchConfirmLabel2;
// CUSTOM VARIABLES
extern lv_obj_t *uic_AppDownloadRoller;
extern lv_obj_t *uic_AppForAssigningRoller;
extern lv_obj_t *uic_SelectAppSlotRoller;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

