// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: fOS_1

#include "ui.h"

void updateSDUI(lv_event_t * e)
{
	// Your code here
}

void fillFileRoller_TextViewer(lv_event_t * e)
{
	// Your code here
}

void updateSystemInfo(lv_event_t * e)
{
	// Your code here
}

void DeleteFileSelected(lv_event_t * e)
{
	// Your code here
}

void save_text_file(lv_event_t * e)
{
	// Your code here
}

void load_selected_file(lv_event_t * e)
{
	// Your code here
}

void keypad_event_handler(lv_event_t * e)
{
	// Your code here
}

void operator_event_handler(lv_event_t * e)
{
	// Your code here
}
