// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: fOS_1

#include "ui.h"

lv_obj_t *uic_NoFunktion;
lv_obj_t *ui_NoFunktion = NULL;
// event funtions

// build funtions

void ui_NoFunktion_screen_init(void)
{
ui_NoFunktion = lv_obj_create(NULL);
lv_obj_clear_flag( ui_NoFunktion, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

uic_NoFunktion = ui_NoFunktion;

}

void ui_NoFunktion_screen_destroy(void)
{
   if (ui_NoFunktion) lv_obj_del(ui_NoFunktion);

// NULL screen variables
uic_NoFunktion= NULL;
ui_NoFunktion= NULL;

}
