// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: fOS_1

#ifndef UI_NOFUNKTION_H
#define UI_NOFUNKTION_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_NoFunktion
extern void ui_NoFunktion_screen_init(void);
extern void ui_NoFunktion_screen_destroy(void);
extern lv_obj_t *ui_NoFunktion;
// CUSTOM VARIABLES
extern lv_obj_t *uic_NoFunktion;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

