// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: fOS_1

#include "ui.h"

lv_obj_t *uic_systemInfoLabel;
lv_obj_t *uic_ButtonBack;
lv_obj_t *uic_ScreenSettingsSystemInfo;
lv_obj_t *ui_ScreenSettingsSystemInfo = NULL;lv_obj_t *ui_ButtonBack = NULL;lv_obj_t *ui_LabelBack = NULL;lv_obj_t *ui_systemInfoLabel = NULL;lv_obj_t *ui_LabelHardwareInformation = NULL;lv_obj_t *ui_LabelSoftwareInformation = NULL;lv_obj_t *ui_LabelSoftwareInformationData = NULL;
// event funtions
void ui_event_ButtonBack( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenSettings, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_ScreenSettings_screen_init);
}
}

// build funtions

void ui_ScreenSettingsSystemInfo_screen_init(void)
{
ui_ScreenSettingsSystemInfo = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenSettingsSystemInfo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ButtonBack = lv_btn_create(ui_ScreenSettingsSystemInfo);
lv_obj_set_width( ui_ButtonBack, 143);
lv_obj_set_height( ui_ButtonBack, 50);
lv_obj_set_x( ui_ButtonBack, -320 );
lv_obj_set_y( ui_ButtonBack, -210 );
lv_obj_set_align( ui_ButtonBack, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonBack, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ButtonBack, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ButtonBack, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonBack, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelBack = lv_label_create(ui_ScreenSettingsSystemInfo);
lv_obj_set_width( ui_LabelBack, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelBack, LV_SIZE_CONTENT);   /// 0
lv_obj_set_x( ui_LabelBack, -320 );
lv_obj_set_y( ui_LabelBack, -210 );
lv_obj_set_align( ui_LabelBack, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelBack,"< Settings");
lv_obj_set_style_text_color(ui_LabelBack, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelBack, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_LabelBack, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelBack, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_systemInfoLabel = lv_label_create(ui_ScreenSettingsSystemInfo);
lv_obj_set_width( ui_systemInfoLabel, 462);
lv_obj_set_height( ui_systemInfoLabel, 368);
lv_obj_set_x( ui_systemInfoLabel, -154 );
lv_obj_set_y( ui_systemInfoLabel, 42 );
lv_obj_set_align( ui_systemInfoLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_systemInfoLabel,"");
lv_obj_set_style_text_font(ui_systemInfoLabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelHardwareInformation = lv_label_create(ui_ScreenSettingsSystemInfo);
lv_obj_set_width( ui_LabelHardwareInformation, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelHardwareInformation, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelHardwareInformation, -249 );
lv_obj_set_y( ui_LabelHardwareInformation, -165 );
lv_obj_set_align( ui_LabelHardwareInformation, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelHardwareInformation,"Hardware information:");
lv_obj_set_style_text_font(ui_LabelHardwareInformation, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelSoftwareInformation = lv_label_create(ui_ScreenSettingsSystemInfo);
lv_obj_set_width( ui_LabelSoftwareInformation, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelSoftwareInformation, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelSoftwareInformation, 226 );
lv_obj_set_y( ui_LabelSoftwareInformation, -165 );
lv_obj_set_align( ui_LabelSoftwareInformation, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelSoftwareInformation,"Software information:");
lv_obj_set_style_text_font(ui_LabelSoftwareInformation, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelSoftwareInformationData = lv_label_create(ui_ScreenSettingsSystemInfo);
lv_obj_set_width( ui_LabelSoftwareInformationData, 281);
lv_obj_set_height( ui_LabelSoftwareInformationData, 368);
lv_obj_set_x( ui_LabelSoftwareInformationData, 235 );
lv_obj_set_y( ui_LabelSoftwareInformationData, 42 );
lv_obj_set_align( ui_LabelSoftwareInformationData, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelSoftwareInformationData,"fOS version:\n1.0\nDeveloper: \nFelix Leopold Meinhardt");
lv_obj_set_style_text_font(ui_LabelSoftwareInformationData, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_ButtonBack, ui_event_ButtonBack, LV_EVENT_ALL, NULL);
uic_ScreenSettingsSystemInfo = ui_ScreenSettingsSystemInfo;
uic_ButtonBack = ui_ButtonBack;
uic_systemInfoLabel = ui_systemInfoLabel;

}

void ui_ScreenSettingsSystemInfo_screen_destroy(void)
{
   if (ui_ScreenSettingsSystemInfo) lv_obj_del(ui_ScreenSettingsSystemInfo);

// NULL screen variables
uic_ScreenSettingsSystemInfo= NULL;
ui_ScreenSettingsSystemInfo= NULL;
uic_ButtonBack= NULL;
ui_ButtonBack= NULL;
ui_LabelBack= NULL;
uic_systemInfoLabel= NULL;
ui_systemInfoLabel= NULL;
ui_LabelHardwareInformation= NULL;
ui_LabelSoftwareInformation= NULL;
ui_LabelSoftwareInformationData= NULL;

}
