// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: fOS_1

#ifndef UI_SCREENHOME_H
#define UI_SCREENHOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenHome
extern void ui_ScreenHome_screen_init(void);
extern void ui_ScreenHome_screen_destroy(void);
extern lv_obj_t *ui_ScreenHome;
extern void ui_event_AppSettings( lv_event_t * e);
extern lv_obj_t *ui_AppSettings;
extern void ui_event_AppFileManager( lv_event_t * e);
extern lv_obj_t *ui_AppFileManager;
extern void ui_event_AppLauncher( lv_event_t * e);
extern lv_obj_t *ui_AppLauncher;
extern void ui_event_AppText( lv_event_t * e);
extern lv_obj_t *ui_AppText;
extern void ui_event_AppRadio( lv_event_t * e);
extern lv_obj_t *ui_AppRadio;
extern void ui_event_AppWeather( lv_event_t * e);
extern lv_obj_t *ui_AppWeather;
extern void ui_event_AppClock( lv_event_t * e);
extern lv_obj_t *ui_AppClock;
extern void ui_event_AppCalculator( lv_event_t * e);
extern lv_obj_t *ui_AppCalculator;
extern lv_obj_t *ui_WiFiImage;
extern lv_obj_t *ui_labelClockTopLine;
extern lv_obj_t *ui_BootOverlay;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_BootProgressBar;
extern lv_obj_t *ui_BootProgressLabel;
// CUSTOM VARIABLES
extern lv_obj_t *uic_ScreenHome;
extern lv_obj_t *uic_AppSettings;
extern lv_obj_t *uic_AppFileManager;
extern lv_obj_t *uic_AppLauncher;
extern lv_obj_t *uic_AppText;
extern lv_obj_t *uic_AppRadio;
extern lv_obj_t *uic_AppWeather;
extern lv_obj_t *uic_AppClock;
extern lv_obj_t *uic_AppCalculator;
extern lv_obj_t *uic_WiFiImage;
extern lv_obj_t *uic_labelClockTopLine;
extern lv_obj_t *uic_BootOverlay;
extern lv_obj_t *uic_BootProgressBar;
extern lv_obj_t *uic_BootProgressLabel;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

