// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: fOS_1

#include "ui.h"

lv_obj_t *uic_LabelStopwatchDisplay;
lv_obj_t *uic_ButtonStopwatchReset;
lv_obj_t *uic_LabelStopwatchPlay;
lv_obj_t *uic_ButtonStopwatchPlay;
lv_obj_t *uic_Calendar;
lv_obj_t *uic_RealTimeClock;
lv_obj_t *uic_TabView1;
lv_obj_t *ui_ScreenClock = NULL;lv_obj_t *ui_TabView1 = NULL;lv_obj_t *ui_Current_Time = NULL;lv_obj_t *ui_RealTimeClock = NULL;lv_obj_t *ui_Calendar = NULL;lv_obj_t *ui_Stopwatch = NULL;lv_obj_t *ui_ButtonStopwatchPlay = NULL;lv_obj_t *ui_LabelStopwatchPlay = NULL;lv_obj_t *ui_ButtonStopwatchReset = NULL;lv_obj_t *ui_LabelStopwatchReset = NULL;lv_obj_t *ui_LabelStopwatchDisplay = NULL;lv_obj_t *ui_HomeButton6 = NULL;lv_obj_t *ui_LabelMenu7 = NULL;
// event funtions
void ui_event_ButtonStopwatchPlay( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      StopwatchPlay( e );
}
}

void ui_event_ButtonStopwatchReset( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      StopwatchReset( e );
}
}

void ui_event_HomeButton6( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenHome, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenHome_screen_init);
}
}

// build funtions

void ui_ScreenClock_screen_init(void)
{
ui_ScreenClock = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenClock, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TabView1 = lv_tabview_create(ui_ScreenClock, LV_DIR_TOP, 65);
lv_obj_set_width( ui_TabView1, 800);
lv_obj_set_height( ui_TabView1, 480);
lv_obj_set_align( ui_TabView1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_TabView1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_text_font(ui_TabView1, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(lv_tabview_get_tab_btns(ui_TabView1), &lv_font_montserrat_20,  LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(lv_tabview_get_tab_btns(ui_TabView1), &lv_font_montserrat_20,  LV_PART_ITEMS| LV_STATE_DEFAULT);

ui_Current_Time = lv_tabview_add_tab(ui_TabView1, "Current Time");

ui_RealTimeClock = lv_label_create(ui_Current_Time);
lv_obj_set_width( ui_RealTimeClock, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RealTimeClock, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RealTimeClock, 0 );
lv_obj_set_y( ui_RealTimeClock, -130 );
lv_obj_set_align( ui_RealTimeClock, LV_ALIGN_CENTER );
lv_label_set_text(ui_RealTimeClock,"00:00:00");
lv_obj_set_style_text_font(ui_RealTimeClock, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Calendar = lv_calendar_create(ui_Current_Time);
lv_calendar_set_today_date(ui_Calendar,2026,1,25);
lv_calendar_set_showed_date(ui_Calendar,2026,1);
lv_obj_t *ui_Calendar_header = lv_calendar_header_arrow_create(ui_Calendar);
lv_obj_set_width( ui_Calendar, 757);
lv_obj_set_height( ui_Calendar, 267);
lv_obj_set_x( ui_Calendar, 0 );
lv_obj_set_y( ui_Calendar, 48 );
lv_obj_set_align( ui_Calendar, LV_ALIGN_CENTER );

ui_Stopwatch = lv_tabview_add_tab(ui_TabView1, "Stopwatch");

ui_ButtonStopwatchPlay = lv_btn_create(ui_Stopwatch);
lv_obj_set_width( ui_ButtonStopwatchPlay, 191);
lv_obj_set_height( ui_ButtonStopwatchPlay, 50);
lv_obj_set_x( ui_ButtonStopwatchPlay, 102 );
lv_obj_set_y( ui_ButtonStopwatchPlay, 0 );
lv_obj_set_align( ui_ButtonStopwatchPlay, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonStopwatchPlay, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonStopwatchPlay, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ButtonStopwatchPlay, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ButtonStopwatchPlay, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonStopwatchPlay, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelStopwatchPlay = lv_label_create(ui_ButtonStopwatchPlay);
lv_obj_set_width( ui_LabelStopwatchPlay, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelStopwatchPlay, LV_SIZE_CONTENT);   /// 0
lv_obj_set_align( ui_LabelStopwatchPlay, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelStopwatchPlay,"||");
lv_obj_set_style_text_color(ui_LabelStopwatchPlay, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelStopwatchPlay, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_LabelStopwatchPlay, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelStopwatchPlay, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonStopwatchReset = lv_btn_create(ui_Stopwatch);
lv_obj_set_width( ui_ButtonStopwatchReset, 191);
lv_obj_set_height( ui_ButtonStopwatchReset, 50);
lv_obj_set_x( ui_ButtonStopwatchReset, -102 );
lv_obj_set_y( ui_ButtonStopwatchReset, 0 );
lv_obj_set_align( ui_ButtonStopwatchReset, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonStopwatchReset, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonStopwatchReset, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ButtonStopwatchReset, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ButtonStopwatchReset, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonStopwatchReset, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelStopwatchReset = lv_label_create(ui_ButtonStopwatchReset);
lv_obj_set_width( ui_LabelStopwatchReset, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelStopwatchReset, LV_SIZE_CONTENT);   /// 0
lv_obj_set_align( ui_LabelStopwatchReset, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelStopwatchReset,"Reset");
lv_obj_set_style_text_color(ui_LabelStopwatchReset, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelStopwatchReset, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_LabelStopwatchReset, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelStopwatchReset, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelStopwatchDisplay = lv_label_create(ui_Stopwatch);
lv_obj_set_width( ui_LabelStopwatchDisplay, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelStopwatchDisplay, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelStopwatchDisplay, 0 );
lv_obj_set_y( ui_LabelStopwatchDisplay, -130 );
lv_obj_set_align( ui_LabelStopwatchDisplay, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelStopwatchDisplay,"00:00:00");
lv_obj_set_style_text_font(ui_LabelStopwatchDisplay, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HomeButton6 = lv_btn_create(ui_ScreenClock);
lv_obj_set_width( ui_HomeButton6, 100);
lv_obj_set_height( ui_HomeButton6, 50);
lv_obj_set_x( ui_HomeButton6, -340 );
lv_obj_set_y( ui_HomeButton6, -210 );
lv_obj_set_align( ui_HomeButton6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_HomeButton6, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_HomeButton6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_HomeButton6, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_HomeButton6, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HomeButton6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelMenu7 = lv_label_create(ui_HomeButton6);
lv_obj_set_width( ui_LabelMenu7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelMenu7, LV_SIZE_CONTENT);   /// 0
lv_obj_set_align( ui_LabelMenu7, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelMenu7,"Menu");
lv_obj_set_style_text_color(ui_LabelMenu7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelMenu7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_LabelMenu7, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelMenu7, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_ButtonStopwatchPlay, ui_event_ButtonStopwatchPlay, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonStopwatchReset, ui_event_ButtonStopwatchReset, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_HomeButton6, ui_event_HomeButton6, LV_EVENT_ALL, NULL);
uic_TabView1 = ui_TabView1;
uic_RealTimeClock = ui_RealTimeClock;
uic_Calendar = ui_Calendar;
uic_ButtonStopwatchPlay = ui_ButtonStopwatchPlay;
uic_LabelStopwatchPlay = ui_LabelStopwatchPlay;
uic_ButtonStopwatchReset = ui_ButtonStopwatchReset;
uic_LabelStopwatchDisplay = ui_LabelStopwatchDisplay;

}

void ui_ScreenClock_screen_destroy(void)
{
   if (ui_ScreenClock) lv_obj_del(ui_ScreenClock);

// NULL screen variables
ui_ScreenClock= NULL;
uic_TabView1= NULL;
ui_TabView1= NULL;
ui_Current_Time= NULL;
uic_RealTimeClock= NULL;
ui_RealTimeClock= NULL;
uic_Calendar= NULL;
ui_Calendar= NULL;
ui_Stopwatch= NULL;
uic_ButtonStopwatchPlay= NULL;
ui_ButtonStopwatchPlay= NULL;
uic_LabelStopwatchPlay= NULL;
ui_LabelStopwatchPlay= NULL;
uic_ButtonStopwatchReset= NULL;
ui_ButtonStopwatchReset= NULL;
ui_LabelStopwatchReset= NULL;
uic_LabelStopwatchDisplay= NULL;
ui_LabelStopwatchDisplay= NULL;
ui_HomeButton6= NULL;
ui_LabelMenu7= NULL;

}
