// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: fOS_1

#ifndef UI_SCREENWEB_H
#define UI_SCREENWEB_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenWeb
extern void ui_ScreenWeb_screen_init(void);
extern void ui_ScreenWeb_screen_destroy(void);
extern lv_obj_t *ui_ScreenWeb;
extern void ui_event_HomeButton2( lv_event_t * e);
extern lv_obj_t *ui_HomeButton2;
extern lv_obj_t *ui_LabelMenu3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

