// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: fOS_1

#ifndef UI_SCREENSETTINGSSYSTEMINFO_H
#define UI_SCREENSETTINGSSYSTEMINFO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenSettingsSystemInfo
extern void ui_ScreenSettingsSystemInfo_screen_init(void);
extern void ui_ScreenSettingsSystemInfo_screen_destroy(void);
extern lv_obj_t *ui_ScreenSettingsSystemInfo;
extern void ui_event_ButtonBack( lv_event_t * e);
extern lv_obj_t *ui_ButtonBack;
extern lv_obj_t *ui_LabelBack;
extern lv_obj_t *ui_systemInfoLabel;
extern lv_obj_t *ui_LabelHardwareInformation;
extern lv_obj_t *ui_LabelSoftwareInformation;
extern lv_obj_t *ui_LabelSoftwareInformationData;
// CUSTOM VARIABLES
extern lv_obj_t *uic_ScreenSettingsSystemInfo;
extern lv_obj_t *uic_ButtonBack;
extern lv_obj_t *uic_systemInfoLabel;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

