// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: fOS_1

#include "ui.h"

lv_obj_t *uic_BtnOpenNewFile;
lv_obj_t *uic_FileRollerText;
lv_obj_t *uic_BtnFileOpen;
lv_obj_t *uic_ButtonTextOpenCancel;
lv_obj_t *uic_PopupList;
lv_obj_t *uic_FileNameInput;
lv_obj_t *uic_BtnSaveConfirm;
lv_obj_t *uic_ButtonTextSaveCancel;
lv_obj_t *uic_PopupSave;
lv_obj_t *uic_BtnOpenFile;
lv_obj_t *uic_BtnSaveAs;
lv_obj_t *uic_TextArea;
lv_obj_t *uic_KeyboardText;
lv_obj_t *ui_ScreenText = NULL;lv_obj_t *ui_HomeButton3 = NULL;lv_obj_t *ui_LabelMenu4 = NULL;lv_obj_t *ui_KeyboardText = NULL;lv_obj_t *ui_TextArea = NULL;lv_obj_t *ui_BtnSaveAs = NULL;lv_obj_t *ui_LabelSaveAs = NULL;lv_obj_t *ui_BtnOpenFile = NULL;lv_obj_t *ui_LabelOpenFile = NULL;lv_obj_t *ui_PopupSave = NULL;lv_obj_t *ui_ButtonTextSaveCancel = NULL;lv_obj_t *ui_LabelTextSaveCancel = NULL;lv_obj_t *ui_BtnSaveConfirm = NULL;lv_obj_t *ui_LabelSaveConfirm = NULL;lv_obj_t *ui_FileNameInput = NULL;lv_obj_t *ui_PopupList = NULL;lv_obj_t *ui_ButtonTextOpenCancel = NULL;lv_obj_t *ui_LabelTextOpenCancel = NULL;lv_obj_t *ui_BtnFileOpen = NULL;lv_obj_t *ui_LabelSaveConfirm1 = NULL;lv_obj_t *ui_FileRollerText = NULL;lv_obj_t *ui_BtnOpenNewFile = NULL;lv_obj_t *ui_LabelOpenNewFile = NULL;
// event funtions
void ui_event_HomeButton3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenHome, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_ScreenHome_screen_init);
}
}

void ui_event_TextArea( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_keyboard_set_target(ui_KeyboardText,  ui_TextArea);
}
}

void ui_event_BtnSaveAs( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_PopupSave, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_keyboard_set_target(ui_KeyboardText,  ui_FileNameInput);
}
}

void ui_event_BtnOpenFile( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_PopupList, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

void ui_event_ButtonTextSaveCancel( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_PopupSave, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_BtnSaveConfirm( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      save_text_file( e );
}
if ( event_code == LV_EVENT_RELEASED) {
      _ui_flag_modify( ui_PopupSave, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_FileNameInput( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_keyboard_set_target(ui_KeyboardText,  ui_FileNameInput);
}
}

void ui_event_ButtonTextOpenCancel( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_PopupList, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_BtnFileOpen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      load_selected_file( e );
}
if ( event_code == LV_EVENT_RELEASED) {
      _ui_flag_modify( ui_PopupList, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_BtnOpenNewFile( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      OpenNewFile( e );
}
}

// build funtions

void ui_ScreenText_screen_init(void)
{
ui_ScreenText = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenText, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_HomeButton3 = lv_btn_create(ui_ScreenText);
lv_obj_set_width( ui_HomeButton3, 100);
lv_obj_set_height( ui_HomeButton3, 50);
lv_obj_set_x( ui_HomeButton3, -340 );
lv_obj_set_y( ui_HomeButton3, -210 );
lv_obj_set_align( ui_HomeButton3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_HomeButton3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_HomeButton3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_HomeButton3, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_HomeButton3, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HomeButton3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelMenu4 = lv_label_create(ui_ScreenText);
lv_obj_set_width( ui_LabelMenu4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelMenu4, LV_SIZE_CONTENT);   /// 0
lv_obj_set_x( ui_LabelMenu4, -340 );
lv_obj_set_y( ui_LabelMenu4, -210 );
lv_obj_set_align( ui_LabelMenu4, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelMenu4,"Menu");
lv_obj_set_style_text_color(ui_LabelMenu4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelMenu4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_LabelMenu4, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelMenu4, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_KeyboardText = lv_keyboard_create(ui_ScreenText);
lv_obj_set_width( ui_KeyboardText, 793);
lv_obj_set_height( ui_KeyboardText, 197);
lv_obj_set_x( ui_KeyboardText, 0 );
lv_obj_set_y( ui_KeyboardText, 135 );
lv_obj_set_align( ui_KeyboardText, LV_ALIGN_CENTER );

lv_obj_set_style_text_font(ui_KeyboardText, &lv_font_montserrat_20, LV_PART_ITEMS| LV_STATE_DEFAULT);

ui_TextArea = lv_textarea_create(ui_ScreenText);
lv_obj_set_width( ui_TextArea, 774);
lv_obj_set_height( ui_TextArea, 203);
lv_obj_set_x( ui_TextArea, 0 );
lv_obj_set_y( ui_TextArea, -69 );
lv_obj_set_align( ui_TextArea, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_TextArea,"You can enter your text here ...");
lv_obj_set_style_text_font(ui_TextArea, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(ui_TextArea, &lv_font_montserrat_20, LV_PART_SELECTED| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(ui_TextArea, &lv_font_montserrat_20, LV_PART_CURSOR| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(ui_TextArea, &lv_font_montserrat_20, LV_PART_TEXTAREA_PLACEHOLDER| LV_STATE_DEFAULT);

ui_BtnSaveAs = lv_btn_create(ui_ScreenText);
lv_obj_set_width( ui_BtnSaveAs, 200);
lv_obj_set_height( ui_BtnSaveAs, 50);
lv_obj_set_x( ui_BtnSaveAs, 76 );
lv_obj_set_y( ui_BtnSaveAs, -210 );
lv_obj_set_align( ui_BtnSaveAs, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BtnSaveAs, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BtnSaveAs, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_BtnSaveAs, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_BtnSaveAs, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BtnSaveAs, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelSaveAs = lv_label_create(ui_BtnSaveAs);
lv_obj_set_width( ui_LabelSaveAs, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelSaveAs, LV_SIZE_CONTENT);   /// 0
lv_obj_set_align( ui_LabelSaveAs, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelSaveAs,"Save as . . .");
lv_obj_set_style_text_color(ui_LabelSaveAs, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelSaveAs, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_LabelSaveAs, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelSaveAs, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BtnOpenFile = lv_btn_create(ui_ScreenText);
lv_obj_set_width( ui_BtnOpenFile, 200);
lv_obj_set_height( ui_BtnOpenFile, 50);
lv_obj_set_x( ui_BtnOpenFile, 286 );
lv_obj_set_y( ui_BtnOpenFile, -210 );
lv_obj_set_align( ui_BtnOpenFile, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BtnOpenFile, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BtnOpenFile, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_BtnOpenFile, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_BtnOpenFile, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BtnOpenFile, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelOpenFile = lv_label_create(ui_BtnOpenFile);
lv_obj_set_width( ui_LabelOpenFile, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelOpenFile, LV_SIZE_CONTENT);   /// 0
lv_obj_set_align( ui_LabelOpenFile, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelOpenFile,"Open file");
lv_obj_set_style_text_color(ui_LabelOpenFile, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelOpenFile, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_LabelOpenFile, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelOpenFile, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PopupSave = lv_obj_create(ui_ScreenText);
lv_obj_remove_style_all(ui_PopupSave);
lv_obj_set_width( ui_PopupSave, 600);
lv_obj_set_height( ui_PopupSave, 140);
lv_obj_set_x( ui_PopupSave, 0 );
lv_obj_set_y( ui_PopupSave, 88 );
lv_obj_set_align( ui_PopupSave, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_PopupSave, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_PopupSave, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_PopupSave, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PopupSave, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PopupSave, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonTextSaveCancel = lv_btn_create(ui_PopupSave);
lv_obj_set_width( ui_ButtonTextSaveCancel, 160);
lv_obj_set_height( ui_ButtonTextSaveCancel, 50);
lv_obj_set_x( ui_ButtonTextSaveCancel, -34 );
lv_obj_set_y( ui_ButtonTextSaveCancel, 33 );
lv_obj_set_align( ui_ButtonTextSaveCancel, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonTextSaveCancel, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonTextSaveCancel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ButtonTextSaveCancel, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ButtonTextSaveCancel, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonTextSaveCancel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelTextSaveCancel = lv_label_create(ui_PopupSave);
lv_obj_set_width( ui_LabelTextSaveCancel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelTextSaveCancel, LV_SIZE_CONTENT);   /// 0
lv_obj_set_x( ui_LabelTextSaveCancel, -34 );
lv_obj_set_y( ui_LabelTextSaveCancel, 33 );
lv_obj_set_align( ui_LabelTextSaveCancel, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelTextSaveCancel,"Cancel");
lv_obj_set_style_text_color(ui_LabelTextSaveCancel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelTextSaveCancel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_LabelTextSaveCancel, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelTextSaveCancel, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BtnSaveConfirm = lv_btn_create(ui_PopupSave);
lv_obj_set_width( ui_BtnSaveConfirm, 160);
lv_obj_set_height( ui_BtnSaveConfirm, 50);
lv_obj_set_x( ui_BtnSaveConfirm, -206 );
lv_obj_set_y( ui_BtnSaveConfirm, 33 );
lv_obj_set_align( ui_BtnSaveConfirm, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BtnSaveConfirm, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BtnSaveConfirm, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_BtnSaveConfirm, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_BtnSaveConfirm, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BtnSaveConfirm, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelSaveConfirm = lv_label_create(ui_PopupSave);
lv_obj_set_width( ui_LabelSaveConfirm, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelSaveConfirm, LV_SIZE_CONTENT);   /// 0
lv_obj_set_x( ui_LabelSaveConfirm, -206 );
lv_obj_set_y( ui_LabelSaveConfirm, 33 );
lv_obj_set_align( ui_LabelSaveConfirm, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelSaveConfirm,"Save");
lv_obj_set_style_text_color(ui_LabelSaveConfirm, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelSaveConfirm, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_LabelSaveConfirm, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelSaveConfirm, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FileNameInput = lv_textarea_create(ui_PopupSave);
lv_obj_set_width( ui_FileNameInput, 577);
lv_obj_set_height( ui_FileNameInput, 52);
lv_obj_set_x( ui_FileNameInput, 0 );
lv_obj_set_y( ui_FileNameInput, -32 );
lv_obj_set_align( ui_FileNameInput, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_FileNameInput,"File name . . .");
lv_obj_set_style_text_font(ui_FileNameInput, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(ui_FileNameInput, &lv_font_montserrat_20, LV_PART_SELECTED| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(ui_FileNameInput, &lv_font_montserrat_20, LV_PART_CURSOR| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(ui_FileNameInput, &lv_font_montserrat_20, LV_PART_TEXTAREA_PLACEHOLDER| LV_STATE_DEFAULT);

ui_PopupList = lv_obj_create(ui_ScreenText);
lv_obj_remove_style_all(ui_PopupList);
lv_obj_set_width( ui_PopupList, 600);
lv_obj_set_height( ui_PopupList, 350);
lv_obj_set_x( ui_PopupList, 0 );
lv_obj_set_y( ui_PopupList, 23 );
lv_obj_set_align( ui_PopupList, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_PopupList, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_PopupList, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_PopupList, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PopupList, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PopupList, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonTextOpenCancel = lv_btn_create(ui_PopupList);
lv_obj_set_width( ui_ButtonTextOpenCancel, 160);
lv_obj_set_height( ui_ButtonTextOpenCancel, 50);
lv_obj_set_x( ui_ButtonTextOpenCancel, -34 );
lv_obj_set_y( ui_ButtonTextOpenCancel, 140 );
lv_obj_set_align( ui_ButtonTextOpenCancel, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonTextOpenCancel, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonTextOpenCancel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ButtonTextOpenCancel, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ButtonTextOpenCancel, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonTextOpenCancel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelTextOpenCancel = lv_label_create(ui_PopupList);
lv_obj_set_width( ui_LabelTextOpenCancel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelTextOpenCancel, LV_SIZE_CONTENT);   /// 0
lv_obj_set_x( ui_LabelTextOpenCancel, -34 );
lv_obj_set_y( ui_LabelTextOpenCancel, 140 );
lv_obj_set_align( ui_LabelTextOpenCancel, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelTextOpenCancel,"Cancel");
lv_obj_set_style_text_color(ui_LabelTextOpenCancel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelTextOpenCancel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_LabelTextOpenCancel, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelTextOpenCancel, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BtnFileOpen = lv_btn_create(ui_PopupList);
lv_obj_set_width( ui_BtnFileOpen, 160);
lv_obj_set_height( ui_BtnFileOpen, 50);
lv_obj_set_x( ui_BtnFileOpen, -206 );
lv_obj_set_y( ui_BtnFileOpen, 140 );
lv_obj_set_align( ui_BtnFileOpen, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BtnFileOpen, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BtnFileOpen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_BtnFileOpen, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_BtnFileOpen, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BtnFileOpen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelSaveConfirm1 = lv_label_create(ui_PopupList);
lv_obj_set_width( ui_LabelSaveConfirm1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelSaveConfirm1, LV_SIZE_CONTENT);   /// 0
lv_obj_set_x( ui_LabelSaveConfirm1, -206 );
lv_obj_set_y( ui_LabelSaveConfirm1, 140 );
lv_obj_set_align( ui_LabelSaveConfirm1, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelSaveConfirm1,"Open");
lv_obj_set_style_text_color(ui_LabelSaveConfirm1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelSaveConfirm1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_LabelSaveConfirm1, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelSaveConfirm1, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FileRollerText = lv_roller_create(ui_PopupList);
lv_roller_set_options( ui_FileRollerText, "No file found", LV_ROLLER_MODE_NORMAL );
lv_obj_set_width( ui_FileRollerText, 576);
lv_obj_set_height( ui_FileRollerText, 266);
lv_obj_set_x( ui_FileRollerText, 0 );
lv_obj_set_y( ui_FileRollerText, -30 );
lv_obj_set_align( ui_FileRollerText, LV_ALIGN_CENTER );
lv_obj_set_style_text_align(ui_FileRollerText, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_FileRollerText, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BtnOpenNewFile = lv_btn_create(ui_ScreenText);
lv_obj_set_width( ui_BtnOpenNewFile, 200);
lv_obj_set_height( ui_BtnOpenNewFile, 50);
lv_obj_set_x( ui_BtnOpenNewFile, -134 );
lv_obj_set_y( ui_BtnOpenNewFile, -210 );
lv_obj_set_align( ui_BtnOpenNewFile, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BtnOpenNewFile, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BtnOpenNewFile, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_BtnOpenNewFile, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_BtnOpenNewFile, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BtnOpenNewFile, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelOpenNewFile = lv_label_create(ui_BtnOpenNewFile);
lv_obj_set_width( ui_LabelOpenNewFile, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelOpenNewFile, LV_SIZE_CONTENT);   /// 0
lv_obj_set_align( ui_LabelOpenNewFile, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelOpenNewFile,"Open New File");
lv_obj_set_style_text_color(ui_LabelOpenNewFile, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelOpenNewFile, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_LabelOpenNewFile, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelOpenNewFile, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_HomeButton3, ui_event_HomeButton3, LV_EVENT_ALL, NULL);
lv_keyboard_set_textarea(ui_KeyboardText,ui_TextArea);
lv_obj_add_event_cb(ui_TextArea, ui_event_TextArea, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BtnSaveAs, ui_event_BtnSaveAs, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BtnOpenFile, ui_event_BtnOpenFile, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonTextSaveCancel, ui_event_ButtonTextSaveCancel, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BtnSaveConfirm, ui_event_BtnSaveConfirm, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_FileNameInput, ui_event_FileNameInput, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonTextOpenCancel, ui_event_ButtonTextOpenCancel, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BtnFileOpen, ui_event_BtnFileOpen, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BtnOpenNewFile, ui_event_BtnOpenNewFile, LV_EVENT_ALL, NULL);
uic_KeyboardText = ui_KeyboardText;
uic_TextArea = ui_TextArea;
uic_BtnSaveAs = ui_BtnSaveAs;
uic_BtnOpenFile = ui_BtnOpenFile;
uic_PopupSave = ui_PopupSave;
uic_ButtonTextSaveCancel = ui_ButtonTextSaveCancel;
uic_BtnSaveConfirm = ui_BtnSaveConfirm;
uic_FileNameInput = ui_FileNameInput;
uic_PopupList = ui_PopupList;
uic_ButtonTextOpenCancel = ui_ButtonTextOpenCancel;
uic_BtnFileOpen = ui_BtnFileOpen;
uic_FileRollerText = ui_FileRollerText;
uic_BtnOpenNewFile = ui_BtnOpenNewFile;

}

void ui_ScreenText_screen_destroy(void)
{
   if (ui_ScreenText) lv_obj_del(ui_ScreenText);

// NULL screen variables
ui_ScreenText= NULL;
ui_HomeButton3= NULL;
ui_LabelMenu4= NULL;
uic_KeyboardText= NULL;
ui_KeyboardText= NULL;
uic_TextArea= NULL;
ui_TextArea= NULL;
uic_BtnSaveAs= NULL;
ui_BtnSaveAs= NULL;
ui_LabelSaveAs= NULL;
uic_BtnOpenFile= NULL;
ui_BtnOpenFile= NULL;
ui_LabelOpenFile= NULL;
uic_PopupSave= NULL;
ui_PopupSave= NULL;
uic_ButtonTextSaveCancel= NULL;
ui_ButtonTextSaveCancel= NULL;
ui_LabelTextSaveCancel= NULL;
uic_BtnSaveConfirm= NULL;
ui_BtnSaveConfirm= NULL;
ui_LabelSaveConfirm= NULL;
uic_FileNameInput= NULL;
ui_FileNameInput= NULL;
uic_PopupList= NULL;
ui_PopupList= NULL;
uic_ButtonTextOpenCancel= NULL;
ui_ButtonTextOpenCancel= NULL;
ui_LabelTextOpenCancel= NULL;
uic_BtnFileOpen= NULL;
ui_BtnFileOpen= NULL;
ui_LabelSaveConfirm1= NULL;
uic_FileRollerText= NULL;
ui_FileRollerText= NULL;
uic_BtnOpenNewFile= NULL;
ui_BtnOpenNewFile= NULL;
ui_LabelOpenNewFile= NULL;

}
