// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: fOS_1

#include "ui.h"

lv_obj_t *uic_BootProgressLabel;
lv_obj_t *uic_BootProgressBar;
lv_obj_t *uic_BootOverlay;
lv_obj_t *uic_labelClockTopLine;
lv_obj_t *uic_WiFiImage;
lv_obj_t *uic_AppCalculator;
lv_obj_t *uic_AppClock;
lv_obj_t *uic_AppWeather;
lv_obj_t *uic_AppRadio;
lv_obj_t *uic_AppText;
lv_obj_t *uic_AppWeb;
lv_obj_t *uic_AppFileManager;
lv_obj_t *uic_AppSettings;
lv_obj_t *uic_TabViewHome;
lv_obj_t *uic_ScreenHome;
lv_obj_t *ui_ScreenHome = NULL;lv_obj_t *ui_TabViewHome = NULL;lv_obj_t *ui_HomePage1 = NULL;lv_obj_t *ui_AppSettings = NULL;lv_obj_t *ui_AppFileManager = NULL;lv_obj_t *ui_AppWeb = NULL;lv_obj_t *ui_AppText = NULL;lv_obj_t *ui_AppRadio = NULL;lv_obj_t *ui_AppWeather = NULL;lv_obj_t *ui_AppClock = NULL;lv_obj_t *ui_AppCalculator = NULL;lv_obj_t *ui_HomePage2 = NULL;lv_obj_t *ui_WiFiImage = NULL;lv_obj_t *ui_labelClockTopLine = NULL;lv_obj_t *ui_BootOverlay = NULL;lv_obj_t *ui_Image1 = NULL;lv_obj_t *ui_BootProgressBar = NULL;lv_obj_t *ui_BootProgressLabel = NULL;
// event funtions
void ui_event_AppSettings( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenSettings, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenSettings_screen_init);
}
}

void ui_event_AppFileManager( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenFileManager, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenFileManager_screen_init);
}
if ( event_code == LV_EVENT_CLICKED) {
      updateSDUI( e );
}
}

void ui_event_AppWeb( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenWeb, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenWeb_screen_init);
}
}

void ui_event_AppText( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenText, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenText_screen_init);
}
if ( event_code == LV_EVENT_CLICKED) {
      fillFileRoller_TextViewer( e );
}
}

void ui_event_AppRadio( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenRadio, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenRadio_screen_init);
}
if ( event_code == LV_EVENT_CLICKED) {
      fillFileRoller_Radio( e );
}
}

void ui_event_AppWeather( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenWeather, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenWeather_screen_init);
}
if ( event_code == LV_EVENT_CLICKED) {
      StartWeatherApp( e );
}
}

void ui_event_AppClock( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenClock, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenClock_screen_init);
}
}

void ui_event_AppCalculator( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenCalculator, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenCalculator_screen_init);
}
}

// build funtions

void ui_ScreenHome_screen_init(void)
{
ui_ScreenHome = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenHome, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TabViewHome = lv_tabview_create(ui_ScreenHome, LV_DIR_TOP, 0);
lv_obj_set_width( ui_TabViewHome, 800);
lv_obj_set_height( ui_TabViewHome, 387);
lv_obj_set_align( ui_TabViewHome, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_TabViewHome, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_HomePage1 = lv_tabview_add_tab(ui_TabViewHome, "HomePage1");

ui_AppSettings = lv_obj_create(ui_HomePage1);
lv_obj_set_width( ui_AppSettings, 120);
lv_obj_set_height( ui_AppSettings, 120);
lv_obj_set_x( ui_AppSettings, -240 );
lv_obj_set_y( ui_AppSettings, -70 );
lv_obj_set_align( ui_AppSettings, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_AppSettings, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_AppSettings, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_AppSettings, &ui_img_350490791, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_AppFileManager = lv_obj_create(ui_HomePage1);
lv_obj_set_width( ui_AppFileManager, 120);
lv_obj_set_height( ui_AppFileManager, 120);
lv_obj_set_x( ui_AppFileManager, -80 );
lv_obj_set_y( ui_AppFileManager, -70 );
lv_obj_set_align( ui_AppFileManager, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_AppFileManager, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_AppFileManager, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_AppFileManager, lv_color_hex(0xA7A7A7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_AppFileManager, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_AppFileManager, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_AppFileManager, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_AppFileManager, &ui_img_folder_png, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_AppWeb = lv_obj_create(ui_HomePage1);
lv_obj_set_width( ui_AppWeb, 120);
lv_obj_set_height( ui_AppWeb, 120);
lv_obj_set_x( ui_AppWeb, 80 );
lv_obj_set_y( ui_AppWeb, -70 );
lv_obj_set_align( ui_AppWeb, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_AppWeb, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_AppWeb, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_AppWeb, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_AppWeb, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_AppWeb, &ui_img_2114985472, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_AppText = lv_obj_create(ui_HomePage1);
lv_obj_set_width( ui_AppText, 120);
lv_obj_set_height( ui_AppText, 120);
lv_obj_set_x( ui_AppText, 240 );
lv_obj_set_y( ui_AppText, -70 );
lv_obj_set_align( ui_AppText, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_AppText, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_AppText, 21, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_AppText, &ui_img_1781796769, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_AppRadio = lv_obj_create(ui_HomePage1);
lv_obj_set_width( ui_AppRadio, 120);
lv_obj_set_height( ui_AppRadio, 120);
lv_obj_set_x( ui_AppRadio, -240 );
lv_obj_set_y( ui_AppRadio, 70 );
lv_obj_set_align( ui_AppRadio, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_AppRadio, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_AppRadio, 27, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_AppRadio, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_AppRadio, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_AppRadio, &ui_img_1607212695, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_AppWeather = lv_obj_create(ui_HomePage1);
lv_obj_set_width( ui_AppWeather, 120);
lv_obj_set_height( ui_AppWeather, 120);
lv_obj_set_x( ui_AppWeather, -80 );
lv_obj_set_y( ui_AppWeather, 70 );
lv_obj_set_align( ui_AppWeather, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_AppWeather, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_AppWeather, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_AppWeather, lv_color_hex(0x3C9FF8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_AppWeather, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_AppWeather, lv_color_hex(0x2656BE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_AppWeather, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_AppWeather, &ui_img_1045517857, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_AppClock = lv_obj_create(ui_HomePage1);
lv_obj_set_width( ui_AppClock, 120);
lv_obj_set_height( ui_AppClock, 120);
lv_obj_set_x( ui_AppClock, 80 );
lv_obj_set_y( ui_AppClock, 70 );
lv_obj_set_align( ui_AppClock, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_AppClock, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_AppClock, 21, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_AppClock, &ui_img_294430296, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_AppCalculator = lv_obj_create(ui_HomePage1);
lv_obj_set_width( ui_AppCalculator, 120);
lv_obj_set_height( ui_AppCalculator, 120);
lv_obj_set_x( ui_AppCalculator, 240 );
lv_obj_set_y( ui_AppCalculator, 70 );
lv_obj_set_align( ui_AppCalculator, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_AppCalculator, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_AppCalculator, 19, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_AppCalculator, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_AppCalculator, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_AppCalculator, &ui_img_1548352994, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_HomePage2 = lv_tabview_add_tab(ui_TabViewHome, "HomePage2");
lv_obj_add_flag( ui_HomePage2, LV_OBJ_FLAG_HIDDEN );   /// Flags

ui_WiFiImage = lv_img_create(ui_ScreenHome);
lv_img_set_src(ui_WiFiImage, &ui_img_1837598647);
lv_obj_set_width( ui_WiFiImage, LV_SIZE_CONTENT);  /// 36
lv_obj_set_height( ui_WiFiImage, LV_SIZE_CONTENT);   /// 31
lv_obj_set_x( ui_WiFiImage, 168 );
lv_obj_set_y( ui_WiFiImage, -220 );
lv_obj_set_align( ui_WiFiImage, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_WiFiImage, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_WiFiImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_labelClockTopLine = lv_label_create(ui_ScreenHome);
lv_obj_set_width( ui_labelClockTopLine, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labelClockTopLine, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_labelClockTopLine, 292 );
lv_obj_set_y( ui_labelClockTopLine, -216 );
lv_obj_set_align( ui_labelClockTopLine, LV_ALIGN_CENTER );
lv_label_set_text(ui_labelClockTopLine,"Mo. 01. Jan. 00:00");
lv_obj_set_style_text_font(ui_labelClockTopLine, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BootOverlay = lv_obj_create(ui_ScreenHome);
lv_obj_remove_style_all(ui_BootOverlay);
lv_obj_set_width( ui_BootOverlay, 800);
lv_obj_set_height( ui_BootOverlay, 480);
lv_obj_set_align( ui_BootOverlay, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_BootOverlay, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_BootOverlay, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BootOverlay, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image1 = lv_img_create(ui_BootOverlay);
lv_img_set_src(ui_Image1, &ui_img_fos_256x256_png);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 256
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 256
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BootProgressBar = lv_bar_create(ui_BootOverlay);
lv_obj_set_width( ui_BootProgressBar, 400);
lv_obj_set_height( ui_BootProgressBar, 15);
lv_obj_set_x( ui_BootProgressBar, 0 );
lv_obj_set_y( ui_BootProgressBar, 128 );
lv_obj_set_align( ui_BootProgressBar, LV_ALIGN_CENTER );

ui_BootProgressLabel = lv_label_create(ui_BootOverlay);
lv_obj_set_width( ui_BootProgressLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BootProgressLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BootProgressLabel, 2 );
lv_obj_set_y( ui_BootProgressLabel, 164 );
lv_obj_set_align( ui_BootProgressLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_BootProgressLabel,"Booting . . .");
lv_obj_set_style_text_font(ui_BootProgressLabel, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_AppSettings, ui_event_AppSettings, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_AppFileManager, ui_event_AppFileManager, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_AppWeb, ui_event_AppWeb, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_AppText, ui_event_AppText, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_AppRadio, ui_event_AppRadio, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_AppWeather, ui_event_AppWeather, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_AppClock, ui_event_AppClock, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_AppCalculator, ui_event_AppCalculator, LV_EVENT_ALL, NULL);
uic_ScreenHome = ui_ScreenHome;
uic_TabViewHome = ui_TabViewHome;
uic_AppSettings = ui_AppSettings;
uic_AppFileManager = ui_AppFileManager;
uic_AppWeb = ui_AppWeb;
uic_AppText = ui_AppText;
uic_AppRadio = ui_AppRadio;
uic_AppWeather = ui_AppWeather;
uic_AppClock = ui_AppClock;
uic_AppCalculator = ui_AppCalculator;
uic_WiFiImage = ui_WiFiImage;
uic_labelClockTopLine = ui_labelClockTopLine;
uic_BootOverlay = ui_BootOverlay;
uic_BootProgressBar = ui_BootProgressBar;
uic_BootProgressLabel = ui_BootProgressLabel;

}

void ui_ScreenHome_screen_destroy(void)
{
   if (ui_ScreenHome) lv_obj_del(ui_ScreenHome);

// NULL screen variables
uic_ScreenHome= NULL;
ui_ScreenHome= NULL;
uic_TabViewHome= NULL;
ui_TabViewHome= NULL;
ui_HomePage1= NULL;
uic_AppSettings= NULL;
ui_AppSettings= NULL;
uic_AppFileManager= NULL;
ui_AppFileManager= NULL;
uic_AppWeb= NULL;
ui_AppWeb= NULL;
uic_AppText= NULL;
ui_AppText= NULL;
uic_AppRadio= NULL;
ui_AppRadio= NULL;
uic_AppWeather= NULL;
ui_AppWeather= NULL;
uic_AppClock= NULL;
ui_AppClock= NULL;
uic_AppCalculator= NULL;
ui_AppCalculator= NULL;
ui_HomePage2= NULL;
uic_WiFiImage= NULL;
ui_WiFiImage= NULL;
uic_labelClockTopLine= NULL;
ui_labelClockTopLine= NULL;
uic_BootOverlay= NULL;
ui_BootOverlay= NULL;
ui_Image1= NULL;
uic_BootProgressBar= NULL;
ui_BootProgressBar= NULL;
uic_BootProgressLabel= NULL;
ui_BootProgressLabel= NULL;

}
