// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: fOS_1

#ifndef UI_SCREENTEXT_H
#define UI_SCREENTEXT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenText
extern void ui_ScreenText_screen_init(void);
extern void ui_ScreenText_screen_destroy(void);
extern lv_obj_t *ui_ScreenText;
extern void ui_event_HomeButton3( lv_event_t * e);
extern lv_obj_t *ui_HomeButton3;
extern lv_obj_t *ui_LabelMenu4;
extern lv_obj_t *ui_KeyboardText;
extern void ui_event_TextArea( lv_event_t * e);
extern lv_obj_t *ui_TextArea;
extern void ui_event_BtnSaveAs( lv_event_t * e);
extern lv_obj_t *ui_BtnSaveAs;
extern lv_obj_t *ui_LabelSaveAs;
extern void ui_event_BtnOpenFile( lv_event_t * e);
extern lv_obj_t *ui_BtnOpenFile;
extern lv_obj_t *ui_LabelOpenFile;
extern lv_obj_t *ui_PopupSave;
extern void ui_event_ButtonTextSaveCancel( lv_event_t * e);
extern lv_obj_t *ui_ButtonTextSaveCancel;
extern lv_obj_t *ui_LabelTextSaveCancel;
extern void ui_event_BtnSaveConfirm( lv_event_t * e);
extern lv_obj_t *ui_BtnSaveConfirm;
extern lv_obj_t *ui_LabelSaveConfirm;
extern void ui_event_FileNameInput( lv_event_t * e);
extern lv_obj_t *ui_FileNameInput;
extern lv_obj_t *ui_PopupList;
extern void ui_event_ButtonTextOpenCancel( lv_event_t * e);
extern lv_obj_t *ui_ButtonTextOpenCancel;
extern lv_obj_t *ui_LabelTextOpenCancel;
extern void ui_event_BtnFileOpen( lv_event_t * e);
extern lv_obj_t *ui_BtnFileOpen;
extern lv_obj_t *ui_LabelSaveConfirm1;
extern lv_obj_t *ui_FileRollerText;
// CUSTOM VARIABLES
extern lv_obj_t *uic_KeyboardText;
extern lv_obj_t *uic_TextArea;
extern lv_obj_t *uic_BtnSaveAs;
extern lv_obj_t *uic_BtnOpenFile;
extern lv_obj_t *uic_PopupSave;
extern lv_obj_t *uic_ButtonTextSaveCancel;
extern lv_obj_t *uic_BtnSaveConfirm;
extern lv_obj_t *uic_FileNameInput;
extern lv_obj_t *uic_PopupList;
extern lv_obj_t *uic_ButtonTextOpenCancel;
extern lv_obj_t *uic_BtnFileOpen;
extern lv_obj_t *uic_FileRollerText;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

