// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: fOS_1

#include "ui.h"

lv_obj_t *uic_ButtonSettingsSystemInfo;
lv_obj_t *uic_ScreenSettings;
lv_obj_t *ui_ScreenSettings = NULL;lv_obj_t *ui_HomeButton = NULL;lv_obj_t *ui_LabelMenu1 = NULL;lv_obj_t *ui_ButtonSettingsSystemInfo = NULL;lv_obj_t *ui_LabelSettingsSystemInfo = NULL;
// event funtions
void ui_event_HomeButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenHome, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_ScreenHome_screen_init);
}
}

void ui_event_ButtonSettingsSystemInfo( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenSettingsSystemInfo, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_ScreenSettingsSystemInfo_screen_init);
}
if ( event_code == LV_EVENT_CLICKED) {
      updateSystemInfo( e );
}
}

// build funtions

void ui_ScreenSettings_screen_init(void)
{
ui_ScreenSettings = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenSettings, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_HomeButton = lv_btn_create(ui_ScreenSettings);
lv_obj_set_width( ui_HomeButton, 100);
lv_obj_set_height( ui_HomeButton, 50);
lv_obj_set_x( ui_HomeButton, -340 );
lv_obj_set_y( ui_HomeButton, -210 );
lv_obj_set_align( ui_HomeButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_HomeButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_HomeButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_HomeButton, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_HomeButton, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HomeButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelMenu1 = lv_label_create(ui_ScreenSettings);
lv_obj_set_width( ui_LabelMenu1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelMenu1, LV_SIZE_CONTENT);   /// 0
lv_obj_set_x( ui_LabelMenu1, -340 );
lv_obj_set_y( ui_LabelMenu1, -210 );
lv_obj_set_align( ui_LabelMenu1, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelMenu1,"Menu");
lv_obj_set_style_text_color(ui_LabelMenu1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelMenu1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_LabelMenu1, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelMenu1, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonSettingsSystemInfo = lv_btn_create(ui_ScreenSettings);
lv_obj_set_width( ui_ButtonSettingsSystemInfo, 180);
lv_obj_set_height( ui_ButtonSettingsSystemInfo, 50);
lv_obj_set_x( ui_ButtonSettingsSystemInfo, -298 );
lv_obj_set_y( ui_ButtonSettingsSystemInfo, -150 );
lv_obj_set_align( ui_ButtonSettingsSystemInfo, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonSettingsSystemInfo, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonSettingsSystemInfo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ButtonSettingsSystemInfo, 7, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelSettingsSystemInfo = lv_label_create(ui_ScreenSettings);
lv_obj_set_width( ui_LabelSettingsSystemInfo, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelSettingsSystemInfo, LV_SIZE_CONTENT);   /// 0
lv_obj_set_x( ui_LabelSettingsSystemInfo, -295 );
lv_obj_set_y( ui_LabelSettingsSystemInfo, -150 );
lv_obj_set_align( ui_LabelSettingsSystemInfo, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelSettingsSystemInfo,"Information");
lv_obj_set_style_text_color(ui_LabelSettingsSystemInfo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelSettingsSystemInfo, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_LabelSettingsSystemInfo, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelSettingsSystemInfo, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_HomeButton, ui_event_HomeButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonSettingsSystemInfo, ui_event_ButtonSettingsSystemInfo, LV_EVENT_ALL, NULL);
uic_ScreenSettings = ui_ScreenSettings;
uic_ButtonSettingsSystemInfo = ui_ButtonSettingsSystemInfo;

}

void ui_ScreenSettings_screen_destroy(void)
{
   if (ui_ScreenSettings) lv_obj_del(ui_ScreenSettings);

// NULL screen variables
uic_ScreenSettings= NULL;
ui_ScreenSettings= NULL;
ui_HomeButton= NULL;
ui_LabelMenu1= NULL;
uic_ButtonSettingsSystemInfo= NULL;
ui_ButtonSettingsSystemInfo= NULL;
ui_LabelSettingsSystemInfo= NULL;

}
