// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: fOS_2

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void updateSystemInfo(lv_event_t * e);
void SaveWifiConnection(lv_event_t * e);
void runWifiConnection(lv_event_t * e);
void StopWifiConnection(lv_event_t * e);
void SaveTimeZone(lv_event_t * e);
void SaveDisplaySettings(lv_event_t * e);
void BackToHomeFromFileManager(lv_event_t * e);
void StorageManagerSelect(lv_event_t * e);
void DeleteFileSelected(lv_event_t * e);
void InstallUpdate(lv_event_t * e);
void UnloadApp(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
