// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: fOS_2

#include "ui.h"

void SaveTimeZone_Data(lv_event_t * e);
void StorageManagerSelect_Data(lv_event_t * e);
void ResetStorageManagerToRoot_Data(void);
void UnloadApp_Data(lv_event_t * e);

void updateSystemInfo(lv_event_t * e)
{
	updateSystemInfoData();
}

void fillFileRoller_TextViewer(lv_event_t * e)
{
	fillFileRoller_TextViewer_Data();
}

void ReloadWiFiConnection(lv_event_t * e)
{
	ReloadWiFiConnection_Data();
}

void SaveWifiConnection(lv_event_t * e)
{
	SaveWifiConnection_Data();
}

void SaveTimeZone(lv_event_t * e)
{
	SaveTimeZone_Data( e );
}

void BackToHomeFromFileManager(lv_event_t * e)
{
	if (lv_event_get_code(e) == LV_EVENT_CLICKED) {
		ResetStorageManagerToRoot_Data();
	}
}

void StorageManagerSelect(lv_event_t * e)
{
	if (lv_event_get_code(e) == LV_EVENT_CLICKED) {
		StorageManagerSelect_Data(e);
	}
}

void DeleteFileSelected(lv_event_t * e)
{
	if (lv_event_get_code(e) == LV_EVENT_CLICKED) {
        deleteSelectedFile();
    }
}

void BackToHomeFromText(lv_event_t * e)
{
	OpenNewFile_Data();
}

void OpenNewFile(lv_event_t * e)
{
	OpenNewFile_Data();
}

void save_text_file(lv_event_t * e)
{
	save_text_file_data();
}

void load_selected_file(lv_event_t * e)
{
	load_selected_file_Data();
}

void UnloadApp(lv_event_t * e)
{
	if (lv_event_get_code(e) == LV_EVENT_CLICKED) {
		UnloadApp_Data(e);
	}
}
