// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: fOS_2

#include "ui.h"

lv_obj_t *uic_BootProgressLabel;
lv_obj_t *uic_BootProgressBar;
lv_obj_t *uic_BootOverlay;
lv_obj_t *uic_labelClockTopLine;
lv_obj_t *uic_WiFiImage;
lv_obj_t *uic_AppL6;
lv_obj_t *uic_AppL5;
lv_obj_t *uic_AppL4;
lv_obj_t *uic_AppL3;
lv_obj_t *uic_AppL2;
lv_obj_t *uic_AppL1;
lv_obj_t *uic_AppText;
lv_obj_t *uic_AppSettings;
lv_obj_t *uic_ScreenHome;
lv_obj_t *ui_ScreenHome = NULL;lv_obj_t *ui_AppSettings = NULL;lv_obj_t *ui_AppText = NULL;lv_obj_t *ui_AppL1 = NULL;lv_obj_t *ui_AppL2 = NULL;lv_obj_t *ui_AppL3 = NULL;lv_obj_t *ui_AppL4 = NULL;lv_obj_t *ui_AppL5 = NULL;lv_obj_t *ui_AppL6 = NULL;lv_obj_t *ui_WiFiImage = NULL;lv_obj_t *ui_labelClockTopLine = NULL;lv_obj_t *ui_BootOverlay = NULL;lv_obj_t *ui_fOS = NULL;lv_obj_t *ui_BootProgressBar = NULL;lv_obj_t *ui_BootProgressLabel = NULL;
// event funtions
void ui_event_AppSettings( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenSettings, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenSettings_screen_init);
}
if ( event_code == LV_EVENT_CLICKED) {
      updateSystemInfo( e );
}
}

void ui_event_AppText( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenText, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenText_screen_init);
}
if ( event_code == LV_EVENT_CLICKED) {
      fillFileRoller_TextViewer( e );
}
}

// build funtions

void ui_ScreenHome_screen_init(void)
{
ui_ScreenHome = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenHome, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_AppSettings = lv_obj_create(ui_ScreenHome);
lv_obj_set_width( ui_AppSettings, 120);
lv_obj_set_height( ui_AppSettings, 120);
lv_obj_set_x( ui_AppSettings, -240 );
lv_obj_set_y( ui_AppSettings, -70 );
lv_obj_set_align( ui_AppSettings, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_AppSettings, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_AppSettings, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_AppSettings, &ui_img_350490791, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_AppText = lv_obj_create(ui_ScreenHome);
lv_obj_set_width( ui_AppText, 120);
lv_obj_set_height( ui_AppText, 120);
lv_obj_set_x( ui_AppText, -240 );
lv_obj_set_y( ui_AppText, 70 );
lv_obj_set_align( ui_AppText, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_AppText, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_AppText, 21, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_AppText, &ui_img_1781796769, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_AppL1 = lv_obj_create(ui_ScreenHome);
lv_obj_remove_style_all(ui_AppL1);
lv_obj_set_width( ui_AppL1, 120);
lv_obj_set_height( ui_AppL1, 120);
lv_obj_set_x( ui_AppL1, -80 );
lv_obj_set_y( ui_AppL1, -70 );
lv_obj_set_align( ui_AppL1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_AppL1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_AppL2 = lv_obj_create(ui_ScreenHome);
lv_obj_remove_style_all(ui_AppL2);
lv_obj_set_width( ui_AppL2, 120);
lv_obj_set_height( ui_AppL2, 120);
lv_obj_set_x( ui_AppL2, 80 );
lv_obj_set_y( ui_AppL2, -70 );
lv_obj_set_align( ui_AppL2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_AppL2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_AppL3 = lv_obj_create(ui_ScreenHome);
lv_obj_remove_style_all(ui_AppL3);
lv_obj_set_width( ui_AppL3, 120);
lv_obj_set_height( ui_AppL3, 120);
lv_obj_set_x( ui_AppL3, 240 );
lv_obj_set_y( ui_AppL3, -70 );
lv_obj_set_align( ui_AppL3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_AppL3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_AppL4 = lv_obj_create(ui_ScreenHome);
lv_obj_remove_style_all(ui_AppL4);
lv_obj_set_width( ui_AppL4, 120);
lv_obj_set_height( ui_AppL4, 120);
lv_obj_set_x( ui_AppL4, -80 );
lv_obj_set_y( ui_AppL4, 70 );
lv_obj_set_align( ui_AppL4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_AppL4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_AppL5 = lv_obj_create(ui_ScreenHome);
lv_obj_remove_style_all(ui_AppL5);
lv_obj_set_width( ui_AppL5, 120);
lv_obj_set_height( ui_AppL5, 120);
lv_obj_set_x( ui_AppL5, 80 );
lv_obj_set_y( ui_AppL5, 70 );
lv_obj_set_align( ui_AppL5, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_AppL5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_AppL6 = lv_obj_create(ui_ScreenHome);
lv_obj_remove_style_all(ui_AppL6);
lv_obj_set_width( ui_AppL6, 120);
lv_obj_set_height( ui_AppL6, 120);
lv_obj_set_x( ui_AppL6, 240 );
lv_obj_set_y( ui_AppL6, 70 );
lv_obj_set_align( ui_AppL6, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_AppL6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_WiFiImage = lv_img_create(ui_ScreenHome);
lv_img_set_src(ui_WiFiImage, &ui_img_1837598647);
lv_obj_set_width( ui_WiFiImage, LV_SIZE_CONTENT);  /// 36
lv_obj_set_height( ui_WiFiImage, LV_SIZE_CONTENT);   /// 31
lv_obj_set_x( ui_WiFiImage, 168 );
lv_obj_set_y( ui_WiFiImage, -220 );
lv_obj_set_align( ui_WiFiImage, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_WiFiImage, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_WiFiImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_labelClockTopLine = lv_label_create(ui_ScreenHome);
lv_obj_set_width( ui_labelClockTopLine, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labelClockTopLine, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_labelClockTopLine, 292 );
lv_obj_set_y( ui_labelClockTopLine, -216 );
lv_obj_set_align( ui_labelClockTopLine, LV_ALIGN_CENTER );
lv_label_set_text(ui_labelClockTopLine,"Mo. 01. Jan. 00:00");
lv_obj_set_style_text_font(ui_labelClockTopLine, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BootOverlay = lv_obj_create(ui_ScreenHome);
lv_obj_remove_style_all(ui_BootOverlay);
lv_obj_set_width( ui_BootOverlay, 800);
lv_obj_set_height( ui_BootOverlay, 480);
lv_obj_set_align( ui_BootOverlay, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_BootOverlay, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_BootOverlay, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BootOverlay, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_fOS = lv_img_create(ui_BootOverlay);
lv_img_set_src(ui_fOS, &ui_img_fos_256x256_png);
lv_obj_set_width( ui_fOS, LV_SIZE_CONTENT);  /// 256
lv_obj_set_height( ui_fOS, LV_SIZE_CONTENT);   /// 256
lv_obj_set_align( ui_fOS, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_fOS, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_fOS, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BootProgressBar = lv_bar_create(ui_BootOverlay);
lv_obj_set_width( ui_BootProgressBar, 400);
lv_obj_set_height( ui_BootProgressBar, 15);
lv_obj_set_x( ui_BootProgressBar, 0 );
lv_obj_set_y( ui_BootProgressBar, 128 );
lv_obj_set_align( ui_BootProgressBar, LV_ALIGN_CENTER );

ui_BootProgressLabel = lv_label_create(ui_BootOverlay);
lv_obj_set_width( ui_BootProgressLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BootProgressLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BootProgressLabel, 2 );
lv_obj_set_y( ui_BootProgressLabel, 164 );
lv_obj_set_align( ui_BootProgressLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_BootProgressLabel,"Booting . . .");
lv_obj_set_style_text_font(ui_BootProgressLabel, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_AppSettings, ui_event_AppSettings, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_AppText, ui_event_AppText, LV_EVENT_ALL, NULL);
uic_ScreenHome = ui_ScreenHome;
uic_AppSettings = ui_AppSettings;
uic_AppText = ui_AppText;
uic_AppL1 = ui_AppL1;
uic_AppL2 = ui_AppL2;
uic_AppL3 = ui_AppL3;
uic_AppL4 = ui_AppL4;
uic_AppL5 = ui_AppL5;
uic_AppL6 = ui_AppL6;
uic_WiFiImage = ui_WiFiImage;
uic_labelClockTopLine = ui_labelClockTopLine;
uic_BootOverlay = ui_BootOverlay;
uic_BootProgressBar = ui_BootProgressBar;
uic_BootProgressLabel = ui_BootProgressLabel;

}

void ui_ScreenHome_screen_destroy(void)
{
   if (ui_ScreenHome) lv_obj_del(ui_ScreenHome);

// NULL screen variables
uic_ScreenHome= NULL;
ui_ScreenHome= NULL;
uic_AppSettings= NULL;
ui_AppSettings= NULL;
uic_AppText= NULL;
ui_AppText= NULL;
uic_AppL1= NULL;
ui_AppL1= NULL;
uic_AppL2= NULL;
ui_AppL2= NULL;
uic_AppL3= NULL;
ui_AppL3= NULL;
uic_AppL4= NULL;
ui_AppL4= NULL;
uic_AppL5= NULL;
ui_AppL5= NULL;
uic_AppL6= NULL;
ui_AppL6= NULL;
uic_WiFiImage= NULL;
ui_WiFiImage= NULL;
uic_labelClockTopLine= NULL;
ui_labelClockTopLine= NULL;
uic_BootOverlay= NULL;
ui_BootOverlay= NULL;
ui_fOS= NULL;
uic_BootProgressBar= NULL;
ui_BootProgressBar= NULL;
uic_BootProgressLabel= NULL;
ui_BootProgressLabel= NULL;

}
