// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: fOS_2

#ifndef UI_SCREENHOME_H
#define UI_SCREENHOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenHome
extern void ui_ScreenHome_screen_init(void);
extern void ui_ScreenHome_screen_destroy(void);
extern lv_obj_t *ui_ScreenHome;
extern void ui_event_AppSettings( lv_event_t * e);
extern lv_obj_t *ui_AppSettings;
extern void ui_event_AppText( lv_event_t * e);
extern lv_obj_t *ui_AppText;
extern lv_obj_t *ui_AppL1;
extern lv_obj_t *ui_AppL2;
extern lv_obj_t *ui_AppL3;
extern lv_obj_t *ui_AppL4;
extern lv_obj_t *ui_AppL5;
extern lv_obj_t *ui_AppL6;
extern lv_obj_t *ui_WiFiImage;
extern lv_obj_t *ui_labelClockTopLine;
extern lv_obj_t *ui_BootOverlay;
extern lv_obj_t *ui_fOS;
extern lv_obj_t *ui_BootProgressBar;
extern lv_obj_t *ui_BootProgressLabel;
// CUSTOM VARIABLES
extern lv_obj_t *uic_ScreenHome;
extern lv_obj_t *uic_AppSettings;
extern lv_obj_t *uic_AppText;
extern lv_obj_t *uic_AppL1;
extern lv_obj_t *uic_AppL2;
extern lv_obj_t *uic_AppL3;
extern lv_obj_t *uic_AppL4;
extern lv_obj_t *uic_AppL5;
extern lv_obj_t *uic_AppL6;
extern lv_obj_t *uic_WiFiImage;
extern lv_obj_t *uic_labelClockTopLine;
extern lv_obj_t *uic_BootOverlay;
extern lv_obj_t *uic_BootProgressBar;
extern lv_obj_t *uic_BootProgressLabel;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

