// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: fOS_2

#include "ui.h"

lv_obj_t *uic_InstallProgressBar;
lv_obj_t *uic_DropdownUpdate;
lv_obj_t *ui_Update = NULL;lv_obj_t *ui_HomeButton2 = NULL;lv_obj_t *ui_LabelMenu4 = NULL;lv_obj_t *ui_DropdownUpdate = NULL;lv_obj_t *ui_ButtonInstallUpdate = NULL;lv_obj_t *ui_LabelInstallUpdate = NULL;lv_obj_t *ui_InstallProgressBar = NULL;lv_obj_t *ui_DowngradeInfo = NULL;
// event funtions
void ui_event_HomeButton2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenSettings, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenSettings_screen_init);
}
if ( event_code == LV_EVENT_CLICKED) {
      BackToHomeFromFileManager( e );
}
}

void ui_event_ButtonInstallUpdate( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      InstallUpdate( e );
}
}

// build funtions

void ui_Update_screen_init(void)
{
ui_Update = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Update, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_text_font(ui_Update, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HomeButton2 = lv_btn_create(ui_Update);
lv_obj_set_width( ui_HomeButton2, 100);
lv_obj_set_height( ui_HomeButton2, 50);
lv_obj_set_x( ui_HomeButton2, -340 );
lv_obj_set_y( ui_HomeButton2, -210 );
lv_obj_set_align( ui_HomeButton2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_HomeButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_HomeButton2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_HomeButton2, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_HomeButton2, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HomeButton2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelMenu4 = lv_label_create(ui_HomeButton2);
lv_obj_set_width( ui_LabelMenu4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelMenu4, LV_SIZE_CONTENT);   /// 0
lv_obj_set_align( ui_LabelMenu4, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelMenu4,"Menu");
lv_obj_set_style_text_color(ui_LabelMenu4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelMenu4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_LabelMenu4, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelMenu4, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DropdownUpdate = lv_dropdown_create(ui_Update);
lv_dropdown_set_options( ui_DropdownUpdate, "No fOS update was found" );
lv_obj_set_width( ui_DropdownUpdate, 567);
lv_obj_set_height( ui_DropdownUpdate, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_DropdownUpdate, -91 );
lv_obj_set_y( ui_DropdownUpdate, -80 );
lv_obj_set_align( ui_DropdownUpdate, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_DropdownUpdate, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_text_font(ui_DropdownUpdate, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(ui_DropdownUpdate, &lv_font_montserrat_20, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(lv_dropdown_get_list(ui_DropdownUpdate), &lv_font_montserrat_20,  LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(lv_dropdown_get_list(ui_DropdownUpdate), &lv_font_montserrat_20,  LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_ButtonInstallUpdate = lv_btn_create(ui_Update);
lv_obj_set_width( ui_ButtonInstallUpdate, 164);
lv_obj_set_height( ui_ButtonInstallUpdate, 46);
lv_obj_set_x( ui_ButtonInstallUpdate, 287 );
lv_obj_set_y( ui_ButtonInstallUpdate, -80 );
lv_obj_set_align( ui_ButtonInstallUpdate, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonInstallUpdate, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonInstallUpdate, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ButtonInstallUpdate, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ButtonInstallUpdate, lv_color_hex(0xE8210B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonInstallUpdate, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelInstallUpdate = lv_label_create(ui_ButtonInstallUpdate);
lv_obj_set_width( ui_LabelInstallUpdate, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelInstallUpdate, LV_SIZE_CONTENT);   /// 0
lv_obj_set_align( ui_LabelInstallUpdate, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelInstallUpdate,"Install");
lv_label_set_recolor(ui_LabelInstallUpdate,"true");
lv_obj_set_style_text_color(ui_LabelInstallUpdate, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelInstallUpdate, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_LabelInstallUpdate, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelInstallUpdate, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_InstallProgressBar = lv_bar_create(ui_Update);
lv_obj_set_width( ui_InstallProgressBar, 743);
lv_obj_set_height( ui_InstallProgressBar, 15);
lv_obj_set_x( ui_InstallProgressBar, 0 );
lv_obj_set_y( ui_InstallProgressBar, -14 );
lv_obj_set_align( ui_InstallProgressBar, LV_ALIGN_CENTER );

ui_DowngradeInfo = lv_label_create(ui_Update);
lv_obj_set_width( ui_DowngradeInfo, 743);
lv_obj_set_height( ui_DowngradeInfo, 54);
lv_obj_set_x( ui_DowngradeInfo, 0 );
lv_obj_set_y( ui_DowngradeInfo, 199 );
lv_obj_set_align( ui_DowngradeInfo, LV_ALIGN_CENTER );
lv_label_set_text(ui_DowngradeInfo,"Please note that when downgrading, files on the SD card may be in the wrong location or may not yet be supported by the old version.");
lv_obj_set_style_text_font(ui_DowngradeInfo, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_HomeButton2, ui_event_HomeButton2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonInstallUpdate, ui_event_ButtonInstallUpdate, LV_EVENT_ALL, NULL);
uic_DropdownUpdate = ui_DropdownUpdate;
uic_InstallProgressBar = ui_InstallProgressBar;

}

void ui_Update_screen_destroy(void)
{
   if (ui_Update) lv_obj_del(ui_Update);

// NULL screen variables
ui_Update= NULL;
ui_HomeButton2= NULL;
ui_LabelMenu4= NULL;
uic_DropdownUpdate= NULL;
ui_DropdownUpdate= NULL;
ui_ButtonInstallUpdate= NULL;
ui_LabelInstallUpdate= NULL;
uic_InstallProgressBar= NULL;
ui_InstallProgressBar= NULL;
ui_DowngradeInfo= NULL;

}
