// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: lvgl_test

#ifndef UI_EMAIL_H
#define UI_EMAIL_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Email
extern void ui_Email_screen_init(void);
extern void ui_Email_screen_destroy(void);
extern lv_obj_t *ui_Email;
extern void ui_event_EmailSelect( lv_event_t * e);
extern lv_obj_t *ui_EmailSelect;
extern lv_obj_t *ui_EmailSelectLabel;
extern void ui_event_NewEmail( lv_event_t * e);
extern lv_obj_t *ui_NewEmail;
extern lv_obj_t *ui_NewEmailLabel;
extern lv_obj_t *ui_TabView1;
extern lv_obj_t *ui_TabPageInbox;
extern lv_obj_t *ui_EmailRollerInbox;
extern lv_obj_t *ui_TabPageOutgoing;
extern lv_obj_t *ui_EmailRollerOutgoing;
extern lv_obj_t *ui_EmailMessageContainer;
extern void ui_event_BackFromEmailShow( lv_event_t * e);
extern lv_obj_t *ui_BackFromEmailShow;
extern lv_obj_t *ui_BackFromEmailShowLabel;
extern lv_obj_t *ui_EmailNameLabel;
extern lv_obj_t *ui_EmailSubjectLabel;
extern lv_obj_t *ui_EmailMessageLabel;
extern lv_obj_t *ui_NewEmailContainer;
extern void ui_event_BackFromNewEmail( lv_event_t * e);
extern lv_obj_t *ui_BackFromNewEmail;
extern lv_obj_t *ui_BackFromNewEmailLabel;
extern void ui_event_EmailSend( lv_event_t * e);
extern lv_obj_t *ui_EmailSend;
extern void ui_event_EmailSendLabel( lv_event_t * e);
extern lv_obj_t *ui_EmailSendLabel;
extern lv_obj_t *ui_NewEmailKeyboard;
extern lv_obj_t *ui_EmailAddressTextArea;
extern lv_obj_t *ui_SubjectTextArea;
extern lv_obj_t *ui_MessageTextArea;
// CUSTOM VARIABLES
extern lv_obj_t *uic_EmailRollerInbox;
extern lv_obj_t *uic_EmailRollerOutgoing;
extern lv_obj_t *uic_EmailMessageContainer;
extern lv_obj_t *uic_EmailNameLabel;
extern lv_obj_t *uic_EmailSubjectLabel;
extern lv_obj_t *uic_EmailMessageLabel;
extern lv_obj_t *uic_NewEmailContainer;
extern lv_obj_t *uic_NewEmailKeyboard;
extern lv_obj_t *uic_EmailAddressTextArea;
extern lv_obj_t *uic_SubjectTextArea;
extern lv_obj_t *uic_MessageTextArea1;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
