// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: lvgl_test

#include "ui.h"

lv_obj_t *uic_MessageTextArea1;
lv_obj_t *uic_SubjectTextArea;
lv_obj_t *uic_EmailAddressTextArea;
lv_obj_t *uic_NewEmailKeyboard;
lv_obj_t *uic_NewEmailContainer;
lv_obj_t *uic_EmailMessageLabel;
lv_obj_t *uic_EmailSubjectLabel;
lv_obj_t *uic_EmailNameLabel;
lv_obj_t *uic_EmailMessageContainer;
lv_obj_t *uic_EmailRollerInbox;
lv_obj_t *uic_EmailRollerOutgoing;
lv_obj_t *ui_Email = NULL;lv_obj_t *ui_EmailSelect = NULL;lv_obj_t *ui_EmailSelectLabel = NULL;lv_obj_t *ui_NewEmail = NULL;lv_obj_t *ui_NewEmailLabel = NULL;lv_obj_t *ui_TabView1 = NULL;lv_obj_t *ui_TabPageInbox = NULL;lv_obj_t *ui_EmailRollerInbox = NULL;lv_obj_t *ui_TabPageOutgoing = NULL;lv_obj_t *ui_EmailRollerOutgoing = NULL;lv_obj_t *ui_EmailMessageContainer = NULL;lv_obj_t *ui_BackFromEmailShow = NULL;lv_obj_t *ui_BackFromEmailShowLabel = NULL;lv_obj_t *ui_EmailNameLabel = NULL;lv_obj_t *ui_EmailSubjectLabel = NULL;lv_obj_t *ui_EmailMessageScrollContainer = NULL;lv_obj_t *ui_EmailMessageLabel = NULL;lv_obj_t *ui_NewEmailContainer = NULL;lv_obj_t *ui_BackFromNewEmail = NULL;lv_obj_t *ui_BackFromNewEmailLabel = NULL;lv_obj_t *ui_EmailSend = NULL;lv_obj_t *ui_EmailSendLabel = NULL;lv_obj_t *ui_NewEmailKeyboard = NULL;lv_obj_t *ui_EmailAddressTextArea = NULL;lv_obj_t *ui_SubjectTextArea = NULL;lv_obj_t *ui_MessageTextArea = NULL;
// event funtions
void ui_event_EmailSelect( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_EmailMessageContainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

void ui_event_NewEmail( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_NewEmailContainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

void ui_event_BackFromEmailShow( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_EmailMessageContainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_BackFromNewEmail( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_NewEmailContainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_EmailSend( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_EmailMessageContainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

void ui_event_EmailSendLabel( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      SendEmail( e );
}
}

// build funtions

void ui_Email_screen_init(void)
{
ui_Email = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Email, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_EmailSelect = lv_btn_create(ui_Email);
lv_obj_set_width( ui_EmailSelect, 119);
lv_obj_set_height( ui_EmailSelect, 50);
lv_obj_set_x( ui_EmailSelect, 325 );
lv_obj_set_y( ui_EmailSelect, -210 );
lv_obj_set_align( ui_EmailSelect, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_EmailSelect, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_EmailSelect, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_EmailSelect, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_EmailSelect, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_MainTheme);
ui_object_set_themeable_style_property(ui_EmailSelect, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_MainTheme);

ui_EmailSelectLabel = lv_label_create(ui_EmailSelect);
lv_obj_set_width( ui_EmailSelectLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_EmailSelectLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_EmailSelectLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_EmailSelectLabel,"Select");
lv_obj_set_style_text_color(ui_EmailSelectLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_EmailSelectLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_EmailSelectLabel, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_NewEmail = lv_btn_create(ui_Email);
lv_obj_set_width( ui_NewEmail, 154);
lv_obj_set_height( ui_NewEmail, 50);
lv_obj_set_x( ui_NewEmail, 180 );
lv_obj_set_y( ui_NewEmail, -209 );
lv_obj_set_align( ui_NewEmail, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_NewEmail, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_NewEmail, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_NewEmail, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_NewEmail, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_MainTheme);
ui_object_set_themeable_style_property(ui_NewEmail, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_MainTheme);

ui_NewEmailLabel = lv_label_create(ui_NewEmail);
lv_obj_set_width( ui_NewEmailLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_NewEmailLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_NewEmailLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_NewEmailLabel,"New Email");
lv_obj_set_style_text_color(ui_NewEmailLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_NewEmailLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_NewEmailLabel, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TabView1 = lv_tabview_create(ui_Email, LV_DIR_TOP, 50);
lv_obj_set_width( ui_TabView1, 800);
lv_obj_set_height( ui_TabView1, 415);
lv_obj_set_x( ui_TabView1, 0 );
lv_obj_set_y( ui_TabView1, 32 );
lv_obj_set_align( ui_TabView1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_TabView1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_set_style_text_font(lv_tabview_get_tab_btns(ui_TabView1), &lv_font_montserrat_24,  LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_TabView1), LV_OPA_TRANSP, LV_PART_ITEMS| LV_STATE_CHECKED);
lv_obj_set_style_border_side(lv_tabview_get_tab_btns(ui_TabView1), LV_BORDER_SIDE_BOTTOM, LV_PART_ITEMS| LV_STATE_CHECKED);
lv_obj_set_style_border_width(lv_tabview_get_tab_btns(ui_TabView1), 4, LV_PART_ITEMS| LV_STATE_CHECKED);
ui_object_set_themeable_style_property(lv_tabview_get_tab_btns(ui_TabView1), LV_PART_ITEMS| LV_STATE_CHECKED, LV_STYLE_TEXT_COLOR, _ui_theme_color_MainTheme);
ui_object_set_themeable_style_property(lv_tabview_get_tab_btns(ui_TabView1), LV_PART_ITEMS| LV_STATE_CHECKED, LV_STYLE_TEXT_OPA, _ui_theme_alpha_MainTheme);
ui_object_set_themeable_style_property(lv_tabview_get_tab_btns(ui_TabView1), LV_PART_ITEMS| LV_STATE_CHECKED, LV_STYLE_BORDER_COLOR, _ui_theme_color_MainTheme);
ui_object_set_themeable_style_property(lv_tabview_get_tab_btns(ui_TabView1), LV_PART_ITEMS| LV_STATE_CHECKED, LV_STYLE_BORDER_OPA, _ui_theme_alpha_MainTheme);

ui_TabPageInbox = lv_tabview_add_tab(ui_TabView1, "Inbox");

ui_EmailRollerInbox = lv_roller_create(ui_TabPageInbox);
lv_roller_set_options( ui_EmailRollerInbox, "17.02.26 18:05 | example@example.com | Subject\n15.01.26 12:34 | test@example.com | test\n", LV_ROLLER_MODE_NORMAL );
lv_obj_set_width( ui_EmailRollerInbox, 760);
lv_obj_set_height( ui_EmailRollerInbox, 325);
lv_obj_set_align( ui_EmailRollerInbox, LV_ALIGN_CENTER );
lv_obj_set_style_text_font(ui_EmailRollerInbox, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(ui_EmailRollerInbox, &lv_font_montserrat_20, LV_PART_SELECTED| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_EmailRollerInbox, LV_PART_SELECTED| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_MainTheme);
ui_object_set_themeable_style_property(ui_EmailRollerInbox, LV_PART_SELECTED| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_MainTheme);

ui_TabPageOutgoing = lv_tabview_add_tab(ui_TabView1, "Outgoing");

ui_EmailRollerOutgoing = lv_roller_create(ui_TabPageOutgoing);
lv_roller_set_options( ui_EmailRollerOutgoing, "17.02.26 18:05 | example@example.com | Subject\n15.01.26 12:34 | test@example.com | test\n", LV_ROLLER_MODE_NORMAL );
lv_obj_set_width( ui_EmailRollerOutgoing, 760);
lv_obj_set_height( ui_EmailRollerOutgoing, 325);
lv_obj_set_align( ui_EmailRollerOutgoing, LV_ALIGN_CENTER );
lv_obj_set_style_text_font(ui_EmailRollerOutgoing, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(ui_EmailRollerOutgoing, &lv_font_montserrat_20, LV_PART_SELECTED| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_EmailRollerOutgoing, LV_PART_SELECTED| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_MainTheme);
ui_object_set_themeable_style_property(ui_EmailRollerOutgoing, LV_PART_SELECTED| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_MainTheme);

ui_EmailMessageContainer = lv_obj_create(ui_Email);
lv_obj_remove_style_all(ui_EmailMessageContainer);
lv_obj_set_width( ui_EmailMessageContainer, 800);
lv_obj_set_height( ui_EmailMessageContainer, 480);
lv_obj_set_align( ui_EmailMessageContainer, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_EmailMessageContainer, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_EmailMessageContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_EmailMessageContainer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_EmailMessageContainer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BackFromEmailShow = lv_btn_create(ui_EmailMessageContainer);
lv_obj_set_width( ui_BackFromEmailShow, 119);
lv_obj_set_height( ui_BackFromEmailShow, 50);
lv_obj_set_x( ui_BackFromEmailShow, -225 );
lv_obj_set_y( ui_BackFromEmailShow, -210 );
lv_obj_set_align( ui_BackFromEmailShow, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BackFromEmailShow, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BackFromEmailShow, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_BackFromEmailShow, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_BackFromEmailShow, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_MainTheme);
ui_object_set_themeable_style_property(ui_BackFromEmailShow, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_MainTheme);

ui_BackFromEmailShowLabel = lv_label_create(ui_BackFromEmailShow);
lv_obj_set_width( ui_BackFromEmailShowLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BackFromEmailShowLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_BackFromEmailShowLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_BackFromEmailShowLabel,"< Back");
lv_obj_set_style_text_color(ui_BackFromEmailShowLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BackFromEmailShowLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_BackFromEmailShowLabel, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_EmailNameLabel = lv_label_create(ui_EmailMessageContainer);
lv_obj_set_width( ui_EmailNameLabel, 760);
lv_obj_set_height( ui_EmailNameLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_EmailNameLabel, 0 );
lv_obj_set_y( ui_EmailNameLabel, -156 );
lv_obj_set_align( ui_EmailNameLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_EmailNameLabel,"example@examle.com");
lv_obj_set_style_text_align(ui_EmailNameLabel, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_EmailNameLabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_EmailSubjectLabel = lv_label_create(ui_EmailMessageContainer);
lv_obj_set_width( ui_EmailSubjectLabel, 760);
lv_obj_set_height( ui_EmailSubjectLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_EmailSubjectLabel, 0 );
lv_obj_set_y( ui_EmailSubjectLabel, -121 );
lv_obj_set_align( ui_EmailSubjectLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_EmailSubjectLabel,"Subject");
lv_obj_set_style_text_font(ui_EmailSubjectLabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_EmailMessageScrollContainer = lv_obj_create(ui_EmailMessageContainer);
lv_obj_remove_style_all(ui_EmailMessageScrollContainer);
lv_obj_set_width( ui_EmailMessageScrollContainer, 760);
lv_obj_set_height( ui_EmailMessageScrollContainer, 311);
lv_obj_set_x( ui_EmailMessageScrollContainer, 0 );
lv_obj_set_y( ui_EmailMessageScrollContainer, 64 );
lv_obj_set_align( ui_EmailMessageScrollContainer, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_EmailMessageScrollContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );
lv_obj_set_scroll_dir(ui_EmailMessageScrollContainer, LV_DIR_VER);
lv_obj_set_scrollbar_mode(ui_EmailMessageScrollContainer, LV_SCROLLBAR_MODE_AUTO);
lv_obj_set_style_pad_all(ui_EmailMessageScrollContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_bg_opa(ui_EmailMessageScrollContainer, LV_OPA_TRANSP, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_EmailMessageScrollContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_width(ui_EmailMessageScrollContainer, 6, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_EmailMessageScrollContainer, LV_PART_SCROLLBAR | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_MainTheme);
ui_object_set_themeable_style_property(ui_EmailMessageScrollContainer, LV_PART_SCROLLBAR | LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_MainTheme);

ui_EmailMessageLabel = lv_label_create(ui_EmailMessageScrollContainer);
lv_obj_set_width( ui_EmailMessageLabel, 744);
lv_obj_set_height( ui_EmailMessageLabel, LV_SIZE_CONTENT);
lv_obj_set_x( ui_EmailMessageLabel, 0 );
lv_obj_set_y( ui_EmailMessageLabel, 0 );
lv_obj_set_align( ui_EmailMessageLabel, LV_ALIGN_TOP_LEFT );
lv_label_set_long_mode(ui_EmailMessageLabel, LV_LABEL_LONG_WRAP);
lv_label_set_text(ui_EmailMessageLabel,"Hello World! ");
lv_obj_set_style_text_font(ui_EmailMessageLabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_NewEmailContainer = lv_obj_create(ui_Email);
lv_obj_remove_style_all(ui_NewEmailContainer);
lv_obj_set_width( ui_NewEmailContainer, 800);
lv_obj_set_height( ui_NewEmailContainer, 480);
lv_obj_set_align( ui_NewEmailContainer, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_NewEmailContainer, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_NewEmailContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_NewEmailContainer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_NewEmailContainer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BackFromNewEmail = lv_btn_create(ui_NewEmailContainer);
lv_obj_set_width( ui_BackFromNewEmail, 119);
lv_obj_set_height( ui_BackFromNewEmail, 50);
lv_obj_set_x( ui_BackFromNewEmail, -225 );
lv_obj_set_y( ui_BackFromNewEmail, -210 );
lv_obj_set_align( ui_BackFromNewEmail, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BackFromNewEmail, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BackFromNewEmail, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_BackFromNewEmail, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_BackFromNewEmail, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_MainTheme);
ui_object_set_themeable_style_property(ui_BackFromNewEmail, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_MainTheme);

ui_BackFromNewEmailLabel = lv_label_create(ui_BackFromNewEmail);
lv_obj_set_width( ui_BackFromNewEmailLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BackFromNewEmailLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_BackFromNewEmailLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_BackFromNewEmailLabel,"< Back");
lv_obj_set_style_text_color(ui_BackFromNewEmailLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BackFromNewEmailLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_BackFromNewEmailLabel, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_EmailSend = lv_btn_create(ui_NewEmailContainer);
lv_obj_set_width( ui_EmailSend, 119);
lv_obj_set_height( ui_EmailSend, 50);
lv_obj_set_x( ui_EmailSend, 325 );
lv_obj_set_y( ui_EmailSend, -210 );
lv_obj_set_align( ui_EmailSend, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_EmailSend, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_EmailSend, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_EmailSend, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_EmailSend, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_MainTheme);
ui_object_set_themeable_style_property(ui_EmailSend, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_MainTheme);

ui_EmailSendLabel = lv_label_create(ui_EmailSend);
lv_obj_set_width( ui_EmailSendLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_EmailSendLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_EmailSendLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_EmailSendLabel,"Send");
lv_obj_set_style_text_color(ui_EmailSendLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_EmailSendLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_EmailSendLabel, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_NewEmailKeyboard = lv_keyboard_create(ui_NewEmailContainer);
lv_obj_set_width( ui_NewEmailKeyboard, 800);
lv_obj_set_height( ui_NewEmailKeyboard, 197);
lv_obj_set_x( ui_NewEmailKeyboard, 0 );
lv_obj_set_y( ui_NewEmailKeyboard, 141 );
lv_obj_set_align( ui_NewEmailKeyboard, LV_ALIGN_CENTER );

ui_EmailAddressTextArea = lv_textarea_create(ui_NewEmailContainer);
lv_obj_set_width( ui_EmailAddressTextArea, 769);
lv_obj_set_height( ui_EmailAddressTextArea, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_EmailAddressTextArea, 0 );
lv_obj_set_y( ui_EmailAddressTextArea, -153 );
lv_obj_set_align( ui_EmailAddressTextArea, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_EmailAddressTextArea,"Email Address ...");
lv_textarea_set_one_line(ui_EmailAddressTextArea,true);
lv_obj_set_style_text_font(ui_EmailAddressTextArea, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_EmailAddressTextArea, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_COLOR, _ui_theme_color_MainTheme);

ui_SubjectTextArea = lv_textarea_create(ui_NewEmailContainer);
lv_obj_set_width( ui_SubjectTextArea, 769);
lv_obj_set_height( ui_SubjectTextArea, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SubjectTextArea, 0 );
lv_obj_set_y( ui_SubjectTextArea, -98 );
lv_obj_set_align( ui_SubjectTextArea, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_SubjectTextArea,"Subject ...");
lv_textarea_set_one_line(ui_SubjectTextArea,true);
lv_obj_set_style_text_font(ui_SubjectTextArea, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_SubjectTextArea, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_COLOR, _ui_theme_color_MainTheme);

ui_MessageTextArea = lv_textarea_create(ui_NewEmailContainer);
lv_obj_set_width( ui_MessageTextArea, 769);
lv_obj_set_height( ui_MessageTextArea, 100);
lv_obj_set_x( ui_MessageTextArea, 0 );
lv_obj_set_y( ui_MessageTextArea, -16 );
lv_obj_set_align( ui_MessageTextArea, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_MessageTextArea,"Your message ...");
lv_obj_set_style_text_font(ui_MessageTextArea, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_MessageTextArea, LV_PART_MAIN| LV_STATE_FOCUSED, LV_STYLE_BORDER_COLOR, _ui_theme_color_MainTheme);

lv_obj_add_event_cb(ui_EmailSelect, ui_event_EmailSelect, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_NewEmail, ui_event_NewEmail, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BackFromEmailShow, ui_event_BackFromEmailShow, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BackFromNewEmail, ui_event_BackFromNewEmail, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_EmailSendLabel, ui_event_EmailSendLabel, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_EmailSend, ui_event_EmailSend, LV_EVENT_ALL, NULL);
lv_keyboard_set_textarea(ui_NewEmailKeyboard,ui_MessageTextArea);
uic_EmailRollerInbox = ui_EmailRollerInbox;
uic_EmailRollerOutgoing = ui_EmailRollerOutgoing;
uic_EmailMessageContainer = ui_EmailMessageContainer;
uic_EmailNameLabel = ui_EmailNameLabel;
uic_EmailSubjectLabel = ui_EmailSubjectLabel;
uic_EmailMessageLabel = ui_EmailMessageLabel;
uic_NewEmailContainer = ui_NewEmailContainer;
uic_NewEmailKeyboard = ui_NewEmailKeyboard;
uic_EmailAddressTextArea = ui_EmailAddressTextArea;
uic_SubjectTextArea = ui_SubjectTextArea;
uic_MessageTextArea1 = ui_MessageTextArea;

}

void ui_Email_screen_destroy(void)
{
   if (ui_Email) lv_obj_del(ui_Email);

// NULL screen variables
ui_Email= NULL;
ui_EmailSelect= NULL;
ui_EmailSelectLabel= NULL;
ui_NewEmail= NULL;
ui_NewEmailLabel= NULL;
ui_TabView1= NULL;
ui_TabPageInbox= NULL;
uic_EmailRollerInbox= NULL;
ui_EmailRollerInbox= NULL;
ui_TabPageOutgoing= NULL;
uic_EmailRollerOutgoing= NULL;
ui_EmailRollerOutgoing= NULL;
uic_EmailMessageContainer= NULL;
ui_EmailMessageContainer= NULL;
ui_BackFromEmailShow= NULL;
ui_BackFromEmailShowLabel= NULL;
uic_EmailNameLabel= NULL;
ui_EmailNameLabel= NULL;
uic_EmailSubjectLabel= NULL;
ui_EmailSubjectLabel= NULL;
ui_EmailMessageScrollContainer= NULL;
uic_EmailMessageLabel= NULL;
ui_EmailMessageLabel= NULL;
uic_NewEmailContainer= NULL;
ui_NewEmailContainer= NULL;
ui_BackFromNewEmail= NULL;
ui_BackFromNewEmailLabel= NULL;
ui_EmailSend= NULL;
ui_EmailSendLabel= NULL;
uic_NewEmailKeyboard= NULL;
ui_NewEmailKeyboard= NULL;
uic_EmailAddressTextArea= NULL;
ui_EmailAddressTextArea= NULL;
uic_SubjectTextArea= NULL;
ui_SubjectTextArea= NULL;
uic_MessageTextArea1= NULL;
ui_MessageTextArea= NULL;

}
