// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: fOS_3

#include "ui.h"
#include "ota_recovery_manager.h"

void SaveTimeZone_Data(lv_event_t * e);
void SaveDisplaySettings_Data(lv_event_t * e);
void StorageManagerSelect_Data(lv_event_t * e);
void ResetStorageManagerToRoot_Data(void);
void UnloadApp_Data(lv_event_t * e);
void SaveWifiConnection_Data(lv_event_t * e);
void runWifiConnection_Data(lv_event_t * e);
void StopWifiConnection_Data(lv_event_t * e);
void storageManagerNewFolderData(lv_event_t * e);

void updateSystemInfo(lv_event_t * e)
{
	updateSystemInfoData();
}

void SaveWifiConnection(lv_event_t * e)
{
	SaveWifiConnection_Data(e);
}

void runWifiConnection(lv_event_t * e)
{
	runWifiConnection_Data(e);
}

void StopWifiConnection(lv_event_t * e)
{
	StopWifiConnection_Data(e);
}

void SaveTimeZone(lv_event_t * e)
{
	SaveTimeZone_Data( e );
}

void SaveDisplaySettings(lv_event_t * e)
{
	SaveDisplaySettings_Data( e );
}

void BackToHomeFromFileManager(lv_event_t * e)
{
	if (lv_event_get_code(e) == LV_EVENT_CLICKED) {
		ResetStorageManagerToRoot_Data();
	}
}

void StorageManagerNewFolder(lv_event_t * e)
{
	storageManagerNewFolderData(e);
}

void StorageManagerSelect(lv_event_t * e)
{
	if (lv_event_get_code(e) == LV_EVENT_CLICKED) {
		StorageManagerSelect_Data(e);
	}
}

void DeleteFileSelected(lv_event_t * e)
{
	if (lv_event_get_code(e) == LV_EVENT_CLICKED) {
        deleteSelectedFile();
    }
}

void InstallUpdate(lv_event_t * e)
{
	OTARecovery_InstallUpdateEvent(e);
}

void UnloadApp(lv_event_t * e)
{
	if (lv_event_get_code(e) == LV_EVENT_CLICKED) {
		UnloadApp_Data(e);
	}
}
