// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: fOS_3

#include "ui.h"

lv_obj_t *uic_KeyboardFolder;
lv_obj_t *uic_ContainerReallyDelete;
lv_obj_t *uic_LabelSDInfo;
lv_obj_t *uic_BarSD;
lv_obj_t *uic_FileRollerFileManager;
lv_obj_t *uic_LabelDeleteFile;
lv_obj_t *uic_ButtonDeleteFile;
lv_obj_t *ui_ScreenStorageManager = NULL;lv_obj_t *ui_HomeButton1 = NULL;lv_obj_t *ui_LabelMenu2 = NULL;lv_obj_t *ui_ButtonNewFolder = NULL;lv_obj_t *ui_LabelNewFolder = NULL;lv_obj_t *ui_ButtonSelect = NULL;lv_obj_t *ui_LabelMenu3 = NULL;lv_obj_t *ui_ButtonDeleteFile = NULL;lv_obj_t *ui_LabelDeleteFile = NULL;lv_obj_t *ui_FileRollerFileManager = NULL;lv_obj_t *ui_BarSD = NULL;lv_obj_t *ui_LabelSDInfo = NULL;lv_obj_t *ui_ContainerReallyDelete = NULL;lv_obj_t *ui_ButtonDeleteFile1 = NULL;lv_obj_t *ui_LabelDeleteFile1 = NULL;lv_obj_t *ui_ButtonCancel = NULL;lv_obj_t *ui_LabelCancel = NULL;lv_obj_t *ui_KeyboardFolder = NULL;
// event funtions
void ui_event_HomeButton1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenSettings, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenSettings_screen_init);
}
if ( event_code == LV_EVENT_CLICKED) {
      BackToHomeFromFileManager( e );
}
}

void ui_event_ButtonNewFolder( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      StorageManagerNewFolder( e );
      _ui_flag_modify( ui_KeyboardFolder, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

void ui_event_ButtonSelect( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      StorageManagerSelect( e );
}
}

void ui_event_ButtonDeleteFile( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_ContainerReallyDelete, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

void ui_event_LabelDeleteFile( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      DeleteFileSelected( e );
}
}

void ui_event_ButtonDeleteFile1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      DeleteFileSelected( e );
}
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_ContainerReallyDelete, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_LabelDeleteFile1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      DeleteFileSelected( e );
}
}

void ui_event_ButtonCancel( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_ContainerReallyDelete, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

// build funtions

void ui_ScreenStorageManager_screen_init(void)
{
ui_ScreenStorageManager = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenStorageManager, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_text_font(ui_ScreenStorageManager, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HomeButton1 = lv_btn_create(ui_ScreenStorageManager);
lv_obj_set_width( ui_HomeButton1, 100);
lv_obj_set_height( ui_HomeButton1, 50);
lv_obj_set_x( ui_HomeButton1, -340 );
lv_obj_set_y( ui_HomeButton1, -210 );
lv_obj_set_align( ui_HomeButton1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_HomeButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_HomeButton1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_HomeButton1, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_HomeButton1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_MainTheme);
ui_object_set_themeable_style_property(ui_HomeButton1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_MainTheme);

ui_LabelMenu2 = lv_label_create(ui_HomeButton1);
lv_obj_set_width( ui_LabelMenu2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelMenu2, LV_SIZE_CONTENT);   /// 0
lv_obj_set_align( ui_LabelMenu2, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelMenu2,"Menu");
lv_obj_set_style_text_color(ui_LabelMenu2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelMenu2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_LabelMenu2, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelMenu2, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonNewFolder = lv_btn_create(ui_ScreenStorageManager);
lv_obj_set_width( ui_ButtonNewFolder, 169);
lv_obj_set_height( ui_ButtonNewFolder, 50);
lv_obj_set_x( ui_ButtonNewFolder, 43 );
lv_obj_set_y( ui_ButtonNewFolder, -210 );
lv_obj_set_align( ui_ButtonNewFolder, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonNewFolder, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonNewFolder, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ButtonNewFolder, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_ButtonNewFolder, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_MainTheme);
ui_object_set_themeable_style_property(ui_ButtonNewFolder, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_MainTheme);

ui_LabelNewFolder = lv_label_create(ui_ButtonNewFolder);
lv_obj_set_width( ui_LabelNewFolder, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelNewFolder, LV_SIZE_CONTENT);   /// 0
lv_obj_set_align( ui_LabelNewFolder, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelNewFolder,"New Folder");
lv_obj_set_style_text_color(ui_LabelNewFolder, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelNewFolder, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_LabelNewFolder, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelNewFolder, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonSelect = lv_btn_create(ui_ScreenStorageManager);
lv_obj_set_width( ui_ButtonSelect, 122);
lv_obj_set_height( ui_ButtonSelect, 50);
lv_obj_set_x( ui_ButtonSelect, 198 );
lv_obj_set_y( ui_ButtonSelect, -210 );
lv_obj_set_align( ui_ButtonSelect, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonSelect, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonSelect, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ButtonSelect, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_ButtonSelect, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_MainTheme);
ui_object_set_themeable_style_property(ui_ButtonSelect, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_MainTheme);

ui_LabelMenu3 = lv_label_create(ui_ButtonSelect);
lv_obj_set_width( ui_LabelMenu3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelMenu3, LV_SIZE_CONTENT);   /// 0
lv_obj_set_align( ui_LabelMenu3, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelMenu3,"Select");
lv_obj_set_style_text_color(ui_LabelMenu3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelMenu3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_LabelMenu3, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelMenu3, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonDeleteFile = lv_btn_create(ui_ScreenStorageManager);
lv_obj_set_width( ui_ButtonDeleteFile, 122);
lv_obj_set_height( ui_ButtonDeleteFile, 50);
lv_obj_set_x( ui_ButtonDeleteFile, 329 );
lv_obj_set_y( ui_ButtonDeleteFile, -210 );
lv_obj_set_align( ui_ButtonDeleteFile, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonDeleteFile, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonDeleteFile, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ButtonDeleteFile, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ButtonDeleteFile, lv_color_hex(0xE8210B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonDeleteFile, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelDeleteFile = lv_label_create(ui_ButtonDeleteFile);
lv_obj_set_width( ui_LabelDeleteFile, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelDeleteFile, LV_SIZE_CONTENT);   /// 0
lv_obj_set_align( ui_LabelDeleteFile, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelDeleteFile,"Delete");
lv_obj_set_style_text_color(ui_LabelDeleteFile, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelDeleteFile, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_LabelDeleteFile, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelDeleteFile, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FileRollerFileManager = lv_roller_create(ui_ScreenStorageManager);
lv_roller_set_options( ui_FileRollerFileManager, "No file found", LV_ROLLER_MODE_NORMAL );
lv_obj_set_width( ui_FileRollerFileManager, 780);
lv_obj_set_height( ui_FileRollerFileManager, 260);
lv_obj_set_x( ui_FileRollerFileManager, 0 );
lv_obj_set_y( ui_FileRollerFileManager, -45 );
lv_obj_set_align( ui_FileRollerFileManager, LV_ALIGN_CENTER );
lv_obj_set_style_text_align(ui_FileRollerFileManager, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_FileRollerFileManager, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_object_set_themeable_style_property(ui_FileRollerFileManager, LV_PART_SELECTED| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_MainTheme);
ui_object_set_themeable_style_property(ui_FileRollerFileManager, LV_PART_SELECTED| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_MainTheme);

ui_BarSD = lv_bar_create(ui_ScreenStorageManager);
lv_obj_set_width( ui_BarSD, 780);
lv_obj_set_height( ui_BarSD, 34);
lv_obj_set_x( ui_BarSD, 0 );
lv_obj_set_y( ui_BarSD, 205 );
lv_obj_set_align( ui_BarSD, LV_ALIGN_CENTER );

ui_object_set_themeable_style_property(ui_BarSD, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_MainTheme);
ui_object_set_themeable_style_property(ui_BarSD, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_MainTheme);

ui_LabelSDInfo = lv_label_create(ui_ScreenStorageManager);
lv_obj_set_width( ui_LabelSDInfo, 775);
lv_obj_set_height( ui_LabelSDInfo, 75);
lv_obj_set_x( ui_LabelSDInfo, 1 );
lv_obj_set_y( ui_LabelSDInfo, 135 );
lv_obj_set_align( ui_LabelSDInfo, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelSDInfo,"No SD card detected.");
lv_obj_set_style_text_font(ui_LabelSDInfo, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ContainerReallyDelete = lv_obj_create(ui_ScreenStorageManager);
lv_obj_remove_style_all(ui_ContainerReallyDelete);
lv_obj_set_width( ui_ContainerReallyDelete, 280);
lv_obj_set_height( ui_ContainerReallyDelete, 77);
lv_obj_set_align( ui_ContainerReallyDelete, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ContainerReallyDelete, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_ContainerReallyDelete, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ContainerReallyDelete, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ContainerReallyDelete, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ContainerReallyDelete, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonDeleteFile1 = lv_btn_create(ui_ContainerReallyDelete);
lv_obj_set_width( ui_ButtonDeleteFile1, 122);
lv_obj_set_height( ui_ButtonDeleteFile1, 50);
lv_obj_set_x( ui_ButtonDeleteFile1, 65 );
lv_obj_set_y( ui_ButtonDeleteFile1, 1 );
lv_obj_set_align( ui_ButtonDeleteFile1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonDeleteFile1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonDeleteFile1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ButtonDeleteFile1, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ButtonDeleteFile1, lv_color_hex(0xE8210B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonDeleteFile1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelDeleteFile1 = lv_label_create(ui_ButtonDeleteFile1);
lv_obj_set_width( ui_LabelDeleteFile1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelDeleteFile1, LV_SIZE_CONTENT);   /// 0
lv_obj_set_align( ui_LabelDeleteFile1, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelDeleteFile1,"Delete");
lv_obj_set_style_text_color(ui_LabelDeleteFile1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelDeleteFile1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_LabelDeleteFile1, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelDeleteFile1, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonCancel = lv_btn_create(ui_ContainerReallyDelete);
lv_obj_set_width( ui_ButtonCancel, 122);
lv_obj_set_height( ui_ButtonCancel, 50);
lv_obj_set_x( ui_ButtonCancel, -65 );
lv_obj_set_y( ui_ButtonCancel, 0 );
lv_obj_set_align( ui_ButtonCancel, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonCancel, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonCancel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ButtonCancel, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_ButtonCancel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_MainTheme);
ui_object_set_themeable_style_property(ui_ButtonCancel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_MainTheme);

ui_LabelCancel = lv_label_create(ui_ButtonCancel);
lv_obj_set_width( ui_LabelCancel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelCancel, LV_SIZE_CONTENT);   /// 0
lv_obj_set_align( ui_LabelCancel, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelCancel,"Cancel");
lv_obj_set_style_text_color(ui_LabelCancel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelCancel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_LabelCancel, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelCancel, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_KeyboardFolder = lv_keyboard_create(ui_ScreenStorageManager);
lv_obj_set_width( ui_KeyboardFolder, 793);
lv_obj_set_height( ui_KeyboardFolder, 197);
lv_obj_set_x( ui_KeyboardFolder, 0 );
lv_obj_set_y( ui_KeyboardFolder, 135 );
lv_obj_set_align( ui_KeyboardFolder, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_KeyboardFolder, LV_OBJ_FLAG_HIDDEN );   /// Flags

lv_obj_set_style_text_font(ui_KeyboardFolder, &lv_font_montserrat_20, LV_PART_ITEMS| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_HomeButton1, ui_event_HomeButton1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonNewFolder, ui_event_ButtonNewFolder, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonSelect, ui_event_ButtonSelect, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_LabelDeleteFile, ui_event_LabelDeleteFile, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonDeleteFile, ui_event_ButtonDeleteFile, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_LabelDeleteFile1, ui_event_LabelDeleteFile1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonDeleteFile1, ui_event_ButtonDeleteFile1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonCancel, ui_event_ButtonCancel, LV_EVENT_ALL, NULL);
lv_keyboard_set_textarea(ui_KeyboardFolder,ui_TextAreaWifiPassword);
uic_ButtonDeleteFile = ui_ButtonDeleteFile;
uic_LabelDeleteFile = ui_LabelDeleteFile;
uic_FileRollerFileManager = ui_FileRollerFileManager;
uic_BarSD = ui_BarSD;
uic_LabelSDInfo = ui_LabelSDInfo;
uic_ContainerReallyDelete = ui_ContainerReallyDelete;
uic_KeyboardFolder = ui_KeyboardFolder;

}

void ui_ScreenStorageManager_screen_destroy(void)
{
   if (ui_ScreenStorageManager) lv_obj_del(ui_ScreenStorageManager);

// NULL screen variables
ui_ScreenStorageManager= NULL;
ui_HomeButton1= NULL;
ui_LabelMenu2= NULL;
ui_ButtonNewFolder= NULL;
ui_LabelNewFolder= NULL;
ui_ButtonSelect= NULL;
ui_LabelMenu3= NULL;
uic_ButtonDeleteFile= NULL;
ui_ButtonDeleteFile= NULL;
uic_LabelDeleteFile= NULL;
ui_LabelDeleteFile= NULL;
uic_FileRollerFileManager= NULL;
ui_FileRollerFileManager= NULL;
uic_BarSD= NULL;
ui_BarSD= NULL;
uic_LabelSDInfo= NULL;
ui_LabelSDInfo= NULL;
uic_ContainerReallyDelete= NULL;
ui_ContainerReallyDelete= NULL;
ui_ButtonDeleteFile1= NULL;
ui_LabelDeleteFile1= NULL;
ui_ButtonCancel= NULL;
ui_LabelCancel= NULL;
uic_KeyboardFolder= NULL;
ui_KeyboardFolder= NULL;

}
