// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: fOS_3

#include "ui.h"

lv_obj_t *uic_DropdownTheme;
lv_obj_t *uic_SliderBrightness;
lv_obj_t *uic_ButtonSaveDisplay;
lv_obj_t *uic_DisplayContainer;
lv_obj_t *uic_TimeZoneManager;
lv_obj_t *uic_ButtonSaveTimeZone;
lv_obj_t *uic_TimeZoneContainer;
lv_obj_t *uic_KeyboardWifi;
lv_obj_t *uic_TextAreaWifiPassword;
lv_obj_t *uic_WifiSelectorDropdown;
lv_obj_t *uic_WifiSwitch;
lv_obj_t *uic_ButtonSaveWifi;
lv_obj_t *uic_WifiScreenContainer;
lv_obj_t *uic_ButtonSettingsGeneral;
lv_obj_t *uic_ButtonSettingsTimeZone;
lv_obj_t *uic_systemInfoLabel;
lv_obj_t *uic_ScreenSettings;
lv_obj_t *ui_ScreenSettings = NULL;lv_obj_t *ui_HomeButton = NULL;lv_obj_t *ui_LabelMenu1 = NULL;lv_obj_t *ui_LabelHardwareInformation = NULL;lv_obj_t *ui_systemInfoLabel = NULL;lv_obj_t *ui_LabelSoftwareInformationData = NULL;lv_obj_t *ui_ButtonSettingsUpdater = NULL;lv_obj_t *ui_LabelSettingsUpdater = NULL;lv_obj_t *ui_ButtonSettingsStorage = NULL;lv_obj_t *ui_LabelSettingsStorage = NULL;lv_obj_t *ui_ButtonSettingsWiFi = NULL;lv_obj_t *ui_LabelSettingsWiFi = NULL;lv_obj_t *ui_ButtonSettingsTimeZone = NULL;lv_obj_t *ui_LabelSettingsTimeZone = NULL;lv_obj_t *ui_ButtonSettingsDisplay = NULL;lv_obj_t *ui_LabelSettingsTimeZone1 = NULL;lv_obj_t *ui_WifiScreenContainer = NULL;lv_obj_t *ui_ButtonBack1 = NULL;lv_obj_t *ui_LabelBack1 = NULL;lv_obj_t *ui_ButtonSaveWifi = NULL;lv_obj_t *ui_LabelBack2 = NULL;lv_obj_t *ui_WifiSwitch = NULL;lv_obj_t *ui_LabelWifiSwitch = NULL;lv_obj_t *ui_WifiSelectorDropdown = NULL;lv_obj_t *ui_TextAreaWifiPassword = NULL;lv_obj_t *ui_KeyboardWifi = NULL;lv_obj_t *ui_TimeZoneContainer = NULL;lv_obj_t *ui_ButtonBack2 = NULL;lv_obj_t *ui_LabelBack3 = NULL;lv_obj_t *ui_ButtonSaveTimeZone = NULL;lv_obj_t *ui_LabelBack4 = NULL;lv_obj_t *ui_TimeZoneManager = NULL;lv_obj_t *ui_DisplayContainer = NULL;lv_obj_t *ui_ButtonBack3 = NULL;lv_obj_t *ui_LabelBack5 = NULL;lv_obj_t *ui_ButtonSaveDisplay = NULL;lv_obj_t *ui_LabelBack6 = NULL;lv_obj_t *ui_LabelBrightness = NULL;lv_obj_t *ui_SliderBrightness = NULL;lv_obj_t *ui_DropdownTheme = NULL;
// event funtions
void ui_event_HomeButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenHome, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenHome_screen_init);
}
}

void ui_event_ButtonSettingsUpdater( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Update, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Update_screen_init);
}
}

void ui_event_ButtonSettingsStorage( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenStorageManager, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenStorageManager_screen_init);
      StartStorageManager( e );
}
}

void ui_event_ButtonSettingsWiFi( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_WifiScreenContainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

void ui_event_ButtonSettingsTimeZone( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_TimeZoneContainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

void ui_event_ButtonSettingsDisplay( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_DisplayContainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

void ui_event_ButtonBack1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_WifiScreenContainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_ButtonSaveWifi( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      SaveWifiConnection( e );
}
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_WifiScreenContainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_WifiSwitch( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_flag_modify( ui_WifiSelectorDropdown, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_TextAreaWifiPassword, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_KeyboardWifi, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      runWifiConnection( e );
}
if ( event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_flag_modify( ui_WifiSelectorDropdown, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_TextAreaWifiPassword, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_KeyboardWifi, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      StopWifiConnection( e );
}
}

void ui_event_TextAreaWifiPassword( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_keyboard_set_target(ui_KeyboardWifi,  ui_TextAreaWifiPassword);
}
}

void ui_event_ButtonBack2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_TimeZoneContainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_ButtonSaveTimeZone( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      SaveTimeZone( e );
}
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_TimeZoneContainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_ButtonBack3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_DisplayContainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_ButtonSaveDisplay( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      SaveDisplaySettings( e );
}
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_DisplayContainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

// build funtions

void ui_ScreenSettings_screen_init(void)
{
ui_ScreenSettings = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenSettings, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_HomeButton = lv_btn_create(ui_ScreenSettings);
lv_obj_set_width( ui_HomeButton, 100);
lv_obj_set_height( ui_HomeButton, 50);
lv_obj_set_x( ui_HomeButton, -340 );
lv_obj_set_y( ui_HomeButton, -210 );
lv_obj_set_align( ui_HomeButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_HomeButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_HomeButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_HomeButton, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_HomeButton, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_MainTheme);
ui_object_set_themeable_style_property(ui_HomeButton, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_MainTheme);

ui_LabelMenu1 = lv_label_create(ui_HomeButton);
lv_obj_set_width( ui_LabelMenu1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelMenu1, LV_SIZE_CONTENT);   /// 0
lv_obj_set_align( ui_LabelMenu1, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelMenu1,"Menu");
lv_obj_set_style_text_color(ui_LabelMenu1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelMenu1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_LabelMenu1, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelMenu1, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelHardwareInformation = lv_label_create(ui_ScreenSettings);
lv_obj_set_width( ui_LabelHardwareInformation, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelHardwareInformation, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelHardwareInformation, -18 );
lv_obj_set_y( ui_LabelHardwareInformation, 86 );
lv_obj_set_align( ui_LabelHardwareInformation, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelHardwareInformation,"Hardware information:																Software information:");
lv_obj_set_style_text_font(ui_LabelHardwareInformation, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_systemInfoLabel = lv_label_create(ui_ScreenSettings);
lv_obj_set_width( ui_systemInfoLabel, 462);
lv_obj_set_height( ui_systemInfoLabel, 120);
lv_obj_set_x( ui_systemInfoLabel, -154 );
lv_obj_set_y( ui_systemInfoLabel, 165 );
lv_obj_set_align( ui_systemInfoLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_systemInfoLabel,"");
lv_obj_set_style_text_font(ui_systemInfoLabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelSoftwareInformationData = lv_label_create(ui_ScreenSettings);
lv_obj_set_width( ui_LabelSoftwareInformationData, 281);
lv_obj_set_height( ui_LabelSoftwareInformationData, 120);
lv_obj_set_x( ui_LabelSoftwareInformationData, 235 );
lv_obj_set_y( ui_LabelSoftwareInformationData, 165 );
lv_obj_set_align( ui_LabelSoftwareInformationData, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelSoftwareInformationData,"fOS version:\n3.0.0\nDeveloper: \nDevMicroCore");
lv_obj_set_style_text_font(ui_LabelSoftwareInformationData, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonSettingsUpdater = lv_btn_create(ui_ScreenSettings);
lv_obj_set_width( ui_ButtonSettingsUpdater, 190);
lv_obj_set_height( ui_ButtonSettingsUpdater, 50);
lv_obj_set_x( ui_ButtonSettingsUpdater, -295 );
lv_obj_set_y( ui_ButtonSettingsUpdater, -145 );
lv_obj_set_align( ui_ButtonSettingsUpdater, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonSettingsUpdater, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonSettingsUpdater, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ButtonSettingsUpdater, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_ButtonSettingsUpdater, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_MainTheme);
ui_object_set_themeable_style_property(ui_ButtonSettingsUpdater, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_MainTheme);

ui_LabelSettingsUpdater = lv_label_create(ui_ButtonSettingsUpdater);
lv_obj_set_width( ui_LabelSettingsUpdater, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelSettingsUpdater, LV_SIZE_CONTENT);   /// 0
lv_obj_set_align( ui_LabelSettingsUpdater, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelSettingsUpdater,"Updater");
lv_label_set_recolor(ui_LabelSettingsUpdater,"true");
lv_obj_set_style_text_color(ui_LabelSettingsUpdater, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelSettingsUpdater, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_LabelSettingsUpdater, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelSettingsUpdater, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonSettingsStorage = lv_btn_create(ui_ScreenSettings);
lv_obj_set_width( ui_ButtonSettingsStorage, 190);
lv_obj_set_height( ui_ButtonSettingsStorage, 50);
lv_obj_set_x( ui_ButtonSettingsStorage, -295 );
lv_obj_set_y( ui_ButtonSettingsStorage, -85 );
lv_obj_set_align( ui_ButtonSettingsStorage, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonSettingsStorage, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonSettingsStorage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ButtonSettingsStorage, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_ButtonSettingsStorage, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_MainTheme);
ui_object_set_themeable_style_property(ui_ButtonSettingsStorage, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_MainTheme);

ui_LabelSettingsStorage = lv_label_create(ui_ButtonSettingsStorage);
lv_obj_set_width( ui_LabelSettingsStorage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelSettingsStorage, LV_SIZE_CONTENT);   /// 0
lv_obj_set_align( ui_LabelSettingsStorage, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelSettingsStorage,"Storage");
lv_label_set_recolor(ui_LabelSettingsStorage,"true");
lv_obj_set_style_text_color(ui_LabelSettingsStorage, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelSettingsStorage, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_LabelSettingsStorage, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelSettingsStorage, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonSettingsWiFi = lv_btn_create(ui_ScreenSettings);
lv_obj_set_width( ui_ButtonSettingsWiFi, 190);
lv_obj_set_height( ui_ButtonSettingsWiFi, 50);
lv_obj_set_x( ui_ButtonSettingsWiFi, -295 );
lv_obj_set_y( ui_ButtonSettingsWiFi, -25 );
lv_obj_set_align( ui_ButtonSettingsWiFi, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonSettingsWiFi, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonSettingsWiFi, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ButtonSettingsWiFi, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_ButtonSettingsWiFi, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_MainTheme);
ui_object_set_themeable_style_property(ui_ButtonSettingsWiFi, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_MainTheme);

ui_LabelSettingsWiFi = lv_label_create(ui_ButtonSettingsWiFi);
lv_obj_set_width( ui_LabelSettingsWiFi, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelSettingsWiFi, LV_SIZE_CONTENT);   /// 0
lv_obj_set_align( ui_LabelSettingsWiFi, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelSettingsWiFi,"WI-FI Setting");
lv_obj_set_style_text_color(ui_LabelSettingsWiFi, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelSettingsWiFi, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_LabelSettingsWiFi, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelSettingsWiFi, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonSettingsTimeZone = lv_btn_create(ui_ScreenSettings);
lv_obj_set_width( ui_ButtonSettingsTimeZone, 190);
lv_obj_set_height( ui_ButtonSettingsTimeZone, 50);
lv_obj_set_x( ui_ButtonSettingsTimeZone, -295 );
lv_obj_set_y( ui_ButtonSettingsTimeZone, 35 );
lv_obj_set_align( ui_ButtonSettingsTimeZone, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonSettingsTimeZone, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonSettingsTimeZone, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ButtonSettingsTimeZone, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_ButtonSettingsTimeZone, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_MainTheme);
ui_object_set_themeable_style_property(ui_ButtonSettingsTimeZone, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_MainTheme);

ui_LabelSettingsTimeZone = lv_label_create(ui_ButtonSettingsTimeZone);
lv_obj_set_width( ui_LabelSettingsTimeZone, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelSettingsTimeZone, LV_SIZE_CONTENT);   /// 0
lv_obj_set_align( ui_LabelSettingsTimeZone, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelSettingsTimeZone,"Time Zone");
lv_obj_set_style_text_color(ui_LabelSettingsTimeZone, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelSettingsTimeZone, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_LabelSettingsTimeZone, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelSettingsTimeZone, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonSettingsDisplay = lv_btn_create(ui_ScreenSettings);
lv_obj_set_width( ui_ButtonSettingsDisplay, 190);
lv_obj_set_height( ui_ButtonSettingsDisplay, 50);
lv_obj_set_x( ui_ButtonSettingsDisplay, -92 );
lv_obj_set_y( ui_ButtonSettingsDisplay, 35 );
lv_obj_set_align( ui_ButtonSettingsDisplay, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonSettingsDisplay, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonSettingsDisplay, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ButtonSettingsDisplay, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_ButtonSettingsDisplay, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_MainTheme);
ui_object_set_themeable_style_property(ui_ButtonSettingsDisplay, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_MainTheme);

ui_LabelSettingsTimeZone1 = lv_label_create(ui_ButtonSettingsDisplay);
lv_obj_set_width( ui_LabelSettingsTimeZone1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelSettingsTimeZone1, LV_SIZE_CONTENT);   /// 0
lv_obj_set_align( ui_LabelSettingsTimeZone1, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelSettingsTimeZone1,"Display");
lv_obj_set_style_text_color(ui_LabelSettingsTimeZone1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelSettingsTimeZone1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_LabelSettingsTimeZone1, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelSettingsTimeZone1, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_WifiScreenContainer = lv_obj_create(ui_ScreenSettings);
lv_obj_remove_style_all(ui_WifiScreenContainer);
lv_obj_set_width( ui_WifiScreenContainer, 800);
lv_obj_set_height( ui_WifiScreenContainer, 480);
lv_obj_set_align( ui_WifiScreenContainer, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_WifiScreenContainer, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_WifiScreenContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_WifiScreenContainer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_WifiScreenContainer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonBack1 = lv_btn_create(ui_WifiScreenContainer);
lv_obj_set_width( ui_ButtonBack1, 143);
lv_obj_set_height( ui_ButtonBack1, 50);
lv_obj_set_x( ui_ButtonBack1, -320 );
lv_obj_set_y( ui_ButtonBack1, -210 );
lv_obj_set_align( ui_ButtonBack1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonBack1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonBack1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ButtonBack1, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_ButtonBack1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_MainTheme);
ui_object_set_themeable_style_property(ui_ButtonBack1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_MainTheme);

ui_LabelBack1 = lv_label_create(ui_ButtonBack1);
lv_obj_set_width( ui_LabelBack1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelBack1, LV_SIZE_CONTENT);   /// 0
lv_obj_set_align( ui_LabelBack1, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelBack1,"< Settings");
lv_obj_set_style_text_color(ui_LabelBack1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelBack1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_LabelBack1, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelBack1, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonSaveWifi = lv_btn_create(ui_WifiScreenContainer);
lv_obj_set_width( ui_ButtonSaveWifi, 143);
lv_obj_set_height( ui_ButtonSaveWifi, 50);
lv_obj_set_x( ui_ButtonSaveWifi, 317 );
lv_obj_set_y( ui_ButtonSaveWifi, -210 );
lv_obj_set_align( ui_ButtonSaveWifi, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonSaveWifi, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonSaveWifi, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ButtonSaveWifi, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_ButtonSaveWifi, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_MainTheme);
ui_object_set_themeable_style_property(ui_ButtonSaveWifi, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_MainTheme);

ui_LabelBack2 = lv_label_create(ui_ButtonSaveWifi);
lv_obj_set_width( ui_LabelBack2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelBack2, LV_SIZE_CONTENT);   /// 0
lv_obj_set_align( ui_LabelBack2, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelBack2,"Save Wifi");
lv_obj_set_style_text_color(ui_LabelBack2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelBack2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_LabelBack2, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelBack2, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_WifiSwitch = lv_switch_create(ui_WifiScreenContainer);
lv_obj_set_width( ui_WifiSwitch, 82);
lv_obj_set_height( ui_WifiSwitch, 40);
lv_obj_set_x( ui_WifiSwitch, -342 );
lv_obj_set_y( ui_WifiSwitch, -130 );
lv_obj_set_align( ui_WifiSwitch, LV_ALIGN_CENTER );

ui_object_set_themeable_style_property(ui_WifiSwitch, LV_PART_INDICATOR| LV_STATE_CHECKED, LV_STYLE_BG_COLOR, _ui_theme_color_MainTheme);
ui_object_set_themeable_style_property(ui_WifiSwitch, LV_PART_INDICATOR| LV_STATE_CHECKED, LV_STYLE_BG_OPA, _ui_theme_alpha_MainTheme);

ui_LabelWifiSwitch = lv_label_create(ui_WifiScreenContainer);
lv_obj_set_width( ui_LabelWifiSwitch, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelWifiSwitch, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelWifiSwitch, -263 );
lv_obj_set_y( ui_LabelWifiSwitch, -130 );
lv_obj_set_align( ui_LabelWifiSwitch, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelWifiSwitch,"WIFI");
lv_obj_set_style_text_font(ui_LabelWifiSwitch, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_WifiSelectorDropdown = lv_dropdown_create(ui_WifiScreenContainer);
lv_dropdown_set_options( ui_WifiSelectorDropdown, "No Wi-Fi network was found" );
lv_obj_set_width( ui_WifiSelectorDropdown, 572);
lv_obj_set_height( ui_WifiSelectorDropdown, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_WifiSelectorDropdown, 102 );
lv_obj_set_y( ui_WifiSelectorDropdown, -130 );
lv_obj_set_align( ui_WifiSelectorDropdown, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_WifiSelectorDropdown, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_text_font(ui_WifiSelectorDropdown, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(ui_WifiSelectorDropdown, &lv_font_montserrat_20, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(lv_dropdown_get_list(ui_WifiSelectorDropdown), &lv_font_montserrat_20,  LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(lv_dropdown_get_list(ui_WifiSelectorDropdown), &lv_font_montserrat_20,  LV_PART_SELECTED| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(lv_dropdown_get_list(ui_WifiSelectorDropdown),  LV_PART_SELECTED| LV_STATE_CHECKED, LV_STYLE_BG_COLOR, _ui_theme_color_MainTheme);
ui_object_set_themeable_style_property(lv_dropdown_get_list(ui_WifiSelectorDropdown),  LV_PART_SELECTED| LV_STATE_CHECKED, LV_STYLE_BG_OPA, _ui_theme_alpha_MainTheme);

ui_TextAreaWifiPassword = lv_textarea_create(ui_WifiScreenContainer);
lv_obj_set_width( ui_TextAreaWifiPassword, 774);
lv_obj_set_height( ui_TextAreaWifiPassword, LV_SIZE_CONTENT);   /// 49
lv_obj_set_x( ui_TextAreaWifiPassword, 0 );
lv_obj_set_y( ui_TextAreaWifiPassword, -54 );
lv_obj_set_align( ui_TextAreaWifiPassword, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_TextAreaWifiPassword,"Here you can enter your Wi-Fi password . . .");
lv_textarea_set_one_line(ui_TextAreaWifiPassword,true);
lv_textarea_set_password_mode(ui_TextAreaWifiPassword, true);
lv_obj_add_flag( ui_TextAreaWifiPassword, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_text_font(ui_TextAreaWifiPassword, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(ui_TextAreaWifiPassword, &lv_font_montserrat_20, LV_PART_SELECTED| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(ui_TextAreaWifiPassword, &lv_font_montserrat_20, LV_PART_CURSOR| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(ui_TextAreaWifiPassword, &lv_font_montserrat_20, LV_PART_TEXTAREA_PLACEHOLDER| LV_STATE_DEFAULT);

ui_KeyboardWifi = lv_keyboard_create(ui_WifiScreenContainer);
lv_obj_set_width( ui_KeyboardWifi, 793);
lv_obj_set_height( ui_KeyboardWifi, 197);
lv_obj_set_x( ui_KeyboardWifi, 0 );
lv_obj_set_y( ui_KeyboardWifi, 135 );
lv_obj_set_align( ui_KeyboardWifi, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_KeyboardWifi, LV_OBJ_FLAG_HIDDEN );   /// Flags

lv_obj_set_style_text_font(ui_KeyboardWifi, &lv_font_montserrat_20, LV_PART_ITEMS| LV_STATE_DEFAULT);

ui_TimeZoneContainer = lv_obj_create(ui_ScreenSettings);
lv_obj_remove_style_all(ui_TimeZoneContainer);
lv_obj_set_width( ui_TimeZoneContainer, 800);
lv_obj_set_height( ui_TimeZoneContainer, 480);
lv_obj_set_align( ui_TimeZoneContainer, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_TimeZoneContainer, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_TimeZoneContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_TimeZoneContainer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TimeZoneContainer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonBack2 = lv_btn_create(ui_TimeZoneContainer);
lv_obj_set_width( ui_ButtonBack2, 143);
lv_obj_set_height( ui_ButtonBack2, 50);
lv_obj_set_x( ui_ButtonBack2, -320 );
lv_obj_set_y( ui_ButtonBack2, -210 );
lv_obj_set_align( ui_ButtonBack2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonBack2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonBack2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ButtonBack2, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_ButtonBack2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_MainTheme);
ui_object_set_themeable_style_property(ui_ButtonBack2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_MainTheme);

ui_LabelBack3 = lv_label_create(ui_ButtonBack2);
lv_obj_set_width( ui_LabelBack3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelBack3, LV_SIZE_CONTENT);   /// 0
lv_obj_set_align( ui_LabelBack3, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelBack3,"< Settings");
lv_obj_set_style_text_color(ui_LabelBack3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelBack3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_LabelBack3, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelBack3, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonSaveTimeZone = lv_btn_create(ui_TimeZoneContainer);
lv_obj_set_width( ui_ButtonSaveTimeZone, 207);
lv_obj_set_height( ui_ButtonSaveTimeZone, 50);
lv_obj_set_x( ui_ButtonSaveTimeZone, 286 );
lv_obj_set_y( ui_ButtonSaveTimeZone, -210 );
lv_obj_set_align( ui_ButtonSaveTimeZone, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonSaveTimeZone, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonSaveTimeZone, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ButtonSaveTimeZone, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_ButtonSaveTimeZone, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_MainTheme);
ui_object_set_themeable_style_property(ui_ButtonSaveTimeZone, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_MainTheme);

ui_LabelBack4 = lv_label_create(ui_ButtonSaveTimeZone);
lv_obj_set_width( ui_LabelBack4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelBack4, LV_SIZE_CONTENT);   /// 0
lv_obj_set_align( ui_LabelBack4, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelBack4,"Save Time Zone");
lv_obj_set_style_text_color(ui_LabelBack4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelBack4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_LabelBack4, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelBack4, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TimeZoneManager = lv_roller_create(ui_TimeZoneContainer);
lv_roller_set_options( ui_TimeZoneManager, "Oops, something went wrong.", LV_ROLLER_MODE_NORMAL );
lv_obj_set_width( ui_TimeZoneManager, 780);
lv_obj_set_height( ui_TimeZoneManager, 398);
lv_obj_set_x( ui_TimeZoneManager, 0 );
lv_obj_set_y( ui_TimeZoneManager, 26 );
lv_obj_set_align( ui_TimeZoneManager, LV_ALIGN_CENTER );
lv_obj_set_style_text_align(ui_TimeZoneManager, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TimeZoneManager, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_object_set_themeable_style_property(ui_TimeZoneManager, LV_PART_SELECTED| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_MainTheme);
ui_object_set_themeable_style_property(ui_TimeZoneManager, LV_PART_SELECTED| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_MainTheme);

ui_DisplayContainer = lv_obj_create(ui_ScreenSettings);
lv_obj_remove_style_all(ui_DisplayContainer);
lv_obj_set_width( ui_DisplayContainer, 800);
lv_obj_set_height( ui_DisplayContainer, 480);
lv_obj_set_align( ui_DisplayContainer, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_DisplayContainer, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_DisplayContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_DisplayContainer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_DisplayContainer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonBack3 = lv_btn_create(ui_DisplayContainer);
lv_obj_set_width( ui_ButtonBack3, 143);
lv_obj_set_height( ui_ButtonBack3, 50);
lv_obj_set_x( ui_ButtonBack3, -320 );
lv_obj_set_y( ui_ButtonBack3, -210 );
lv_obj_set_align( ui_ButtonBack3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonBack3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonBack3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ButtonBack3, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_ButtonBack3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_MainTheme);
ui_object_set_themeable_style_property(ui_ButtonBack3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_MainTheme);

ui_LabelBack5 = lv_label_create(ui_ButtonBack3);
lv_obj_set_width( ui_LabelBack5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelBack5, LV_SIZE_CONTENT);   /// 0
lv_obj_set_align( ui_LabelBack5, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelBack5,"< Settings");
lv_obj_set_style_text_color(ui_LabelBack5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelBack5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_LabelBack5, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelBack5, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonSaveDisplay = lv_btn_create(ui_DisplayContainer);
lv_obj_set_width( ui_ButtonSaveDisplay, 207);
lv_obj_set_height( ui_ButtonSaveDisplay, 50);
lv_obj_set_x( ui_ButtonSaveDisplay, 286 );
lv_obj_set_y( ui_ButtonSaveDisplay, -210 );
lv_obj_set_align( ui_ButtonSaveDisplay, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonSaveDisplay, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonSaveDisplay, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ButtonSaveDisplay, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_ButtonSaveDisplay, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_MainTheme);
ui_object_set_themeable_style_property(ui_ButtonSaveDisplay, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_MainTheme);

ui_LabelBack6 = lv_label_create(ui_ButtonSaveDisplay);
lv_obj_set_width( ui_LabelBack6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelBack6, LV_SIZE_CONTENT);   /// 0
lv_obj_set_align( ui_LabelBack6, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelBack6,"Save Display");
lv_obj_set_style_text_color(ui_LabelBack6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelBack6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_LabelBack6, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelBack6, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelBrightness = lv_label_create(ui_DisplayContainer);
lv_obj_set_width( ui_LabelBrightness, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelBrightness, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelBrightness, -307 );
lv_obj_set_y( ui_LabelBrightness, -110 );
lv_obj_set_align( ui_LabelBrightness, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelBrightness,"Brightness");
lv_obj_set_style_text_color(ui_LabelBrightness, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelBrightness, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelBrightness, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SliderBrightness = lv_slider_create(ui_DisplayContainer);
lv_slider_set_value( ui_SliderBrightness, 100, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_SliderBrightness)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_SliderBrightness, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_SliderBrightness, 575);
lv_obj_set_height( ui_SliderBrightness, 15);
lv_obj_set_x( ui_SliderBrightness, 73 );
lv_obj_set_y( ui_SliderBrightness, -110 );
lv_obj_set_align( ui_SliderBrightness, LV_ALIGN_CENTER );

ui_object_set_themeable_style_property(ui_SliderBrightness, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_MainTheme);
ui_object_set_themeable_style_property(ui_SliderBrightness, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_MainTheme);

ui_object_set_themeable_style_property(ui_SliderBrightness, LV_PART_KNOB| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_MainTheme);
ui_object_set_themeable_style_property(ui_SliderBrightness, LV_PART_KNOB| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_MainTheme);

ui_DropdownTheme = lv_dropdown_create(ui_DisplayContainer);
lv_dropdown_set_options( ui_DropdownTheme, "Blue Theme\nOrange Theme\nGreen Theme" );
lv_obj_set_width( ui_DropdownTheme, 745);
lv_obj_set_height( ui_DropdownTheme, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_DropdownTheme, 0 );
lv_obj_set_y( ui_DropdownTheme, -40 );
lv_obj_set_align( ui_DropdownTheme, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_DropdownTheme, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_text_font(ui_DropdownTheme, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(ui_DropdownTheme, &lv_font_montserrat_20, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(lv_dropdown_get_list(ui_DropdownTheme), &lv_font_montserrat_20,  LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(lv_dropdown_get_list(ui_DropdownTheme), &lv_font_montserrat_20,  LV_PART_SELECTED| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(lv_dropdown_get_list(ui_DropdownTheme),  LV_PART_SELECTED| LV_STATE_CHECKED, LV_STYLE_BG_COLOR, _ui_theme_color_MainTheme);
ui_object_set_themeable_style_property(lv_dropdown_get_list(ui_DropdownTheme),  LV_PART_SELECTED| LV_STATE_CHECKED, LV_STYLE_BG_OPA, _ui_theme_alpha_MainTheme);

lv_obj_add_event_cb(ui_HomeButton, ui_event_HomeButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonSettingsUpdater, ui_event_ButtonSettingsUpdater, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonSettingsStorage, ui_event_ButtonSettingsStorage, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonSettingsWiFi, ui_event_ButtonSettingsWiFi, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonSettingsTimeZone, ui_event_ButtonSettingsTimeZone, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonSettingsDisplay, ui_event_ButtonSettingsDisplay, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonBack1, ui_event_ButtonBack1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonSaveWifi, ui_event_ButtonSaveWifi, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_WifiSwitch, ui_event_WifiSwitch, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TextAreaWifiPassword, ui_event_TextAreaWifiPassword, LV_EVENT_ALL, NULL);
lv_keyboard_set_textarea(ui_KeyboardWifi,ui_TextAreaWifiPassword);
lv_obj_add_event_cb(ui_ButtonBack2, ui_event_ButtonBack2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonSaveTimeZone, ui_event_ButtonSaveTimeZone, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonBack3, ui_event_ButtonBack3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonSaveDisplay, ui_event_ButtonSaveDisplay, LV_EVENT_ALL, NULL);
uic_ScreenSettings = ui_ScreenSettings;
uic_systemInfoLabel = ui_systemInfoLabel;
uic_ButtonSettingsTimeZone = ui_ButtonSettingsTimeZone;
uic_ButtonSettingsGeneral = ui_ButtonSettingsDisplay;
uic_WifiScreenContainer = ui_WifiScreenContainer;
uic_ButtonSaveWifi = ui_ButtonSaveWifi;
uic_WifiSwitch = ui_WifiSwitch;
uic_WifiSelectorDropdown = ui_WifiSelectorDropdown;
uic_TextAreaWifiPassword = ui_TextAreaWifiPassword;
uic_KeyboardWifi = ui_KeyboardWifi;
uic_TimeZoneContainer = ui_TimeZoneContainer;
uic_ButtonSaveTimeZone = ui_ButtonSaveTimeZone;
uic_TimeZoneManager = ui_TimeZoneManager;
uic_DisplayContainer = ui_DisplayContainer;
uic_ButtonSaveDisplay = ui_ButtonSaveDisplay;
uic_SliderBrightness = ui_SliderBrightness;
uic_DropdownTheme = ui_DropdownTheme;

}

void ui_ScreenSettings_screen_destroy(void)
{
   if (ui_ScreenSettings) lv_obj_del(ui_ScreenSettings);

// NULL screen variables
uic_ScreenSettings= NULL;
ui_ScreenSettings= NULL;
ui_HomeButton= NULL;
ui_LabelMenu1= NULL;
ui_LabelHardwareInformation= NULL;
uic_systemInfoLabel= NULL;
ui_systemInfoLabel= NULL;
ui_LabelSoftwareInformationData= NULL;
ui_ButtonSettingsUpdater= NULL;
ui_LabelSettingsUpdater= NULL;
ui_ButtonSettingsStorage= NULL;
ui_LabelSettingsStorage= NULL;
ui_ButtonSettingsWiFi= NULL;
ui_LabelSettingsWiFi= NULL;
uic_ButtonSettingsTimeZone= NULL;
ui_ButtonSettingsTimeZone= NULL;
ui_LabelSettingsTimeZone= NULL;
uic_ButtonSettingsGeneral= NULL;
ui_ButtonSettingsDisplay= NULL;
ui_LabelSettingsTimeZone1= NULL;
uic_WifiScreenContainer= NULL;
ui_WifiScreenContainer= NULL;
ui_ButtonBack1= NULL;
ui_LabelBack1= NULL;
uic_ButtonSaveWifi= NULL;
ui_ButtonSaveWifi= NULL;
ui_LabelBack2= NULL;
uic_WifiSwitch= NULL;
ui_WifiSwitch= NULL;
ui_LabelWifiSwitch= NULL;
uic_WifiSelectorDropdown= NULL;
ui_WifiSelectorDropdown= NULL;
uic_TextAreaWifiPassword= NULL;
ui_TextAreaWifiPassword= NULL;
uic_KeyboardWifi= NULL;
ui_KeyboardWifi= NULL;
uic_TimeZoneContainer= NULL;
ui_TimeZoneContainer= NULL;
ui_ButtonBack2= NULL;
ui_LabelBack3= NULL;
uic_ButtonSaveTimeZone= NULL;
ui_ButtonSaveTimeZone= NULL;
ui_LabelBack4= NULL;
uic_TimeZoneManager= NULL;
ui_TimeZoneManager= NULL;
uic_DisplayContainer= NULL;
ui_DisplayContainer= NULL;
ui_ButtonBack3= NULL;
ui_LabelBack5= NULL;
uic_ButtonSaveDisplay= NULL;
ui_ButtonSaveDisplay= NULL;
ui_LabelBack6= NULL;
ui_LabelBrightness= NULL;
uic_SliderBrightness= NULL;
ui_SliderBrightness= NULL;
uic_DropdownTheme= NULL;
ui_DropdownTheme= NULL;

}
