// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: fOS_3

#ifndef UI_SCREENSETTINGS_H
#define UI_SCREENSETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenSettings
extern void ui_ScreenSettings_screen_init(void);
extern void ui_ScreenSettings_screen_destroy(void);
extern lv_obj_t *ui_ScreenSettings;
extern void ui_event_HomeButton( lv_event_t * e);
extern lv_obj_t *ui_HomeButton;
extern lv_obj_t *ui_LabelMenu1;
extern lv_obj_t *ui_LabelHardwareInformation;
extern lv_obj_t *ui_systemInfoLabel;
extern lv_obj_t *ui_LabelSoftwareInformationData;
extern void ui_event_ButtonSettingsUpdater( lv_event_t * e);
extern lv_obj_t *ui_ButtonSettingsUpdater;
extern lv_obj_t *ui_LabelSettingsUpdater;
extern void ui_event_ButtonSettingsStorage( lv_event_t * e);
extern lv_obj_t *ui_ButtonSettingsStorage;
extern lv_obj_t *ui_LabelSettingsStorage;
extern void ui_event_ButtonSettingsWiFi( lv_event_t * e);
extern lv_obj_t *ui_ButtonSettingsWiFi;
extern lv_obj_t *ui_LabelSettingsWiFi;
extern void ui_event_ButtonSettingsTimeZone( lv_event_t * e);
extern lv_obj_t *ui_ButtonSettingsTimeZone;
extern lv_obj_t *ui_LabelSettingsTimeZone;
extern void ui_event_ButtonSettingsDisplay( lv_event_t * e);
extern lv_obj_t *ui_ButtonSettingsDisplay;
extern lv_obj_t *ui_LabelSettingsTimeZone1;
extern lv_obj_t *ui_WifiScreenContainer;
extern void ui_event_ButtonBack1( lv_event_t * e);
extern lv_obj_t *ui_ButtonBack1;
extern lv_obj_t *ui_LabelBack1;
extern void ui_event_ButtonSaveWifi( lv_event_t * e);
extern lv_obj_t *ui_ButtonSaveWifi;
extern lv_obj_t *ui_LabelBack2;
extern void ui_event_WifiSwitch( lv_event_t * e);
extern lv_obj_t *ui_WifiSwitch;
extern lv_obj_t *ui_LabelWifiSwitch;
extern lv_obj_t *ui_WifiSelectorDropdown;
extern void ui_event_TextAreaWifiPassword( lv_event_t * e);
extern lv_obj_t *ui_TextAreaWifiPassword;
extern lv_obj_t *ui_KeyboardWifi;
extern lv_obj_t *ui_TimeZoneContainer;
extern void ui_event_ButtonBack2( lv_event_t * e);
extern lv_obj_t *ui_ButtonBack2;
extern lv_obj_t *ui_LabelBack3;
extern void ui_event_ButtonSaveTimeZone( lv_event_t * e);
extern lv_obj_t *ui_ButtonSaveTimeZone;
extern lv_obj_t *ui_LabelBack4;
extern lv_obj_t *ui_TimeZoneManager;
extern lv_obj_t *ui_DisplayContainer;
extern void ui_event_ButtonBack3( lv_event_t * e);
extern lv_obj_t *ui_ButtonBack3;
extern lv_obj_t *ui_LabelBack5;
extern void ui_event_ButtonSaveDisplay( lv_event_t * e);
extern lv_obj_t *ui_ButtonSaveDisplay;
extern lv_obj_t *ui_LabelBack6;
extern lv_obj_t *ui_LabelBrightness;
extern lv_obj_t *ui_SliderBrightness;
extern lv_obj_t *ui_DropdownTheme;
// CUSTOM VARIABLES
extern lv_obj_t *uic_ScreenSettings;
extern lv_obj_t *uic_systemInfoLabel;
extern lv_obj_t *uic_ButtonSettingsTimeZone;
extern lv_obj_t *uic_ButtonSettingsGeneral;
extern lv_obj_t *uic_WifiScreenContainer;
extern lv_obj_t *uic_ButtonSaveWifi;
extern lv_obj_t *uic_WifiSwitch;
extern lv_obj_t *uic_WifiSelectorDropdown;
extern lv_obj_t *uic_TextAreaWifiPassword;
extern lv_obj_t *uic_KeyboardWifi;
extern lv_obj_t *uic_TimeZoneContainer;
extern lv_obj_t *uic_ButtonSaveTimeZone;
extern lv_obj_t *uic_TimeZoneManager;
extern lv_obj_t *uic_DisplayContainer;
extern lv_obj_t *uic_ButtonSaveDisplay;
extern lv_obj_t *uic_SliderBrightness;
extern lv_obj_t *uic_DropdownTheme;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

