// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: fOS_3

#ifndef UI_UPDATE_H
#define UI_UPDATE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Update
extern void ui_Update_screen_init(void);
extern void ui_Update_screen_destroy(void);
extern lv_obj_t *ui_Update;
extern void ui_event_HomeButton2( lv_event_t * e);
extern lv_obj_t *ui_HomeButton2;
extern lv_obj_t *ui_LabelMenu4;
extern lv_obj_t *ui_DropdownUpdate;
extern void ui_event_ButtonInstallUpdate( lv_event_t * e);
extern lv_obj_t *ui_ButtonInstallUpdate;
extern lv_obj_t *ui_LabelInstallUpdate;
extern lv_obj_t *ui_InstallProgressBar;
extern lv_obj_t *ui_DowngradeInfo;
// CUSTOM VARIABLES
extern lv_obj_t *uic_DropdownUpdate;
extern lv_obj_t *uic_InstallProgressBar;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

